// Code generated by servicegen. DO NOT EDIT.

import {
  JsonSerde, MessageContext, SerdeRegistry, SerdeType,
  type RuntimeEnvironment,
  boolSerdeType, bytesSerdeType, errorSerdeType,
  float32SerdeType, float64SerdeType,
  int8SerdeType, int16SerdeType, int32SerdeType, int64SerdeType, intSerdeType,
  makeStreamSerde, runeSerdeType,
  stringSerdeType,
  uint8SerdeType, uint16SerdeType, uint32SerdeType, uint64SerdeType, uintSerdeType,
} from "@gorundebug/tsservicelib/runtime/graph";
import {
  makeCaseStream, makeDelayStream, makeFilterStream, makeFlatMapIterableStream,
  makeFlatMapStream, makeInputStream, makeJoinStream, makeKeyByStream,
  makeLinkStream, makeMapStream, makeMergeStream, makeMultiJoinLink,
  makeMultiJoinStream, makeProcessStream, makeSinkStream,
  makeSinkStreamWithResult, makeSplitStream, makeWhenStream,
} from "@gorundebug/tsservicelib/operators";
import type { AutomationJob } from "@gorundebug/model";
import {
  StreamIds,
  type ConfigSnapshot,
} from "../config/config-snapshot.generated.js";
import {
  ActivityJobEndpointSink, makeActivityJobEndpointSink,
  ActivityJobEndpointSource, makeActivityJobEndpointSource,
  FanoutActivityAEndpointSink, makeFanoutActivityAEndpointSink,
  FanoutActivityAEndpointSource, makeFanoutActivityAEndpointSource,
  FanoutActivityBEndpointSink, makeFanoutActivityBEndpointSink,
  FanoutActivityBEndpointSource, makeFanoutActivityBEndpointSource,
  FanoutActivityCEndpointSink, makeFanoutActivityCEndpointSink,
  FanoutActivityCEndpointSource, makeFanoutActivityCEndpointSource,
  SequentialActivityAEndpointSink, makeSequentialActivityAEndpointSink,
  SequentialActivityAEndpointSource, makeSequentialActivityAEndpointSource,
  SequentialActivityBEndpointSink, makeSequentialActivityBEndpointSink,
  SequentialActivityBEndpointSource, makeSequentialActivityBEndpointSource,
  TemporalActivityScheduleSource, makeTemporalActivityScheduleSource,
  ActivityPause, makeActivityPause,
  ObserveActivityResult, makeObserveActivityResult,
  ObserveFanoutActivityB, makeObserveFanoutActivityB,
  ObserveFanoutActivityC, makeObserveFanoutActivityC,
  ObserveWorkflowResult, makeObserveWorkflowResult,
  ProcessActivityJob, makeProcessActivityJob,
  ProcessFanoutActivityA, makeProcessFanoutActivityA,
  ProcessFanoutActivityB, makeProcessFanoutActivityB,
  ProcessFanoutActivityC, makeProcessFanoutActivityC,
  ProcessScheduledActivity, makeProcessScheduledActivity,
  ProcessScheduledWorkflow, makeProcessScheduledWorkflow,
  ProcessSequentialActivityA, makeProcessSequentialActivityA,
  ProcessSequentialActivityB, makeProcessSequentialActivityB,
  ProcessWorkflowJob, makeProcessWorkflowJob,
  ScheduledActivityPause, makeScheduledActivityPause,
  ScheduledWorkflowPause, makeScheduledWorkflowPause,
  WorkflowPause, makeWorkflowPause,
  LocalScheduleSource, makeLocalScheduleSource,
  FanoutWorkflowJobEndpointSink, makeFanoutWorkflowJobEndpointSink,
  FanoutWorkflowJobEndpointSource, makeFanoutWorkflowJobEndpointSource,
  TemporalWorkflowScheduleSource, makeTemporalWorkflowScheduleSource,
  WorkflowJobEndpointSink, makeWorkflowJobEndpointSink,
  WorkflowJobEndpointSource, makeWorkflowJobEndpointSource,
} from "../functions/index.generated.js";
import {
  defaultAutomationPipelineMakers,
  initAutomationPipelineStreams,
  postInitAutomationPipelineStreams,
} from "./pipeline_automation.generated.js";
import type {
  AutomationPipelineFunctions,
  AutomationPipelineMakers,
  AutomationPipelineStreams,
} from "./pipeline_automation.generated.js";

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const serdeTypes = {
  automationJob: new SerdeType<AutomationJob>("AutomationJob", (value): value is AutomationJob => typeof value === "string"),
} as const;

export function registerGeneratedSerdes(registry: SerdeRegistry): void {
  registry.register(serdeTypes.automationJob, registry.require(stringSerdeType));
  registry.registerStreamValueType(StreamIds.CONSUME_ACTIVITY_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_ACTIVITY_JOB, errorSerdeType);
  registry.registerStreamValueType(StreamIds.ACTIVITY_PAUSE, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.CONSUME_FAN_OUT_WORKFLOW_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_FAN_OUT_WORKFLOW_JOB, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CALL_FAN_OUT_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CALL_FAN_OUT_ACTIVITY_A, errorSerdeType);
  registry.registerStreamValueType(StreamIds.SPLIT_ACTIVITY_A_RESULT, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.CALL_FAN_OUT_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CALL_FAN_OUT_ACTIVITY_B, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CALL_FAN_OUT_ACTIVITY_C, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CALL_FAN_OUT_ACTIVITY_C, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_WORKFLOW_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_WORKFLOW_JOB, errorSerdeType);
  registry.registerStreamValueType(StreamIds.WORKFLOW_PAUSE, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.CALL_SEQUENTIAL_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CALL_SEQUENTIAL_ACTIVITY_A, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CALL_SEQUENTIAL_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CALL_SEQUENTIAL_ACTIVITY_B, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_A, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_B, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_C, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_C, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_SEQUENTIAL_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_SEQUENTIAL_ACTIVITY_A, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_SEQUENTIAL_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_SEQUENTIAL_ACTIVITY_B, errorSerdeType);
  registry.registerStreamValueType(StreamIds.LOCAL_SCHEDULE, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.LOCAL_SCHEDULE, errorSerdeType);
  registry.registerStreamValueType(StreamIds.SPLIT_ON_DEMAND_JOBS, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.SUBMIT_ACTIVITY_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.SUBMIT_ACTIVITY_JOB, errorSerdeType);
  registry.registerStreamValueType(StreamIds.OBSERVE_ACTIVITY_RESULT, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.OBSERVE_FAN_OUT_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.OBSERVE_FAN_OUT_ACTIVITY_C, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.SUBMIT_WORKFLOW_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.SUBMIT_WORKFLOW_JOB, errorSerdeType);
  registry.registerStreamValueType(StreamIds.OBSERVE_WORKFLOW_RESULT, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_ACTIVITY_JOB, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_FAN_OUT_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_FAN_OUT_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_FAN_OUT_ACTIVITY_C, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.TEMPORAL_ACTIVITY_SCHEDULE, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.TEMPORAL_ACTIVITY_SCHEDULE, errorSerdeType);
  registry.registerStreamValueType(StreamIds.SCHEDULED_ACTIVITY_PAUSE, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_SCHEDULED_ACTIVITY, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.TEMPORAL_WORKFLOW_SCHEDULE, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.TEMPORAL_WORKFLOW_SCHEDULE, errorSerdeType);
  registry.registerStreamValueType(StreamIds.SCHEDULED_WORKFLOW_PAUSE, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_SCHEDULED_WORKFLOW, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_SEQUENTIAL_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_SEQUENTIAL_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_WORKFLOW_JOB, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.SUBMIT_FAN_OUT_WORKFLOW_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.SUBMIT_FAN_OUT_WORKFLOW_JOB, errorSerdeType);
}

export type ServiceMakers =
  AutomationPipelineMakers;

export type WorkflowServiceMakers = ServiceMakers;

export function defaultMakers(): ServiceMakers {
  return {
    ...defaultAutomationPipelineMakers(),
  };
}

export function defaultWorkflowMakers(): WorkflowServiceMakers {
  return {
    ...defaultAutomationPipelineMakers(),
  };
}

export type ServiceFunctions =
  AutomationPipelineFunctions;

export async function initFunctions(
  context: MessageContext,
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  makers: WorkflowServiceMakers,
): Promise<ServiceFunctions> {
  let activityJobEndpointSink: ActivityJobEndpointSink;
  let activityJobEndpointSource: ActivityJobEndpointSource;
  let fanoutActivityAEndpointSink: FanoutActivityAEndpointSink;
  let fanoutActivityAEndpointSource: FanoutActivityAEndpointSource;
  let fanoutActivityBEndpointSink: FanoutActivityBEndpointSink;
  let fanoutActivityBEndpointSource: FanoutActivityBEndpointSource;
  let fanoutActivityCEndpointSink: FanoutActivityCEndpointSink;
  let fanoutActivityCEndpointSource: FanoutActivityCEndpointSource;
  let sequentialActivityAEndpointSink: SequentialActivityAEndpointSink;
  let sequentialActivityAEndpointSource: SequentialActivityAEndpointSource;
  let sequentialActivityBEndpointSink: SequentialActivityBEndpointSink;
  let sequentialActivityBEndpointSource: SequentialActivityBEndpointSource;
  let temporalActivityScheduleSource: TemporalActivityScheduleSource;
  let activityPause: ActivityPause;
  let observeActivityResult: ObserveActivityResult;
  let observeFanoutActivityB: ObserveFanoutActivityB;
  let observeFanoutActivityC: ObserveFanoutActivityC;
  let observeWorkflowResult: ObserveWorkflowResult;
  let processActivityJob: ProcessActivityJob;
  let processFanoutActivityA: ProcessFanoutActivityA;
  let processFanoutActivityB: ProcessFanoutActivityB;
  let processFanoutActivityC: ProcessFanoutActivityC;
  let processScheduledActivity: ProcessScheduledActivity;
  let processScheduledWorkflow: ProcessScheduledWorkflow;
  let processSequentialActivityA: ProcessSequentialActivityA;
  let processSequentialActivityB: ProcessSequentialActivityB;
  let processWorkflowJob: ProcessWorkflowJob;
  let scheduledActivityPause: ScheduledActivityPause;
  let scheduledWorkflowPause: ScheduledWorkflowPause;
  let workflowPause: WorkflowPause;
  let localScheduleSource: LocalScheduleSource;
  let fanoutWorkflowJobEndpointSink: FanoutWorkflowJobEndpointSink;
  let fanoutWorkflowJobEndpointSource: FanoutWorkflowJobEndpointSource;
  let temporalWorkflowScheduleSource: TemporalWorkflowScheduleSource;
  let workflowJobEndpointSink: WorkflowJobEndpointSink;
  let workflowJobEndpointSource: WorkflowJobEndpointSource;
  {
    const controller = new AbortController();
    const makerContext = context.withExternalCancellation(controller.signal);
    let firstError: unknown;
    let failed = false;
    const invokeMaker = async <T>(maker: () => Promise<T>): Promise<T> => {
      try {
        return await maker();
      } catch (error) {
        if (!failed) {
          failed = true;
          firstError = error;
          controller.abort(error);
        }
        throw error;
      }
    };
    const group = await Promise.allSettled([
      invokeMaker(() => makers.activityJobEndpointSink(
        makerContext, environment, config.named.endpoints.activityJob,
      )),
      invokeMaker(() => makers.activityJobEndpointSource(
        makerContext, environment, config.named.endpoints.activityJob,
      )),
      invokeMaker(() => makers.fanoutActivityAEndpointSink(
        makerContext, environment, config.named.endpoints.fanOutActivityA,
      )),
      invokeMaker(() => makers.fanoutActivityAEndpointSource(
        makerContext, environment, config.named.endpoints.fanOutActivityA,
      )),
      invokeMaker(() => makers.fanoutActivityBEndpointSink(
        makerContext, environment, config.named.endpoints.fanOutActivityB,
      )),
      invokeMaker(() => makers.fanoutActivityBEndpointSource(
        makerContext, environment, config.named.endpoints.fanOutActivityB,
      )),
      invokeMaker(() => makers.fanoutActivityCEndpointSink(
        makerContext, environment, config.named.endpoints.fanOutActivityC,
      )),
      invokeMaker(() => makers.fanoutActivityCEndpointSource(
        makerContext, environment, config.named.endpoints.fanOutActivityC,
      )),
      invokeMaker(() => makers.sequentialActivityAEndpointSink(
        makerContext, environment, config.named.endpoints.sequentialActivityA,
      )),
      invokeMaker(() => makers.sequentialActivityAEndpointSource(
        makerContext, environment, config.named.endpoints.sequentialActivityA,
      )),
      invokeMaker(() => makers.sequentialActivityBEndpointSink(
        makerContext, environment, config.named.endpoints.sequentialActivityB,
      )),
      invokeMaker(() => makers.sequentialActivityBEndpointSource(
        makerContext, environment, config.named.endpoints.sequentialActivityB,
      )),
      invokeMaker(() => makers.temporalActivityScheduleSource(
        makerContext, environment, config.named.endpoints.temporalActivitySchedule,
      )),
      invokeMaker(() => makers.activityPause(
        makerContext, environment, config.named.streams.activityPause,
      )),
      invokeMaker(() => makers.observeActivityResult(
        makerContext, environment, config.named.streams.observeActivityResult,
      )),
      invokeMaker(() => makers.observeFanoutActivityB(
        makerContext, environment, config.named.streams.observeFanOutActivityB,
      )),
      invokeMaker(() => makers.observeFanoutActivityC(
        makerContext, environment, config.named.streams.observeFanOutActivityC,
      )),
      invokeMaker(() => makers.observeWorkflowResult(
        makerContext, environment, config.named.streams.observeWorkflowResult,
      )),
      invokeMaker(() => makers.processActivityJob(
        makerContext, environment, config.named.streams.processActivityJob,
      )),
      invokeMaker(() => makers.processFanoutActivityA(
        makerContext, environment, config.named.streams.processFanOutActivityA,
      )),
      invokeMaker(() => makers.processFanoutActivityB(
        makerContext, environment, config.named.streams.processFanOutActivityB,
      )),
      invokeMaker(() => makers.processFanoutActivityC(
        makerContext, environment, config.named.streams.processFanOutActivityC,
      )),
      invokeMaker(() => makers.processScheduledActivity(
        makerContext, environment, config.named.streams.processScheduledActivity,
      )),
      invokeMaker(() => makers.processScheduledWorkflow(
        makerContext, environment, config.named.streams.processScheduledWorkflow,
      )),
      invokeMaker(() => makers.processSequentialActivityA(
        makerContext, environment, config.named.streams.processSequentialActivityA,
      )),
      invokeMaker(() => makers.processSequentialActivityB(
        makerContext, environment, config.named.streams.processSequentialActivityB,
      )),
      invokeMaker(() => makers.processWorkflowJob(
        makerContext, environment, config.named.streams.processWorkflowJob,
      )),
      invokeMaker(() => makers.scheduledActivityPause(
        makerContext, environment, config.named.streams.scheduledActivityPause,
      )),
      invokeMaker(() => makers.scheduledWorkflowPause(
        makerContext, environment, config.named.streams.scheduledWorkflowPause,
      )),
      invokeMaker(() => makers.workflowPause(
        makerContext, environment, config.named.streams.workflowPause,
      )),
      invokeMaker(() => makers.localScheduleSource(
        makerContext, environment, config.named.endpoints.localSchedule,
      )),
      invokeMaker(() => makers.fanoutWorkflowJobEndpointSink(
        makerContext, environment, config.named.endpoints.fanOutWorkflowJob,
      )),
      invokeMaker(() => makers.fanoutWorkflowJobEndpointSource(
        makerContext, environment, config.named.endpoints.fanOutWorkflowJob,
      )),
      invokeMaker(() => makers.temporalWorkflowScheduleSource(
        makerContext, environment, config.named.endpoints.temporalWorkflowSchedule,
      )),
      invokeMaker(() => makers.workflowJobEndpointSink(
        makerContext, environment, config.named.endpoints.workflowJob,
      )),
      invokeMaker(() => makers.workflowJobEndpointSource(
        makerContext, environment, config.named.endpoints.workflowJob,
      )),
    ] as const);
    controller.abort();
    if (failed) throw firstError;
    const activityJobEndpointSinkResult0 = group[0];
    if (activityJobEndpointSinkResult0.status !== "fulfilled") {
      throw activityJobEndpointSinkResult0.reason;
    }
    activityJobEndpointSink = activityJobEndpointSinkResult0.value;
    const activityJobEndpointSourceResult0 = group[1];
    if (activityJobEndpointSourceResult0.status !== "fulfilled") {
      throw activityJobEndpointSourceResult0.reason;
    }
    activityJobEndpointSource = activityJobEndpointSourceResult0.value;
    const fanoutActivityAEndpointSinkResult0 = group[2];
    if (fanoutActivityAEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutActivityAEndpointSinkResult0.reason;
    }
    fanoutActivityAEndpointSink = fanoutActivityAEndpointSinkResult0.value;
    const fanoutActivityAEndpointSourceResult0 = group[3];
    if (fanoutActivityAEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutActivityAEndpointSourceResult0.reason;
    }
    fanoutActivityAEndpointSource = fanoutActivityAEndpointSourceResult0.value;
    const fanoutActivityBEndpointSinkResult0 = group[4];
    if (fanoutActivityBEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutActivityBEndpointSinkResult0.reason;
    }
    fanoutActivityBEndpointSink = fanoutActivityBEndpointSinkResult0.value;
    const fanoutActivityBEndpointSourceResult0 = group[5];
    if (fanoutActivityBEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutActivityBEndpointSourceResult0.reason;
    }
    fanoutActivityBEndpointSource = fanoutActivityBEndpointSourceResult0.value;
    const fanoutActivityCEndpointSinkResult0 = group[6];
    if (fanoutActivityCEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutActivityCEndpointSinkResult0.reason;
    }
    fanoutActivityCEndpointSink = fanoutActivityCEndpointSinkResult0.value;
    const fanoutActivityCEndpointSourceResult0 = group[7];
    if (fanoutActivityCEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutActivityCEndpointSourceResult0.reason;
    }
    fanoutActivityCEndpointSource = fanoutActivityCEndpointSourceResult0.value;
    const sequentialActivityAEndpointSinkResult0 = group[8];
    if (sequentialActivityAEndpointSinkResult0.status !== "fulfilled") {
      throw sequentialActivityAEndpointSinkResult0.reason;
    }
    sequentialActivityAEndpointSink = sequentialActivityAEndpointSinkResult0.value;
    const sequentialActivityAEndpointSourceResult0 = group[9];
    if (sequentialActivityAEndpointSourceResult0.status !== "fulfilled") {
      throw sequentialActivityAEndpointSourceResult0.reason;
    }
    sequentialActivityAEndpointSource = sequentialActivityAEndpointSourceResult0.value;
    const sequentialActivityBEndpointSinkResult0 = group[10];
    if (sequentialActivityBEndpointSinkResult0.status !== "fulfilled") {
      throw sequentialActivityBEndpointSinkResult0.reason;
    }
    sequentialActivityBEndpointSink = sequentialActivityBEndpointSinkResult0.value;
    const sequentialActivityBEndpointSourceResult0 = group[11];
    if (sequentialActivityBEndpointSourceResult0.status !== "fulfilled") {
      throw sequentialActivityBEndpointSourceResult0.reason;
    }
    sequentialActivityBEndpointSource = sequentialActivityBEndpointSourceResult0.value;
    const temporalActivityScheduleSourceResult0 = group[12];
    if (temporalActivityScheduleSourceResult0.status !== "fulfilled") {
      throw temporalActivityScheduleSourceResult0.reason;
    }
    temporalActivityScheduleSource = temporalActivityScheduleSourceResult0.value;
    const activityPauseResult0 = group[13];
    if (activityPauseResult0.status !== "fulfilled") {
      throw activityPauseResult0.reason;
    }
    activityPause = activityPauseResult0.value;
    const observeActivityResultResult0 = group[14];
    if (observeActivityResultResult0.status !== "fulfilled") {
      throw observeActivityResultResult0.reason;
    }
    observeActivityResult = observeActivityResultResult0.value;
    const observeFanoutActivityBResult0 = group[15];
    if (observeFanoutActivityBResult0.status !== "fulfilled") {
      throw observeFanoutActivityBResult0.reason;
    }
    observeFanoutActivityB = observeFanoutActivityBResult0.value;
    const observeFanoutActivityCResult0 = group[16];
    if (observeFanoutActivityCResult0.status !== "fulfilled") {
      throw observeFanoutActivityCResult0.reason;
    }
    observeFanoutActivityC = observeFanoutActivityCResult0.value;
    const observeWorkflowResultResult0 = group[17];
    if (observeWorkflowResultResult0.status !== "fulfilled") {
      throw observeWorkflowResultResult0.reason;
    }
    observeWorkflowResult = observeWorkflowResultResult0.value;
    const processActivityJobResult0 = group[18];
    if (processActivityJobResult0.status !== "fulfilled") {
      throw processActivityJobResult0.reason;
    }
    processActivityJob = processActivityJobResult0.value;
    const processFanoutActivityAResult0 = group[19];
    if (processFanoutActivityAResult0.status !== "fulfilled") {
      throw processFanoutActivityAResult0.reason;
    }
    processFanoutActivityA = processFanoutActivityAResult0.value;
    const processFanoutActivityBResult0 = group[20];
    if (processFanoutActivityBResult0.status !== "fulfilled") {
      throw processFanoutActivityBResult0.reason;
    }
    processFanoutActivityB = processFanoutActivityBResult0.value;
    const processFanoutActivityCResult0 = group[21];
    if (processFanoutActivityCResult0.status !== "fulfilled") {
      throw processFanoutActivityCResult0.reason;
    }
    processFanoutActivityC = processFanoutActivityCResult0.value;
    const processScheduledActivityResult0 = group[22];
    if (processScheduledActivityResult0.status !== "fulfilled") {
      throw processScheduledActivityResult0.reason;
    }
    processScheduledActivity = processScheduledActivityResult0.value;
    const processScheduledWorkflowResult0 = group[23];
    if (processScheduledWorkflowResult0.status !== "fulfilled") {
      throw processScheduledWorkflowResult0.reason;
    }
    processScheduledWorkflow = processScheduledWorkflowResult0.value;
    const processSequentialActivityAResult0 = group[24];
    if (processSequentialActivityAResult0.status !== "fulfilled") {
      throw processSequentialActivityAResult0.reason;
    }
    processSequentialActivityA = processSequentialActivityAResult0.value;
    const processSequentialActivityBResult0 = group[25];
    if (processSequentialActivityBResult0.status !== "fulfilled") {
      throw processSequentialActivityBResult0.reason;
    }
    processSequentialActivityB = processSequentialActivityBResult0.value;
    const processWorkflowJobResult0 = group[26];
    if (processWorkflowJobResult0.status !== "fulfilled") {
      throw processWorkflowJobResult0.reason;
    }
    processWorkflowJob = processWorkflowJobResult0.value;
    const scheduledActivityPauseResult0 = group[27];
    if (scheduledActivityPauseResult0.status !== "fulfilled") {
      throw scheduledActivityPauseResult0.reason;
    }
    scheduledActivityPause = scheduledActivityPauseResult0.value;
    const scheduledWorkflowPauseResult0 = group[28];
    if (scheduledWorkflowPauseResult0.status !== "fulfilled") {
      throw scheduledWorkflowPauseResult0.reason;
    }
    scheduledWorkflowPause = scheduledWorkflowPauseResult0.value;
    const workflowPauseResult0 = group[29];
    if (workflowPauseResult0.status !== "fulfilled") {
      throw workflowPauseResult0.reason;
    }
    workflowPause = workflowPauseResult0.value;
    const localScheduleSourceResult0 = group[30];
    if (localScheduleSourceResult0.status !== "fulfilled") {
      throw localScheduleSourceResult0.reason;
    }
    localScheduleSource = localScheduleSourceResult0.value;
    const fanoutWorkflowJobEndpointSinkResult0 = group[31];
    if (fanoutWorkflowJobEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutWorkflowJobEndpointSinkResult0.reason;
    }
    fanoutWorkflowJobEndpointSink = fanoutWorkflowJobEndpointSinkResult0.value;
    const fanoutWorkflowJobEndpointSourceResult0 = group[32];
    if (fanoutWorkflowJobEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutWorkflowJobEndpointSourceResult0.reason;
    }
    fanoutWorkflowJobEndpointSource = fanoutWorkflowJobEndpointSourceResult0.value;
    const temporalWorkflowScheduleSourceResult0 = group[33];
    if (temporalWorkflowScheduleSourceResult0.status !== "fulfilled") {
      throw temporalWorkflowScheduleSourceResult0.reason;
    }
    temporalWorkflowScheduleSource = temporalWorkflowScheduleSourceResult0.value;
    const workflowJobEndpointSinkResult0 = group[34];
    if (workflowJobEndpointSinkResult0.status !== "fulfilled") {
      throw workflowJobEndpointSinkResult0.reason;
    }
    workflowJobEndpointSink = workflowJobEndpointSinkResult0.value;
    const workflowJobEndpointSourceResult0 = group[35];
    if (workflowJobEndpointSourceResult0.status !== "fulfilled") {
      throw workflowJobEndpointSourceResult0.reason;
    }
    workflowJobEndpointSource = workflowJobEndpointSourceResult0.value;
  }
  return {
    activityJobEndpointSink,
    activityJobEndpointSource,
    fanoutActivityAEndpointSink,
    fanoutActivityAEndpointSource,
    fanoutActivityBEndpointSink,
    fanoutActivityBEndpointSource,
    fanoutActivityCEndpointSink,
    fanoutActivityCEndpointSource,
    sequentialActivityAEndpointSink,
    sequentialActivityAEndpointSource,
    sequentialActivityBEndpointSink,
    sequentialActivityBEndpointSource,
    temporalActivityScheduleSource,
    activityPause,
    observeActivityResult,
    observeFanoutActivityB,
    observeFanoutActivityC,
    observeWorkflowResult,
    processActivityJob,
    processFanoutActivityA,
    processFanoutActivityB,
    processFanoutActivityC,
    processScheduledActivity,
    processScheduledWorkflow,
    processSequentialActivityA,
    processSequentialActivityB,
    processWorkflowJob,
    scheduledActivityPause,
    scheduledWorkflowPause,
    workflowPause,
    localScheduleSource,
    fanoutWorkflowJobEndpointSink,
    fanoutWorkflowJobEndpointSource,
    temporalWorkflowScheduleSource,
    workflowJobEndpointSink,
    workflowJobEndpointSource,
  };
}

export async function initFunctionsParallel(
  context: MessageContext,
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  makers: ServiceMakers,
): Promise<ServiceFunctions> {
  let activityJobEndpointSink: ActivityJobEndpointSink;
  let activityJobEndpointSource: ActivityJobEndpointSource;
  let fanoutActivityAEndpointSink: FanoutActivityAEndpointSink;
  let fanoutActivityAEndpointSource: FanoutActivityAEndpointSource;
  let fanoutActivityBEndpointSink: FanoutActivityBEndpointSink;
  let fanoutActivityBEndpointSource: FanoutActivityBEndpointSource;
  let fanoutActivityCEndpointSink: FanoutActivityCEndpointSink;
  let fanoutActivityCEndpointSource: FanoutActivityCEndpointSource;
  let sequentialActivityAEndpointSink: SequentialActivityAEndpointSink;
  let sequentialActivityAEndpointSource: SequentialActivityAEndpointSource;
  let sequentialActivityBEndpointSink: SequentialActivityBEndpointSink;
  let sequentialActivityBEndpointSource: SequentialActivityBEndpointSource;
  let temporalActivityScheduleSource: TemporalActivityScheduleSource;
  let activityPause: ActivityPause;
  let observeActivityResult: ObserveActivityResult;
  let observeFanoutActivityB: ObserveFanoutActivityB;
  let observeFanoutActivityC: ObserveFanoutActivityC;
  let observeWorkflowResult: ObserveWorkflowResult;
  let processActivityJob: ProcessActivityJob;
  let processFanoutActivityA: ProcessFanoutActivityA;
  let processFanoutActivityB: ProcessFanoutActivityB;
  let processFanoutActivityC: ProcessFanoutActivityC;
  let processScheduledActivity: ProcessScheduledActivity;
  let processScheduledWorkflow: ProcessScheduledWorkflow;
  let processSequentialActivityA: ProcessSequentialActivityA;
  let processSequentialActivityB: ProcessSequentialActivityB;
  let processWorkflowJob: ProcessWorkflowJob;
  let scheduledActivityPause: ScheduledActivityPause;
  let scheduledWorkflowPause: ScheduledWorkflowPause;
  let workflowPause: WorkflowPause;
  let localScheduleSource: LocalScheduleSource;
  let fanoutWorkflowJobEndpointSink: FanoutWorkflowJobEndpointSink;
  let fanoutWorkflowJobEndpointSource: FanoutWorkflowJobEndpointSource;
  let temporalWorkflowScheduleSource: TemporalWorkflowScheduleSource;
  let workflowJobEndpointSink: WorkflowJobEndpointSink;
  let workflowJobEndpointSource: WorkflowJobEndpointSource;
  {
    const controller = new AbortController();
    const makerContext = context.withExternalCancellation(controller.signal);
    let firstError: unknown;
    let failed = false;
    const invokeMaker = async <T>(maker: () => Promise<T>): Promise<T> => {
      try {
        return await maker();
      } catch (error) {
        if (!failed) {
          failed = true;
          firstError = error;
          controller.abort(error);
        }
        throw error;
      }
    };
    const group = await Promise.allSettled([
      invokeMaker(() => makers.activityJobEndpointSink(
        makerContext, environment, config.named.endpoints.activityJob,
      )),
      invokeMaker(() => makers.activityJobEndpointSource(
        makerContext, environment, config.named.endpoints.activityJob,
      )),
      invokeMaker(() => makers.fanoutActivityAEndpointSink(
        makerContext, environment, config.named.endpoints.fanOutActivityA,
      )),
      invokeMaker(() => makers.fanoutActivityAEndpointSource(
        makerContext, environment, config.named.endpoints.fanOutActivityA,
      )),
      invokeMaker(() => makers.fanoutActivityBEndpointSink(
        makerContext, environment, config.named.endpoints.fanOutActivityB,
      )),
      invokeMaker(() => makers.fanoutActivityBEndpointSource(
        makerContext, environment, config.named.endpoints.fanOutActivityB,
      )),
      invokeMaker(() => makers.fanoutActivityCEndpointSink(
        makerContext, environment, config.named.endpoints.fanOutActivityC,
      )),
      invokeMaker(() => makers.fanoutActivityCEndpointSource(
        makerContext, environment, config.named.endpoints.fanOutActivityC,
      )),
      invokeMaker(() => makers.sequentialActivityAEndpointSink(
        makerContext, environment, config.named.endpoints.sequentialActivityA,
      )),
      invokeMaker(() => makers.sequentialActivityAEndpointSource(
        makerContext, environment, config.named.endpoints.sequentialActivityA,
      )),
      invokeMaker(() => makers.sequentialActivityBEndpointSink(
        makerContext, environment, config.named.endpoints.sequentialActivityB,
      )),
      invokeMaker(() => makers.sequentialActivityBEndpointSource(
        makerContext, environment, config.named.endpoints.sequentialActivityB,
      )),
      invokeMaker(() => makers.temporalActivityScheduleSource(
        makerContext, environment, config.named.endpoints.temporalActivitySchedule,
      )),
      invokeMaker(() => makers.activityPause(
        makerContext, environment, config.named.streams.activityPause,
      )),
      invokeMaker(() => makers.observeActivityResult(
        makerContext, environment, config.named.streams.observeActivityResult,
      )),
      invokeMaker(() => makers.observeFanoutActivityB(
        makerContext, environment, config.named.streams.observeFanOutActivityB,
      )),
      invokeMaker(() => makers.observeFanoutActivityC(
        makerContext, environment, config.named.streams.observeFanOutActivityC,
      )),
      invokeMaker(() => makers.observeWorkflowResult(
        makerContext, environment, config.named.streams.observeWorkflowResult,
      )),
      invokeMaker(() => makers.processActivityJob(
        makerContext, environment, config.named.streams.processActivityJob,
      )),
      invokeMaker(() => makers.processFanoutActivityA(
        makerContext, environment, config.named.streams.processFanOutActivityA,
      )),
      invokeMaker(() => makers.processFanoutActivityB(
        makerContext, environment, config.named.streams.processFanOutActivityB,
      )),
      invokeMaker(() => makers.processFanoutActivityC(
        makerContext, environment, config.named.streams.processFanOutActivityC,
      )),
      invokeMaker(() => makers.processScheduledActivity(
        makerContext, environment, config.named.streams.processScheduledActivity,
      )),
      invokeMaker(() => makers.processScheduledWorkflow(
        makerContext, environment, config.named.streams.processScheduledWorkflow,
      )),
      invokeMaker(() => makers.processSequentialActivityA(
        makerContext, environment, config.named.streams.processSequentialActivityA,
      )),
      invokeMaker(() => makers.processSequentialActivityB(
        makerContext, environment, config.named.streams.processSequentialActivityB,
      )),
      invokeMaker(() => makers.processWorkflowJob(
        makerContext, environment, config.named.streams.processWorkflowJob,
      )),
      invokeMaker(() => makers.scheduledActivityPause(
        makerContext, environment, config.named.streams.scheduledActivityPause,
      )),
      invokeMaker(() => makers.scheduledWorkflowPause(
        makerContext, environment, config.named.streams.scheduledWorkflowPause,
      )),
      invokeMaker(() => makers.workflowPause(
        makerContext, environment, config.named.streams.workflowPause,
      )),
      invokeMaker(() => makers.localScheduleSource(
        makerContext, environment, config.named.endpoints.localSchedule,
      )),
      invokeMaker(() => makers.fanoutWorkflowJobEndpointSink(
        makerContext, environment, config.named.endpoints.fanOutWorkflowJob,
      )),
      invokeMaker(() => makers.fanoutWorkflowJobEndpointSource(
        makerContext, environment, config.named.endpoints.fanOutWorkflowJob,
      )),
      invokeMaker(() => makers.temporalWorkflowScheduleSource(
        makerContext, environment, config.named.endpoints.temporalWorkflowSchedule,
      )),
      invokeMaker(() => makers.workflowJobEndpointSink(
        makerContext, environment, config.named.endpoints.workflowJob,
      )),
      invokeMaker(() => makers.workflowJobEndpointSource(
        makerContext, environment, config.named.endpoints.workflowJob,
      )),
    ] as const);
    controller.abort();
    if (failed) throw firstError;
    const activityJobEndpointSinkResult0 = group[0];
    if (activityJobEndpointSinkResult0.status !== "fulfilled") {
      throw activityJobEndpointSinkResult0.reason;
    }
    activityJobEndpointSink = activityJobEndpointSinkResult0.value;
    const activityJobEndpointSourceResult0 = group[1];
    if (activityJobEndpointSourceResult0.status !== "fulfilled") {
      throw activityJobEndpointSourceResult0.reason;
    }
    activityJobEndpointSource = activityJobEndpointSourceResult0.value;
    const fanoutActivityAEndpointSinkResult0 = group[2];
    if (fanoutActivityAEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutActivityAEndpointSinkResult0.reason;
    }
    fanoutActivityAEndpointSink = fanoutActivityAEndpointSinkResult0.value;
    const fanoutActivityAEndpointSourceResult0 = group[3];
    if (fanoutActivityAEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutActivityAEndpointSourceResult0.reason;
    }
    fanoutActivityAEndpointSource = fanoutActivityAEndpointSourceResult0.value;
    const fanoutActivityBEndpointSinkResult0 = group[4];
    if (fanoutActivityBEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutActivityBEndpointSinkResult0.reason;
    }
    fanoutActivityBEndpointSink = fanoutActivityBEndpointSinkResult0.value;
    const fanoutActivityBEndpointSourceResult0 = group[5];
    if (fanoutActivityBEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutActivityBEndpointSourceResult0.reason;
    }
    fanoutActivityBEndpointSource = fanoutActivityBEndpointSourceResult0.value;
    const fanoutActivityCEndpointSinkResult0 = group[6];
    if (fanoutActivityCEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutActivityCEndpointSinkResult0.reason;
    }
    fanoutActivityCEndpointSink = fanoutActivityCEndpointSinkResult0.value;
    const fanoutActivityCEndpointSourceResult0 = group[7];
    if (fanoutActivityCEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutActivityCEndpointSourceResult0.reason;
    }
    fanoutActivityCEndpointSource = fanoutActivityCEndpointSourceResult0.value;
    const sequentialActivityAEndpointSinkResult0 = group[8];
    if (sequentialActivityAEndpointSinkResult0.status !== "fulfilled") {
      throw sequentialActivityAEndpointSinkResult0.reason;
    }
    sequentialActivityAEndpointSink = sequentialActivityAEndpointSinkResult0.value;
    const sequentialActivityAEndpointSourceResult0 = group[9];
    if (sequentialActivityAEndpointSourceResult0.status !== "fulfilled") {
      throw sequentialActivityAEndpointSourceResult0.reason;
    }
    sequentialActivityAEndpointSource = sequentialActivityAEndpointSourceResult0.value;
    const sequentialActivityBEndpointSinkResult0 = group[10];
    if (sequentialActivityBEndpointSinkResult0.status !== "fulfilled") {
      throw sequentialActivityBEndpointSinkResult0.reason;
    }
    sequentialActivityBEndpointSink = sequentialActivityBEndpointSinkResult0.value;
    const sequentialActivityBEndpointSourceResult0 = group[11];
    if (sequentialActivityBEndpointSourceResult0.status !== "fulfilled") {
      throw sequentialActivityBEndpointSourceResult0.reason;
    }
    sequentialActivityBEndpointSource = sequentialActivityBEndpointSourceResult0.value;
    const temporalActivityScheduleSourceResult0 = group[12];
    if (temporalActivityScheduleSourceResult0.status !== "fulfilled") {
      throw temporalActivityScheduleSourceResult0.reason;
    }
    temporalActivityScheduleSource = temporalActivityScheduleSourceResult0.value;
    const activityPauseResult0 = group[13];
    if (activityPauseResult0.status !== "fulfilled") {
      throw activityPauseResult0.reason;
    }
    activityPause = activityPauseResult0.value;
    const observeActivityResultResult0 = group[14];
    if (observeActivityResultResult0.status !== "fulfilled") {
      throw observeActivityResultResult0.reason;
    }
    observeActivityResult = observeActivityResultResult0.value;
    const observeFanoutActivityBResult0 = group[15];
    if (observeFanoutActivityBResult0.status !== "fulfilled") {
      throw observeFanoutActivityBResult0.reason;
    }
    observeFanoutActivityB = observeFanoutActivityBResult0.value;
    const observeFanoutActivityCResult0 = group[16];
    if (observeFanoutActivityCResult0.status !== "fulfilled") {
      throw observeFanoutActivityCResult0.reason;
    }
    observeFanoutActivityC = observeFanoutActivityCResult0.value;
    const observeWorkflowResultResult0 = group[17];
    if (observeWorkflowResultResult0.status !== "fulfilled") {
      throw observeWorkflowResultResult0.reason;
    }
    observeWorkflowResult = observeWorkflowResultResult0.value;
    const processActivityJobResult0 = group[18];
    if (processActivityJobResult0.status !== "fulfilled") {
      throw processActivityJobResult0.reason;
    }
    processActivityJob = processActivityJobResult0.value;
    const processFanoutActivityAResult0 = group[19];
    if (processFanoutActivityAResult0.status !== "fulfilled") {
      throw processFanoutActivityAResult0.reason;
    }
    processFanoutActivityA = processFanoutActivityAResult0.value;
    const processFanoutActivityBResult0 = group[20];
    if (processFanoutActivityBResult0.status !== "fulfilled") {
      throw processFanoutActivityBResult0.reason;
    }
    processFanoutActivityB = processFanoutActivityBResult0.value;
    const processFanoutActivityCResult0 = group[21];
    if (processFanoutActivityCResult0.status !== "fulfilled") {
      throw processFanoutActivityCResult0.reason;
    }
    processFanoutActivityC = processFanoutActivityCResult0.value;
    const processScheduledActivityResult0 = group[22];
    if (processScheduledActivityResult0.status !== "fulfilled") {
      throw processScheduledActivityResult0.reason;
    }
    processScheduledActivity = processScheduledActivityResult0.value;
    const processScheduledWorkflowResult0 = group[23];
    if (processScheduledWorkflowResult0.status !== "fulfilled") {
      throw processScheduledWorkflowResult0.reason;
    }
    processScheduledWorkflow = processScheduledWorkflowResult0.value;
    const processSequentialActivityAResult0 = group[24];
    if (processSequentialActivityAResult0.status !== "fulfilled") {
      throw processSequentialActivityAResult0.reason;
    }
    processSequentialActivityA = processSequentialActivityAResult0.value;
    const processSequentialActivityBResult0 = group[25];
    if (processSequentialActivityBResult0.status !== "fulfilled") {
      throw processSequentialActivityBResult0.reason;
    }
    processSequentialActivityB = processSequentialActivityBResult0.value;
    const processWorkflowJobResult0 = group[26];
    if (processWorkflowJobResult0.status !== "fulfilled") {
      throw processWorkflowJobResult0.reason;
    }
    processWorkflowJob = processWorkflowJobResult0.value;
    const scheduledActivityPauseResult0 = group[27];
    if (scheduledActivityPauseResult0.status !== "fulfilled") {
      throw scheduledActivityPauseResult0.reason;
    }
    scheduledActivityPause = scheduledActivityPauseResult0.value;
    const scheduledWorkflowPauseResult0 = group[28];
    if (scheduledWorkflowPauseResult0.status !== "fulfilled") {
      throw scheduledWorkflowPauseResult0.reason;
    }
    scheduledWorkflowPause = scheduledWorkflowPauseResult0.value;
    const workflowPauseResult0 = group[29];
    if (workflowPauseResult0.status !== "fulfilled") {
      throw workflowPauseResult0.reason;
    }
    workflowPause = workflowPauseResult0.value;
    const localScheduleSourceResult0 = group[30];
    if (localScheduleSourceResult0.status !== "fulfilled") {
      throw localScheduleSourceResult0.reason;
    }
    localScheduleSource = localScheduleSourceResult0.value;
    const fanoutWorkflowJobEndpointSinkResult0 = group[31];
    if (fanoutWorkflowJobEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutWorkflowJobEndpointSinkResult0.reason;
    }
    fanoutWorkflowJobEndpointSink = fanoutWorkflowJobEndpointSinkResult0.value;
    const fanoutWorkflowJobEndpointSourceResult0 = group[32];
    if (fanoutWorkflowJobEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutWorkflowJobEndpointSourceResult0.reason;
    }
    fanoutWorkflowJobEndpointSource = fanoutWorkflowJobEndpointSourceResult0.value;
    const temporalWorkflowScheduleSourceResult0 = group[33];
    if (temporalWorkflowScheduleSourceResult0.status !== "fulfilled") {
      throw temporalWorkflowScheduleSourceResult0.reason;
    }
    temporalWorkflowScheduleSource = temporalWorkflowScheduleSourceResult0.value;
    const workflowJobEndpointSinkResult0 = group[34];
    if (workflowJobEndpointSinkResult0.status !== "fulfilled") {
      throw workflowJobEndpointSinkResult0.reason;
    }
    workflowJobEndpointSink = workflowJobEndpointSinkResult0.value;
    const workflowJobEndpointSourceResult0 = group[35];
    if (workflowJobEndpointSourceResult0.status !== "fulfilled") {
      throw workflowJobEndpointSourceResult0.reason;
    }
    workflowJobEndpointSource = workflowJobEndpointSourceResult0.value;
  }
  return {
    activityJobEndpointSink,
    activityJobEndpointSource,
    fanoutActivityAEndpointSink,
    fanoutActivityAEndpointSource,
    fanoutActivityBEndpointSink,
    fanoutActivityBEndpointSource,
    fanoutActivityCEndpointSink,
    fanoutActivityCEndpointSource,
    sequentialActivityAEndpointSink,
    sequentialActivityAEndpointSource,
    sequentialActivityBEndpointSink,
    sequentialActivityBEndpointSource,
    temporalActivityScheduleSource,
    activityPause,
    observeActivityResult,
    observeFanoutActivityB,
    observeFanoutActivityC,
    observeWorkflowResult,
    processActivityJob,
    processFanoutActivityA,
    processFanoutActivityB,
    processFanoutActivityC,
    processScheduledActivity,
    processScheduledWorkflow,
    processSequentialActivityA,
    processSequentialActivityB,
    processWorkflowJob,
    scheduledActivityPause,
    scheduledWorkflowPause,
    workflowPause,
    localScheduleSource,
    fanoutWorkflowJobEndpointSink,
    fanoutWorkflowJobEndpointSource,
    temporalWorkflowScheduleSource,
    workflowJobEndpointSink,
    workflowJobEndpointSource,
  };
}

export function initStreams(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
): ServiceStreams {
  const streams = {} as ServiceStreams;
  initAutomationPipelineStreams(config, environment, functions, streams);
  postInitAutomationPipelineStreams(streams);
  return streams;
}

export type ServiceStreams =
  AutomationPipelineStreams;
