// Code generated by servicegen. DO NOT EDIT.

import {
  JsonSerde, MessageContext, SerdeRegistry, SerdeType,
  type RuntimeEnvironment,
  boolSerdeType, bytesSerdeType, errorSerdeType,
  float32SerdeType, float64SerdeType,
  int8SerdeType, int16SerdeType, int32SerdeType, int64SerdeType, intSerdeType,
  makeStreamSerde, runeSerdeType,
  stringSerdeType,
  uint8SerdeType, uint16SerdeType, uint32SerdeType, uint64SerdeType, uintSerdeType,
} from "@gorundebug/tsservicelib/runtime/graph";
import {
  makeCaseStream, makeDelayStream, makeFilterStream, makeFlatMapIterableStream,
  makeFlatMapStream, makeInputStream, makeJoinStream, makeKeyByStream,
  makeLinkStream, makeMapStream, makeMergeStream, makeMultiJoinLink,
  makeMultiJoinStream, makeProcessStream, makeSinkStream,
  makeSinkStreamWithResult, makeSplitStream, makeWhenStream,
} from "@gorundebug/tsservicelib/operators";
import type { AutomationJob } from "@gorundebug/model";
import {
  StreamIds,
  type ConfigSnapshot,
} from "../config/config-snapshot.generated.js";
import {
  ActivityJobEndpointSink, makeActivityJobEndpointSink,
  ActivityJobEndpointSource, makeActivityJobEndpointSource,
  FanoutActivityAEndpointSink, makeFanoutActivityAEndpointSink,
  FanoutActivityAEndpointSource, makeFanoutActivityAEndpointSource,
  FanoutActivityBEndpointSink, makeFanoutActivityBEndpointSink,
  FanoutActivityBEndpointSource, makeFanoutActivityBEndpointSource,
  FanoutActivityCEndpointSink, makeFanoutActivityCEndpointSink,
  FanoutActivityCEndpointSource, makeFanoutActivityCEndpointSource,
  SequentialActivityAEndpointSink, makeSequentialActivityAEndpointSink,
  SequentialActivityAEndpointSource, makeSequentialActivityAEndpointSource,
  SequentialActivityBEndpointSink, makeSequentialActivityBEndpointSink,
  SequentialActivityBEndpointSource, makeSequentialActivityBEndpointSource,
  TemporalActivityScheduleSource, makeTemporalActivityScheduleSource,
  ActivityPause, makeActivityPause,
  ObserveActivityResult, makeObserveActivityResult,
  ObserveFanoutActivityB, makeObserveFanoutActivityB,
  ObserveFanoutActivityC, makeObserveFanoutActivityC,
  ObserveWorkflowResult, makeObserveWorkflowResult,
  ProcessActivityJob, makeProcessActivityJob,
  ProcessFanoutActivityA, makeProcessFanoutActivityA,
  ProcessFanoutActivityB, makeProcessFanoutActivityB,
  ProcessFanoutActivityC, makeProcessFanoutActivityC,
  ProcessScheduledActivity, makeProcessScheduledActivity,
  ProcessScheduledWorkflow, makeProcessScheduledWorkflow,
  ProcessSequentialActivityA, makeProcessSequentialActivityA,
  ProcessSequentialActivityB, makeProcessSequentialActivityB,
  ProcessWorkflowJob, makeProcessWorkflowJob,
  ScheduledActivityPause, makeScheduledActivityPause,
  ScheduledWorkflowPause, makeScheduledWorkflowPause,
  WorkflowPause, makeWorkflowPause,
  LocalScheduleSource, makeLocalScheduleSource,
  FanoutWorkflowJobEndpointSink, makeFanoutWorkflowJobEndpointSink,
  FanoutWorkflowJobEndpointSource, makeFanoutWorkflowJobEndpointSource,
  TemporalWorkflowScheduleSource, makeTemporalWorkflowScheduleSource,
  WorkflowJobEndpointSink, makeWorkflowJobEndpointSink,
  WorkflowJobEndpointSource, makeWorkflowJobEndpointSource,
} from "../functions/index.generated.js";

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const serdeTypes = {
  automationJob: new SerdeType<AutomationJob>("AutomationJob", (value): value is AutomationJob => typeof value === "string"),
} as const;

export function registerGeneratedSerdes(registry: SerdeRegistry): void {
  registry.register(serdeTypes.automationJob, registry.require(stringSerdeType));
  registry.registerStreamValueType(StreamIds.CONSUME_ACTIVITY_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_ACTIVITY_JOB, errorSerdeType);
  registry.registerStreamValueType(StreamIds.ACTIVITY_PAUSE, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.CONSUME_FAN_OUT_WORKFLOW_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_FAN_OUT_WORKFLOW_JOB, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CALL_FAN_OUT_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CALL_FAN_OUT_ACTIVITY_A, errorSerdeType);
  registry.registerStreamValueType(StreamIds.SPLIT_ACTIVITY_A_RESULT, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.CALL_FAN_OUT_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CALL_FAN_OUT_ACTIVITY_B, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CALL_FAN_OUT_ACTIVITY_C, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CALL_FAN_OUT_ACTIVITY_C, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_WORKFLOW_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_WORKFLOW_JOB, errorSerdeType);
  registry.registerStreamValueType(StreamIds.WORKFLOW_PAUSE, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.CALL_SEQUENTIAL_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CALL_SEQUENTIAL_ACTIVITY_A, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CALL_SEQUENTIAL_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CALL_SEQUENTIAL_ACTIVITY_B, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_A, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_B, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_C, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_FAN_OUT_ACTIVITY_C, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_SEQUENTIAL_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_SEQUENTIAL_ACTIVITY_A, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_SEQUENTIAL_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.CONSUME_SEQUENTIAL_ACTIVITY_B, errorSerdeType);
  registry.registerStreamValueType(StreamIds.LOCAL_SCHEDULE, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.LOCAL_SCHEDULE, errorSerdeType);
  registry.registerStreamValueType(StreamIds.SPLIT_ON_DEMAND_JOBS, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.SUBMIT_ACTIVITY_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.SUBMIT_ACTIVITY_JOB, errorSerdeType);
  registry.registerStreamValueType(StreamIds.OBSERVE_ACTIVITY_RESULT, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.OBSERVE_FAN_OUT_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.OBSERVE_FAN_OUT_ACTIVITY_C, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.SUBMIT_WORKFLOW_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.SUBMIT_WORKFLOW_JOB, errorSerdeType);
  registry.registerStreamValueType(StreamIds.OBSERVE_WORKFLOW_RESULT, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_ACTIVITY_JOB, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_FAN_OUT_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_FAN_OUT_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_FAN_OUT_ACTIVITY_C, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.TEMPORAL_ACTIVITY_SCHEDULE, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.TEMPORAL_ACTIVITY_SCHEDULE, errorSerdeType);
  registry.registerStreamValueType(StreamIds.SCHEDULED_ACTIVITY_PAUSE, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_SCHEDULED_ACTIVITY, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.TEMPORAL_WORKFLOW_SCHEDULE, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.TEMPORAL_WORKFLOW_SCHEDULE, errorSerdeType);
  registry.registerStreamValueType(StreamIds.SCHEDULED_WORKFLOW_PAUSE, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_SCHEDULED_WORKFLOW, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_SEQUENTIAL_ACTIVITY_A, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_SEQUENTIAL_ACTIVITY_B, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.PROCESS_WORKFLOW_JOB, serdeTypes.automationJob);
  registry.registerStreamValueType(StreamIds.SUBMIT_FAN_OUT_WORKFLOW_JOB, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.SUBMIT_FAN_OUT_WORKFLOW_JOB, errorSerdeType);
}

export interface ServiceMakers {
  activityJobEndpointSink: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => ActivityJobEndpointSink | Promise<ActivityJobEndpointSink>;
  activityJobEndpointSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => ActivityJobEndpointSource | Promise<ActivityJobEndpointSource>;
  fanoutActivityAEndpointSink: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => FanoutActivityAEndpointSink | Promise<FanoutActivityAEndpointSink>;
  fanoutActivityAEndpointSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => FanoutActivityAEndpointSource | Promise<FanoutActivityAEndpointSource>;
  fanoutActivityBEndpointSink: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => FanoutActivityBEndpointSink | Promise<FanoutActivityBEndpointSink>;
  fanoutActivityBEndpointSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => FanoutActivityBEndpointSource | Promise<FanoutActivityBEndpointSource>;
  fanoutActivityCEndpointSink: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => FanoutActivityCEndpointSink | Promise<FanoutActivityCEndpointSink>;
  fanoutActivityCEndpointSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => FanoutActivityCEndpointSource | Promise<FanoutActivityCEndpointSource>;
  sequentialActivityAEndpointSink: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => SequentialActivityAEndpointSink | Promise<SequentialActivityAEndpointSink>;
  sequentialActivityAEndpointSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => SequentialActivityAEndpointSource | Promise<SequentialActivityAEndpointSource>;
  sequentialActivityBEndpointSink: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => SequentialActivityBEndpointSink | Promise<SequentialActivityBEndpointSink>;
  sequentialActivityBEndpointSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => SequentialActivityBEndpointSource | Promise<SequentialActivityBEndpointSource>;
  temporalActivityScheduleSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => TemporalActivityScheduleSource | Promise<TemporalActivityScheduleSource>;
  activityPause: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").DelayStreamConfig,
  ) => ActivityPause | Promise<ActivityPause>;
  observeActivityResult: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ObserveActivityResult | Promise<ObserveActivityResult>;
  observeFanoutActivityB: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ObserveFanoutActivityB | Promise<ObserveFanoutActivityB>;
  observeFanoutActivityC: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ObserveFanoutActivityC | Promise<ObserveFanoutActivityC>;
  observeWorkflowResult: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ObserveWorkflowResult | Promise<ObserveWorkflowResult>;
  processActivityJob: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ProcessActivityJob | Promise<ProcessActivityJob>;
  processFanoutActivityA: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ProcessFanoutActivityA | Promise<ProcessFanoutActivityA>;
  processFanoutActivityB: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ProcessFanoutActivityB | Promise<ProcessFanoutActivityB>;
  processFanoutActivityC: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ProcessFanoutActivityC | Promise<ProcessFanoutActivityC>;
  processScheduledActivity: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ProcessScheduledActivity | Promise<ProcessScheduledActivity>;
  processScheduledWorkflow: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ProcessScheduledWorkflow | Promise<ProcessScheduledWorkflow>;
  processSequentialActivityA: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ProcessSequentialActivityA | Promise<ProcessSequentialActivityA>;
  processSequentialActivityB: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ProcessSequentialActivityB | Promise<ProcessSequentialActivityB>;
  processWorkflowJob: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => ProcessWorkflowJob | Promise<ProcessWorkflowJob>;
  scheduledActivityPause: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").DelayStreamConfig,
  ) => ScheduledActivityPause | Promise<ScheduledActivityPause>;
  scheduledWorkflowPause: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").DelayStreamConfig,
  ) => ScheduledWorkflowPause | Promise<ScheduledWorkflowPause>;
  workflowPause: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").DelayStreamConfig,
  ) => WorkflowPause | Promise<WorkflowPause>;
  localScheduleSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").CronEndpointConfig,
  ) => LocalScheduleSource | Promise<LocalScheduleSource>;
  fanoutWorkflowJobEndpointSink: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => FanoutWorkflowJobEndpointSink | Promise<FanoutWorkflowJobEndpointSink>;
  fanoutWorkflowJobEndpointSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => FanoutWorkflowJobEndpointSource | Promise<FanoutWorkflowJobEndpointSource>;
  temporalWorkflowScheduleSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => TemporalWorkflowScheduleSource | Promise<TemporalWorkflowScheduleSource>;
  workflowJobEndpointSink: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => WorkflowJobEndpointSink | Promise<WorkflowJobEndpointSink>;
  workflowJobEndpointSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").TemporalEndpointConfig,
  ) => WorkflowJobEndpointSource | Promise<WorkflowJobEndpointSource>;
}

export function defaultMakers(): ServiceMakers {
  return {
    activityJobEndpointSink: makeActivityJobEndpointSink,
    activityJobEndpointSource: makeActivityJobEndpointSource,
    fanoutActivityAEndpointSink: makeFanoutActivityAEndpointSink,
    fanoutActivityAEndpointSource: makeFanoutActivityAEndpointSource,
    fanoutActivityBEndpointSink: makeFanoutActivityBEndpointSink,
    fanoutActivityBEndpointSource: makeFanoutActivityBEndpointSource,
    fanoutActivityCEndpointSink: makeFanoutActivityCEndpointSink,
    fanoutActivityCEndpointSource: makeFanoutActivityCEndpointSource,
    sequentialActivityAEndpointSink: makeSequentialActivityAEndpointSink,
    sequentialActivityAEndpointSource: makeSequentialActivityAEndpointSource,
    sequentialActivityBEndpointSink: makeSequentialActivityBEndpointSink,
    sequentialActivityBEndpointSource: makeSequentialActivityBEndpointSource,
    temporalActivityScheduleSource: makeTemporalActivityScheduleSource,
    activityPause: makeActivityPause,
    observeActivityResult: makeObserveActivityResult,
    observeFanoutActivityB: makeObserveFanoutActivityB,
    observeFanoutActivityC: makeObserveFanoutActivityC,
    observeWorkflowResult: makeObserveWorkflowResult,
    processActivityJob: makeProcessActivityJob,
    processFanoutActivityA: makeProcessFanoutActivityA,
    processFanoutActivityB: makeProcessFanoutActivityB,
    processFanoutActivityC: makeProcessFanoutActivityC,
    processScheduledActivity: makeProcessScheduledActivity,
    processScheduledWorkflow: makeProcessScheduledWorkflow,
    processSequentialActivityA: makeProcessSequentialActivityA,
    processSequentialActivityB: makeProcessSequentialActivityB,
    processWorkflowJob: makeProcessWorkflowJob,
    scheduledActivityPause: makeScheduledActivityPause,
    scheduledWorkflowPause: makeScheduledWorkflowPause,
    workflowPause: makeWorkflowPause,
    localScheduleSource: makeLocalScheduleSource,
    fanoutWorkflowJobEndpointSink: makeFanoutWorkflowJobEndpointSink,
    fanoutWorkflowJobEndpointSource: makeFanoutWorkflowJobEndpointSource,
    temporalWorkflowScheduleSource: makeTemporalWorkflowScheduleSource,
    workflowJobEndpointSink: makeWorkflowJobEndpointSink,
    workflowJobEndpointSource: makeWorkflowJobEndpointSource,
  };
}

function synchronousMakerResult<T>(value: T | Promise<T>, name: string): T {
  if (value instanceof Promise) {
    throw new Error(`Temporal Workflow maker ${name} must be synchronous`);
  }
  return value;
}

export interface ServiceFunctions {
  activityJobEndpointSink: ActivityJobEndpointSink;
  activityJobEndpointSource: ActivityJobEndpointSource;
  fanoutActivityAEndpointSink: FanoutActivityAEndpointSink;
  fanoutActivityAEndpointSource: FanoutActivityAEndpointSource;
  fanoutActivityBEndpointSink: FanoutActivityBEndpointSink;
  fanoutActivityBEndpointSource: FanoutActivityBEndpointSource;
  fanoutActivityCEndpointSink: FanoutActivityCEndpointSink;
  fanoutActivityCEndpointSource: FanoutActivityCEndpointSource;
  sequentialActivityAEndpointSink: SequentialActivityAEndpointSink;
  sequentialActivityAEndpointSource: SequentialActivityAEndpointSource;
  sequentialActivityBEndpointSink: SequentialActivityBEndpointSink;
  sequentialActivityBEndpointSource: SequentialActivityBEndpointSource;
  temporalActivityScheduleSource: TemporalActivityScheduleSource;
  activityPause: ActivityPause;
  observeActivityResult: ObserveActivityResult;
  observeFanoutActivityB: ObserveFanoutActivityB;
  observeFanoutActivityC: ObserveFanoutActivityC;
  observeWorkflowResult: ObserveWorkflowResult;
  processActivityJob: ProcessActivityJob;
  processFanoutActivityA: ProcessFanoutActivityA;
  processFanoutActivityB: ProcessFanoutActivityB;
  processFanoutActivityC: ProcessFanoutActivityC;
  processScheduledActivity: ProcessScheduledActivity;
  processScheduledWorkflow: ProcessScheduledWorkflow;
  processSequentialActivityA: ProcessSequentialActivityA;
  processSequentialActivityB: ProcessSequentialActivityB;
  processWorkflowJob: ProcessWorkflowJob;
  scheduledActivityPause: ScheduledActivityPause;
  scheduledWorkflowPause: ScheduledWorkflowPause;
  workflowPause: WorkflowPause;
  localScheduleSource: LocalScheduleSource;
  fanoutWorkflowJobEndpointSink: FanoutWorkflowJobEndpointSink;
  fanoutWorkflowJobEndpointSource: FanoutWorkflowJobEndpointSource;
  temporalWorkflowScheduleSource: TemporalWorkflowScheduleSource;
  workflowJobEndpointSink: WorkflowJobEndpointSink;
  workflowJobEndpointSource: WorkflowJobEndpointSource;
}

export function initFunctions(
  context: MessageContext,
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  makers: ServiceMakers,
) {
  return {
    activityJobEndpointSink: synchronousMakerResult(
      makers.activityJobEndpointSink(context, environment, config.named.endpoints.activityJob),
      "activityJobEndpointSink",
    ),
    activityJobEndpointSource: synchronousMakerResult(
      makers.activityJobEndpointSource(context, environment, config.named.endpoints.activityJob),
      "activityJobEndpointSource",
    ),
    fanoutActivityAEndpointSink: synchronousMakerResult(
      makers.fanoutActivityAEndpointSink(context, environment, config.named.endpoints.fanOutActivityA),
      "fanoutActivityAEndpointSink",
    ),
    fanoutActivityAEndpointSource: synchronousMakerResult(
      makers.fanoutActivityAEndpointSource(context, environment, config.named.endpoints.fanOutActivityA),
      "fanoutActivityAEndpointSource",
    ),
    fanoutActivityBEndpointSink: synchronousMakerResult(
      makers.fanoutActivityBEndpointSink(context, environment, config.named.endpoints.fanOutActivityB),
      "fanoutActivityBEndpointSink",
    ),
    fanoutActivityBEndpointSource: synchronousMakerResult(
      makers.fanoutActivityBEndpointSource(context, environment, config.named.endpoints.fanOutActivityB),
      "fanoutActivityBEndpointSource",
    ),
    fanoutActivityCEndpointSink: synchronousMakerResult(
      makers.fanoutActivityCEndpointSink(context, environment, config.named.endpoints.fanOutActivityC),
      "fanoutActivityCEndpointSink",
    ),
    fanoutActivityCEndpointSource: synchronousMakerResult(
      makers.fanoutActivityCEndpointSource(context, environment, config.named.endpoints.fanOutActivityC),
      "fanoutActivityCEndpointSource",
    ),
    sequentialActivityAEndpointSink: synchronousMakerResult(
      makers.sequentialActivityAEndpointSink(context, environment, config.named.endpoints.sequentialActivityA),
      "sequentialActivityAEndpointSink",
    ),
    sequentialActivityAEndpointSource: synchronousMakerResult(
      makers.sequentialActivityAEndpointSource(context, environment, config.named.endpoints.sequentialActivityA),
      "sequentialActivityAEndpointSource",
    ),
    sequentialActivityBEndpointSink: synchronousMakerResult(
      makers.sequentialActivityBEndpointSink(context, environment, config.named.endpoints.sequentialActivityB),
      "sequentialActivityBEndpointSink",
    ),
    sequentialActivityBEndpointSource: synchronousMakerResult(
      makers.sequentialActivityBEndpointSource(context, environment, config.named.endpoints.sequentialActivityB),
      "sequentialActivityBEndpointSource",
    ),
    temporalActivityScheduleSource: synchronousMakerResult(
      makers.temporalActivityScheduleSource(context, environment, config.named.endpoints.temporalActivitySchedule),
      "temporalActivityScheduleSource",
    ),
    activityPause: synchronousMakerResult(
      makers.activityPause(context, environment, config.named.streams.activityPause),
      "activityPause",
    ),
    observeActivityResult: synchronousMakerResult(
      makers.observeActivityResult(context, environment, config.named.streams.observeActivityResult),
      "observeActivityResult",
    ),
    observeFanoutActivityB: synchronousMakerResult(
      makers.observeFanoutActivityB(context, environment, config.named.streams.observeFanOutActivityB),
      "observeFanoutActivityB",
    ),
    observeFanoutActivityC: synchronousMakerResult(
      makers.observeFanoutActivityC(context, environment, config.named.streams.observeFanOutActivityC),
      "observeFanoutActivityC",
    ),
    observeWorkflowResult: synchronousMakerResult(
      makers.observeWorkflowResult(context, environment, config.named.streams.observeWorkflowResult),
      "observeWorkflowResult",
    ),
    processActivityJob: synchronousMakerResult(
      makers.processActivityJob(context, environment, config.named.streams.processActivityJob),
      "processActivityJob",
    ),
    processFanoutActivityA: synchronousMakerResult(
      makers.processFanoutActivityA(context, environment, config.named.streams.processFanOutActivityA),
      "processFanoutActivityA",
    ),
    processFanoutActivityB: synchronousMakerResult(
      makers.processFanoutActivityB(context, environment, config.named.streams.processFanOutActivityB),
      "processFanoutActivityB",
    ),
    processFanoutActivityC: synchronousMakerResult(
      makers.processFanoutActivityC(context, environment, config.named.streams.processFanOutActivityC),
      "processFanoutActivityC",
    ),
    processScheduledActivity: synchronousMakerResult(
      makers.processScheduledActivity(context, environment, config.named.streams.processScheduledActivity),
      "processScheduledActivity",
    ),
    processScheduledWorkflow: synchronousMakerResult(
      makers.processScheduledWorkflow(context, environment, config.named.streams.processScheduledWorkflow),
      "processScheduledWorkflow",
    ),
    processSequentialActivityA: synchronousMakerResult(
      makers.processSequentialActivityA(context, environment, config.named.streams.processSequentialActivityA),
      "processSequentialActivityA",
    ),
    processSequentialActivityB: synchronousMakerResult(
      makers.processSequentialActivityB(context, environment, config.named.streams.processSequentialActivityB),
      "processSequentialActivityB",
    ),
    processWorkflowJob: synchronousMakerResult(
      makers.processWorkflowJob(context, environment, config.named.streams.processWorkflowJob),
      "processWorkflowJob",
    ),
    scheduledActivityPause: synchronousMakerResult(
      makers.scheduledActivityPause(context, environment, config.named.streams.scheduledActivityPause),
      "scheduledActivityPause",
    ),
    scheduledWorkflowPause: synchronousMakerResult(
      makers.scheduledWorkflowPause(context, environment, config.named.streams.scheduledWorkflowPause),
      "scheduledWorkflowPause",
    ),
    workflowPause: synchronousMakerResult(
      makers.workflowPause(context, environment, config.named.streams.workflowPause),
      "workflowPause",
    ),
    localScheduleSource: synchronousMakerResult(
      makers.localScheduleSource(context, environment, config.named.endpoints.localSchedule),
      "localScheduleSource",
    ),
    fanoutWorkflowJobEndpointSink: synchronousMakerResult(
      makers.fanoutWorkflowJobEndpointSink(context, environment, config.named.endpoints.fanOutWorkflowJob),
      "fanoutWorkflowJobEndpointSink",
    ),
    fanoutWorkflowJobEndpointSource: synchronousMakerResult(
      makers.fanoutWorkflowJobEndpointSource(context, environment, config.named.endpoints.fanOutWorkflowJob),
      "fanoutWorkflowJobEndpointSource",
    ),
    temporalWorkflowScheduleSource: synchronousMakerResult(
      makers.temporalWorkflowScheduleSource(context, environment, config.named.endpoints.temporalWorkflowSchedule),
      "temporalWorkflowScheduleSource",
    ),
    workflowJobEndpointSink: synchronousMakerResult(
      makers.workflowJobEndpointSink(context, environment, config.named.endpoints.workflowJob),
      "workflowJobEndpointSink",
    ),
    workflowJobEndpointSource: synchronousMakerResult(
      makers.workflowJobEndpointSource(context, environment, config.named.endpoints.workflowJob),
      "workflowJobEndpointSource",
    ),
  };
}

export async function initFunctionsParallel(
  context: MessageContext,
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  makers: ServiceMakers,
): Promise<ServiceFunctions> {
  let activityJobEndpointSink: ActivityJobEndpointSink;
  let activityJobEndpointSource: ActivityJobEndpointSource;
  let fanoutActivityAEndpointSink: FanoutActivityAEndpointSink;
  let fanoutActivityAEndpointSource: FanoutActivityAEndpointSource;
  let fanoutActivityBEndpointSink: FanoutActivityBEndpointSink;
  let fanoutActivityBEndpointSource: FanoutActivityBEndpointSource;
  let fanoutActivityCEndpointSink: FanoutActivityCEndpointSink;
  let fanoutActivityCEndpointSource: FanoutActivityCEndpointSource;
  let sequentialActivityAEndpointSink: SequentialActivityAEndpointSink;
  let sequentialActivityAEndpointSource: SequentialActivityAEndpointSource;
  let sequentialActivityBEndpointSink: SequentialActivityBEndpointSink;
  let sequentialActivityBEndpointSource: SequentialActivityBEndpointSource;
  let temporalActivityScheduleSource: TemporalActivityScheduleSource;
  let activityPause: ActivityPause;
  let observeActivityResult: ObserveActivityResult;
  let observeFanoutActivityB: ObserveFanoutActivityB;
  let observeFanoutActivityC: ObserveFanoutActivityC;
  let observeWorkflowResult: ObserveWorkflowResult;
  let processActivityJob: ProcessActivityJob;
  let processFanoutActivityA: ProcessFanoutActivityA;
  let processFanoutActivityB: ProcessFanoutActivityB;
  let processFanoutActivityC: ProcessFanoutActivityC;
  let processScheduledActivity: ProcessScheduledActivity;
  let processScheduledWorkflow: ProcessScheduledWorkflow;
  let processSequentialActivityA: ProcessSequentialActivityA;
  let processSequentialActivityB: ProcessSequentialActivityB;
  let processWorkflowJob: ProcessWorkflowJob;
  let scheduledActivityPause: ScheduledActivityPause;
  let scheduledWorkflowPause: ScheduledWorkflowPause;
  let workflowPause: WorkflowPause;
  let localScheduleSource: LocalScheduleSource;
  let fanoutWorkflowJobEndpointSink: FanoutWorkflowJobEndpointSink;
  let fanoutWorkflowJobEndpointSource: FanoutWorkflowJobEndpointSource;
  let temporalWorkflowScheduleSource: TemporalWorkflowScheduleSource;
  let workflowJobEndpointSink: WorkflowJobEndpointSink;
  let workflowJobEndpointSource: WorkflowJobEndpointSource;
  {
    const group = await Promise.allSettled([
      makers.activityJobEndpointSink(context, environment, config.named.endpoints.activityJob),
      makers.activityJobEndpointSource(context, environment, config.named.endpoints.activityJob),
      makers.fanoutActivityAEndpointSink(context, environment, config.named.endpoints.fanOutActivityA),
      makers.fanoutActivityAEndpointSource(context, environment, config.named.endpoints.fanOutActivityA),
      makers.fanoutActivityBEndpointSink(context, environment, config.named.endpoints.fanOutActivityB),
      makers.fanoutActivityBEndpointSource(context, environment, config.named.endpoints.fanOutActivityB),
      makers.fanoutActivityCEndpointSink(context, environment, config.named.endpoints.fanOutActivityC),
      makers.fanoutActivityCEndpointSource(context, environment, config.named.endpoints.fanOutActivityC),
      makers.sequentialActivityAEndpointSink(context, environment, config.named.endpoints.sequentialActivityA),
      makers.sequentialActivityAEndpointSource(context, environment, config.named.endpoints.sequentialActivityA),
      makers.sequentialActivityBEndpointSink(context, environment, config.named.endpoints.sequentialActivityB),
      makers.sequentialActivityBEndpointSource(context, environment, config.named.endpoints.sequentialActivityB),
      makers.temporalActivityScheduleSource(context, environment, config.named.endpoints.temporalActivitySchedule),
      makers.activityPause(context, environment, config.named.streams.activityPause),
      makers.observeActivityResult(context, environment, config.named.streams.observeActivityResult),
      makers.observeFanoutActivityB(context, environment, config.named.streams.observeFanOutActivityB),
      makers.observeFanoutActivityC(context, environment, config.named.streams.observeFanOutActivityC),
      makers.observeWorkflowResult(context, environment, config.named.streams.observeWorkflowResult),
      makers.processActivityJob(context, environment, config.named.streams.processActivityJob),
      makers.processFanoutActivityA(context, environment, config.named.streams.processFanOutActivityA),
      makers.processFanoutActivityB(context, environment, config.named.streams.processFanOutActivityB),
      makers.processFanoutActivityC(context, environment, config.named.streams.processFanOutActivityC),
      makers.processScheduledActivity(context, environment, config.named.streams.processScheduledActivity),
      makers.processScheduledWorkflow(context, environment, config.named.streams.processScheduledWorkflow),
      makers.processSequentialActivityA(context, environment, config.named.streams.processSequentialActivityA),
      makers.processSequentialActivityB(context, environment, config.named.streams.processSequentialActivityB),
      makers.processWorkflowJob(context, environment, config.named.streams.processWorkflowJob),
      makers.scheduledActivityPause(context, environment, config.named.streams.scheduledActivityPause),
      makers.scheduledWorkflowPause(context, environment, config.named.streams.scheduledWorkflowPause),
      makers.workflowPause(context, environment, config.named.streams.workflowPause),
      makers.localScheduleSource(context, environment, config.named.endpoints.localSchedule),
      makers.fanoutWorkflowJobEndpointSink(context, environment, config.named.endpoints.fanOutWorkflowJob),
      makers.fanoutWorkflowJobEndpointSource(context, environment, config.named.endpoints.fanOutWorkflowJob),
      makers.temporalWorkflowScheduleSource(context, environment, config.named.endpoints.temporalWorkflowSchedule),
      makers.workflowJobEndpointSink(context, environment, config.named.endpoints.workflowJob),
      makers.workflowJobEndpointSource(context, environment, config.named.endpoints.workflowJob),
    ] as const);
    for (const result of group) {
      if (result.status === "rejected") {
        throw result.reason;
      }
    }
    const activityJobEndpointSinkResult0 = group[0];
    if (activityJobEndpointSinkResult0.status !== "fulfilled") {
      throw activityJobEndpointSinkResult0.reason;
    }
    activityJobEndpointSink = activityJobEndpointSinkResult0.value;
    const activityJobEndpointSourceResult0 = group[1];
    if (activityJobEndpointSourceResult0.status !== "fulfilled") {
      throw activityJobEndpointSourceResult0.reason;
    }
    activityJobEndpointSource = activityJobEndpointSourceResult0.value;
    const fanoutActivityAEndpointSinkResult0 = group[2];
    if (fanoutActivityAEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutActivityAEndpointSinkResult0.reason;
    }
    fanoutActivityAEndpointSink = fanoutActivityAEndpointSinkResult0.value;
    const fanoutActivityAEndpointSourceResult0 = group[3];
    if (fanoutActivityAEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutActivityAEndpointSourceResult0.reason;
    }
    fanoutActivityAEndpointSource = fanoutActivityAEndpointSourceResult0.value;
    const fanoutActivityBEndpointSinkResult0 = group[4];
    if (fanoutActivityBEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutActivityBEndpointSinkResult0.reason;
    }
    fanoutActivityBEndpointSink = fanoutActivityBEndpointSinkResult0.value;
    const fanoutActivityBEndpointSourceResult0 = group[5];
    if (fanoutActivityBEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutActivityBEndpointSourceResult0.reason;
    }
    fanoutActivityBEndpointSource = fanoutActivityBEndpointSourceResult0.value;
    const fanoutActivityCEndpointSinkResult0 = group[6];
    if (fanoutActivityCEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutActivityCEndpointSinkResult0.reason;
    }
    fanoutActivityCEndpointSink = fanoutActivityCEndpointSinkResult0.value;
    const fanoutActivityCEndpointSourceResult0 = group[7];
    if (fanoutActivityCEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutActivityCEndpointSourceResult0.reason;
    }
    fanoutActivityCEndpointSource = fanoutActivityCEndpointSourceResult0.value;
    const sequentialActivityAEndpointSinkResult0 = group[8];
    if (sequentialActivityAEndpointSinkResult0.status !== "fulfilled") {
      throw sequentialActivityAEndpointSinkResult0.reason;
    }
    sequentialActivityAEndpointSink = sequentialActivityAEndpointSinkResult0.value;
    const sequentialActivityAEndpointSourceResult0 = group[9];
    if (sequentialActivityAEndpointSourceResult0.status !== "fulfilled") {
      throw sequentialActivityAEndpointSourceResult0.reason;
    }
    sequentialActivityAEndpointSource = sequentialActivityAEndpointSourceResult0.value;
    const sequentialActivityBEndpointSinkResult0 = group[10];
    if (sequentialActivityBEndpointSinkResult0.status !== "fulfilled") {
      throw sequentialActivityBEndpointSinkResult0.reason;
    }
    sequentialActivityBEndpointSink = sequentialActivityBEndpointSinkResult0.value;
    const sequentialActivityBEndpointSourceResult0 = group[11];
    if (sequentialActivityBEndpointSourceResult0.status !== "fulfilled") {
      throw sequentialActivityBEndpointSourceResult0.reason;
    }
    sequentialActivityBEndpointSource = sequentialActivityBEndpointSourceResult0.value;
    const temporalActivityScheduleSourceResult0 = group[12];
    if (temporalActivityScheduleSourceResult0.status !== "fulfilled") {
      throw temporalActivityScheduleSourceResult0.reason;
    }
    temporalActivityScheduleSource = temporalActivityScheduleSourceResult0.value;
    const activityPauseResult0 = group[13];
    if (activityPauseResult0.status !== "fulfilled") {
      throw activityPauseResult0.reason;
    }
    activityPause = activityPauseResult0.value;
    const observeActivityResultResult0 = group[14];
    if (observeActivityResultResult0.status !== "fulfilled") {
      throw observeActivityResultResult0.reason;
    }
    observeActivityResult = observeActivityResultResult0.value;
    const observeFanoutActivityBResult0 = group[15];
    if (observeFanoutActivityBResult0.status !== "fulfilled") {
      throw observeFanoutActivityBResult0.reason;
    }
    observeFanoutActivityB = observeFanoutActivityBResult0.value;
    const observeFanoutActivityCResult0 = group[16];
    if (observeFanoutActivityCResult0.status !== "fulfilled") {
      throw observeFanoutActivityCResult0.reason;
    }
    observeFanoutActivityC = observeFanoutActivityCResult0.value;
    const observeWorkflowResultResult0 = group[17];
    if (observeWorkflowResultResult0.status !== "fulfilled") {
      throw observeWorkflowResultResult0.reason;
    }
    observeWorkflowResult = observeWorkflowResultResult0.value;
    const processActivityJobResult0 = group[18];
    if (processActivityJobResult0.status !== "fulfilled") {
      throw processActivityJobResult0.reason;
    }
    processActivityJob = processActivityJobResult0.value;
    const processFanoutActivityAResult0 = group[19];
    if (processFanoutActivityAResult0.status !== "fulfilled") {
      throw processFanoutActivityAResult0.reason;
    }
    processFanoutActivityA = processFanoutActivityAResult0.value;
    const processFanoutActivityBResult0 = group[20];
    if (processFanoutActivityBResult0.status !== "fulfilled") {
      throw processFanoutActivityBResult0.reason;
    }
    processFanoutActivityB = processFanoutActivityBResult0.value;
    const processFanoutActivityCResult0 = group[21];
    if (processFanoutActivityCResult0.status !== "fulfilled") {
      throw processFanoutActivityCResult0.reason;
    }
    processFanoutActivityC = processFanoutActivityCResult0.value;
    const processScheduledActivityResult0 = group[22];
    if (processScheduledActivityResult0.status !== "fulfilled") {
      throw processScheduledActivityResult0.reason;
    }
    processScheduledActivity = processScheduledActivityResult0.value;
    const processScheduledWorkflowResult0 = group[23];
    if (processScheduledWorkflowResult0.status !== "fulfilled") {
      throw processScheduledWorkflowResult0.reason;
    }
    processScheduledWorkflow = processScheduledWorkflowResult0.value;
    const processSequentialActivityAResult0 = group[24];
    if (processSequentialActivityAResult0.status !== "fulfilled") {
      throw processSequentialActivityAResult0.reason;
    }
    processSequentialActivityA = processSequentialActivityAResult0.value;
    const processSequentialActivityBResult0 = group[25];
    if (processSequentialActivityBResult0.status !== "fulfilled") {
      throw processSequentialActivityBResult0.reason;
    }
    processSequentialActivityB = processSequentialActivityBResult0.value;
    const processWorkflowJobResult0 = group[26];
    if (processWorkflowJobResult0.status !== "fulfilled") {
      throw processWorkflowJobResult0.reason;
    }
    processWorkflowJob = processWorkflowJobResult0.value;
    const scheduledActivityPauseResult0 = group[27];
    if (scheduledActivityPauseResult0.status !== "fulfilled") {
      throw scheduledActivityPauseResult0.reason;
    }
    scheduledActivityPause = scheduledActivityPauseResult0.value;
    const scheduledWorkflowPauseResult0 = group[28];
    if (scheduledWorkflowPauseResult0.status !== "fulfilled") {
      throw scheduledWorkflowPauseResult0.reason;
    }
    scheduledWorkflowPause = scheduledWorkflowPauseResult0.value;
    const workflowPauseResult0 = group[29];
    if (workflowPauseResult0.status !== "fulfilled") {
      throw workflowPauseResult0.reason;
    }
    workflowPause = workflowPauseResult0.value;
    const localScheduleSourceResult0 = group[30];
    if (localScheduleSourceResult0.status !== "fulfilled") {
      throw localScheduleSourceResult0.reason;
    }
    localScheduleSource = localScheduleSourceResult0.value;
    const fanoutWorkflowJobEndpointSinkResult0 = group[31];
    if (fanoutWorkflowJobEndpointSinkResult0.status !== "fulfilled") {
      throw fanoutWorkflowJobEndpointSinkResult0.reason;
    }
    fanoutWorkflowJobEndpointSink = fanoutWorkflowJobEndpointSinkResult0.value;
    const fanoutWorkflowJobEndpointSourceResult0 = group[32];
    if (fanoutWorkflowJobEndpointSourceResult0.status !== "fulfilled") {
      throw fanoutWorkflowJobEndpointSourceResult0.reason;
    }
    fanoutWorkflowJobEndpointSource = fanoutWorkflowJobEndpointSourceResult0.value;
    const temporalWorkflowScheduleSourceResult0 = group[33];
    if (temporalWorkflowScheduleSourceResult0.status !== "fulfilled") {
      throw temporalWorkflowScheduleSourceResult0.reason;
    }
    temporalWorkflowScheduleSource = temporalWorkflowScheduleSourceResult0.value;
    const workflowJobEndpointSinkResult0 = group[34];
    if (workflowJobEndpointSinkResult0.status !== "fulfilled") {
      throw workflowJobEndpointSinkResult0.reason;
    }
    workflowJobEndpointSink = workflowJobEndpointSinkResult0.value;
    const workflowJobEndpointSourceResult0 = group[35];
    if (workflowJobEndpointSourceResult0.status !== "fulfilled") {
      throw workflowJobEndpointSourceResult0.reason;
    }
    workflowJobEndpointSource = workflowJobEndpointSourceResult0.value;
  }
  return {
    activityJobEndpointSink,
    activityJobEndpointSource,
    fanoutActivityAEndpointSink,
    fanoutActivityAEndpointSource,
    fanoutActivityBEndpointSink,
    fanoutActivityBEndpointSource,
    fanoutActivityCEndpointSink,
    fanoutActivityCEndpointSource,
    sequentialActivityAEndpointSink,
    sequentialActivityAEndpointSource,
    sequentialActivityBEndpointSink,
    sequentialActivityBEndpointSource,
    temporalActivityScheduleSource,
    activityPause,
    observeActivityResult,
    observeFanoutActivityB,
    observeFanoutActivityC,
    observeWorkflowResult,
    processActivityJob,
    processFanoutActivityA,
    processFanoutActivityB,
    processFanoutActivityC,
    processScheduledActivity,
    processScheduledWorkflow,
    processSequentialActivityA,
    processSequentialActivityB,
    processWorkflowJob,
    scheduledActivityPause,
    scheduledWorkflowPause,
    workflowPause,
    localScheduleSource,
    fanoutWorkflowJobEndpointSink,
    fanoutWorkflowJobEndpointSource,
    temporalWorkflowScheduleSource,
    workflowJobEndpointSink,
    workflowJobEndpointSource,
  };
}

export function initStreams(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
) {
  const consumeActivityJob = makeInputStream<string, string, Error>(config.named.streams.consumeActivityJob, environment);
  const activityPause = makeDelayStream<string>(config.named.streams.activityPause, consumeActivityJob, functions.activityPause);
  const consumeFanOutWorkflowJob = makeInputStream<string, unknown, Error>(config.named.streams.consumeFanOutWorkflowJob, environment);
  const callFanOutActivityA = makeSinkStreamWithResult<string, string, Error>(config.named.streams.callFanOutActivityA, consumeFanOutWorkflowJob);
  const splitActivityAResult = makeSplitStream<string>(config.named.streams.splitActivityAResult, callFanOutActivityA);
  const callFanOutActivityB = makeSinkStreamWithResult<string, string, Error>(config.named.streams.callFanOutActivityB, splitActivityAResult.addStream());
  const callFanOutActivityC = makeSinkStreamWithResult<string, string, Error>(config.named.streams.callFanOutActivityC, splitActivityAResult.addStream());
  const consumeWorkflowJob = makeInputStream<string, string, Error>(config.named.streams.consumeWorkflowJob, environment);
  const workflowPause = makeDelayStream<string>(config.named.streams.workflowPause, consumeWorkflowJob, functions.workflowPause);
  const callSequentialActivityA = makeSinkStreamWithResult<string, string, Error>(config.named.streams.callSequentialActivityA, workflowPause);
  const callSequentialActivityB = makeSinkStreamWithResult<string, string, Error>(config.named.streams.callSequentialActivityB, callSequentialActivityA);
  const consumeFanOutActivityA = makeInputStream<string, string, Error>(config.named.streams.consumeFanOutActivityA, environment);
  const consumeFanOutActivityB = makeInputStream<string, string, Error>(config.named.streams.consumeFanOutActivityB, environment);
  const consumeFanOutActivityC = makeInputStream<string, string, Error>(config.named.streams.consumeFanOutActivityC, environment);
  const consumeSequentialActivityA = makeInputStream<string, string, Error>(config.named.streams.consumeSequentialActivityA, environment);
  const consumeSequentialActivityB = makeInputStream<string, string, Error>(config.named.streams.consumeSequentialActivityB, environment);
  const localSchedule = makeInputStream<string, unknown, Error>(config.named.streams.localSchedule, environment);
  const splitOnDemandJobs = makeSplitStream<string>(config.named.streams.splitOnDemandJobs, localSchedule);
  const submitActivityJob = makeSinkStreamWithResult<string, string, Error>(config.named.streams.submitActivityJob, splitOnDemandJobs.addStream());
  const observeActivityResult = makeMapStream<string, string>(config.named.streams.observeActivityResult, submitActivityJob, functions.observeActivityResult);
  const observeFanOutActivityB = makeMapStream<string, string>(config.named.streams.observeFanOutActivityB, callFanOutActivityB, functions.observeFanoutActivityB);
  const observeFanOutActivityC = makeMapStream<string, string>(config.named.streams.observeFanOutActivityC, callFanOutActivityC, functions.observeFanoutActivityC);
  const submitWorkflowJob = makeSinkStreamWithResult<string, string, Error>(config.named.streams.submitWorkflowJob, splitOnDemandJobs.addStream());
  const observeWorkflowResult = makeMapStream<string, string>(config.named.streams.observeWorkflowResult, submitWorkflowJob, functions.observeWorkflowResult);
  const processActivityJob = makeMapStream<string, string>(config.named.streams.processActivityJob, activityPause, functions.processActivityJob);
  const processFanOutActivityA = makeMapStream<string, string>(config.named.streams.processFanOutActivityA, consumeFanOutActivityA, functions.processFanoutActivityA);
  const processFanOutActivityB = makeMapStream<string, string>(config.named.streams.processFanOutActivityB, consumeFanOutActivityB, functions.processFanoutActivityB);
  const processFanOutActivityC = makeMapStream<string, string>(config.named.streams.processFanOutActivityC, consumeFanOutActivityC, functions.processFanoutActivityC);
  const temporalActivitySchedule = makeInputStream<string, string, Error>(config.named.streams.temporalActivitySchedule, environment);
  const scheduledActivityPause = makeDelayStream<string>(config.named.streams.scheduledActivityPause, temporalActivitySchedule, functions.scheduledActivityPause);
  const processScheduledActivity = makeMapStream<string, string>(config.named.streams.processScheduledActivity, scheduledActivityPause, functions.processScheduledActivity);
  const temporalWorkflowSchedule = makeInputStream<string, string, Error>(config.named.streams.temporalWorkflowSchedule, environment);
  const scheduledWorkflowPause = makeDelayStream<string>(config.named.streams.scheduledWorkflowPause, temporalWorkflowSchedule, functions.scheduledWorkflowPause);
  const processScheduledWorkflow = makeMapStream<string, string>(config.named.streams.processScheduledWorkflow, scheduledWorkflowPause, functions.processScheduledWorkflow);
  const processSequentialActivityA = makeMapStream<string, string>(config.named.streams.processSequentialActivityA, consumeSequentialActivityA, functions.processSequentialActivityA);
  const processSequentialActivityB = makeMapStream<string, string>(config.named.streams.processSequentialActivityB, consumeSequentialActivityB, functions.processSequentialActivityB);
  const processWorkflowJob = makeMapStream<string, string>(config.named.streams.processWorkflowJob, callSequentialActivityB, functions.processWorkflowJob);
  const submitFanOutWorkflowJob = makeSinkStream<string, Error>(config.named.streams.submitFanOutWorkflowJob, splitOnDemandJobs.addStream());
  consumeActivityJob.setSource(processActivityJob);
  consumeWorkflowJob.setSource(processWorkflowJob);
  consumeFanOutActivityA.setSource(processFanOutActivityA);
  consumeFanOutActivityB.setSource(processFanOutActivityB);
  consumeFanOutActivityC.setSource(processFanOutActivityC);
  consumeSequentialActivityA.setSource(processSequentialActivityA);
  consumeSequentialActivityB.setSource(processSequentialActivityB);
  temporalActivitySchedule.setSource(processScheduledActivity);
  temporalWorkflowSchedule.setSource(processScheduledWorkflow);
  return {
    consumeActivityJob,
    activityPause,
    consumeFanOutWorkflowJob,
    callFanOutActivityA,
    splitActivityAResult,
    callFanOutActivityB,
    callFanOutActivityC,
    consumeWorkflowJob,
    workflowPause,
    callSequentialActivityA,
    callSequentialActivityB,
    consumeFanOutActivityA,
    consumeFanOutActivityB,
    consumeFanOutActivityC,
    consumeSequentialActivityA,
    consumeSequentialActivityB,
    localSchedule,
    splitOnDemandJobs,
    submitActivityJob,
    observeActivityResult,
    observeFanOutActivityB,
    observeFanOutActivityC,
    submitWorkflowJob,
    observeWorkflowResult,
    processActivityJob,
    processFanOutActivityA,
    processFanOutActivityB,
    processFanOutActivityC,
    temporalActivitySchedule,
    scheduledActivityPause,
    processScheduledActivity,
    temporalWorkflowSchedule,
    scheduledWorkflowPause,
    processScheduledWorkflow,
    processSequentialActivityA,
    processSequentialActivityB,
    processWorkflowJob,
    submitFanOutWorkflowJob,
  };
}

export type ServiceStreams = ReturnType<typeof initStreams>;
