// Code generated by servicegen. DO NOT EDIT.

import {
  Context, JsonSerde, MessageContext, RuntimeConfigStore,
  SerdeRegistry, SerdeType, ServiceApp, ServiceEnvironment,
  type ServiceAppOptions, type ServiceConfig,
  boolSerdeType, bytesSerdeType, errorSerdeType,
  errorFromUnknown,
  float32SerdeType, float64SerdeType,
  int8SerdeType, int16SerdeType, int32SerdeType, int64SerdeType, intSerdeType,
  makeDefaultSerdeRegistry, makeStreamSerde, runeSerdeType,
  scheduleTriggerSerdeType,
  stringSerdeType,
  uint8SerdeType, uint16SerdeType, uint32SerdeType, uint64SerdeType, uintSerdeType,
  makeTemporalConnector,
} from "@gorundebug/tsservicelib/runtime";
import type { ScheduleTrigger } from "@gorundebug/tsservicelib/runtime";
import {
  makeCaseStream, makeDelayStream, makeFilterStream, makeFlatMapIterableStream,
  makeFlatMapStream, makeInputStream, makeJoinStream, makeKeyByStream,
  makeLinkStream, makeMapStream, makeMergeStream, makeMultiJoinLink,
  makeMultiJoinStream, makeProcessStream, makeSinkStream,
  makeSinkStreamWithResult, makeSplitStream, makeWhenStream,
} from "@gorundebug/tsservicelib/operators";
import { makeCronEndpointConsumer } from "@gorundebug/tsservicelib/datasource/cron";
import {
  makeTemporalEndpointConsumer,
  makeTemporalScheduleEndpointConsumer,
} from "@gorundebug/tsservicelib/datasource/temporal";
import {
  makeTemporalSinkEndpointConsumer,
  makeTemporalSinkEndpointConsumerWithResult,
} from "@gorundebug/tsservicelib/datasink/temporal";
import type { String } from "../types/index.generated.js";
import { Config } from "../config/config.js";
import { DataConnectorIds, ServiceIds, StreamIds } from "../config/config.generated.js";
import {
  LocalJob, makeLocalJob,
  LocalSchedule, makeLocalSchedule,
  ProcessDurableJob, makeProcessDurableJob,
  TemporalJob, makeTemporalJob,
  TemporalSchedule, makeTemporalSchedule,
} from "../functions/index.generated.js";

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const serdeTypes = {
} as const;

function registerGeneratedSerdes(registry: SerdeRegistry): void {
  registry.registerStreamValueType(StreamIds.CONSUME_DURABLE_JOB, stringSerdeType);
  registry.registerStreamErrorType(StreamIds.CONSUME_DURABLE_JOB, errorSerdeType);
  registry.registerStreamValueType(StreamIds.LOCAL_SCHEDULE, scheduleTriggerSerdeType);
  registry.registerStreamErrorType(StreamIds.LOCAL_SCHEDULE, errorSerdeType);
  registry.registerStreamValueType(StreamIds.MAKE_LOCAL_JOB, stringSerdeType);
  registry.registerStreamValueType(StreamIds.TEMPORAL_SCHEDULE, scheduleTriggerSerdeType);
  registry.registerStreamErrorType(StreamIds.TEMPORAL_SCHEDULE, errorSerdeType);
  registry.registerStreamValueType(StreamIds.MAKE_TEMPORAL_JOB, stringSerdeType);
  registry.registerStreamValueType(StreamIds.MERGE_JOB_SUBMISSIONS, stringSerdeType);
  registry.registerStreamValueType(StreamIds.PROCESS_DURABLE_JOB, stringSerdeType);
  registry.registerStreamValueType(StreamIds.SUBMIT_DURABLE_JOB, stringSerdeType);
  registry.registerStreamErrorType(StreamIds.SUBMIT_DURABLE_JOB, errorSerdeType);
}

export interface ServiceMakers {
  localJob: (
    context: MessageContext,
    environment: ServiceEnvironment,
    config: import("@gorundebug/tsservicelib/runtime").MapStreamConfig,
  ) => LocalJob;
  localSchedule: (
    context: MessageContext,
    environment: ServiceEnvironment,
    config: import("@gorundebug/tsservicelib/runtime").CronEndpointConfig,
  ) => LocalSchedule;
  processDurableJob: (
    context: MessageContext,
    environment: ServiceEnvironment,
    config: import("@gorundebug/tsservicelib/runtime").MapStreamConfig,
  ) => ProcessDurableJob;
  temporalJob: (
    context: MessageContext,
    environment: ServiceEnvironment,
    config: import("@gorundebug/tsservicelib/runtime").MapStreamConfig,
  ) => TemporalJob;
  temporalSchedule: (
    context: MessageContext,
    environment: ServiceEnvironment,
    config: import("@gorundebug/tsservicelib/runtime").TemporalEndpointConfig,
  ) => TemporalSchedule;
}

function defaultMakers(): ServiceMakers {
  return {
    localJob: makeLocalJob,
    localSchedule: makeLocalSchedule,
    processDurableJob: makeProcessDurableJob,
    temporalJob: makeTemporalJob,
    temporalSchedule: makeTemporalSchedule,
  };
}

function initFunctions(
  context: MessageContext,
  config: Config,
  environment: ServiceEnvironment,
  makers: ServiceMakers,
) {
  return {
    localJob: makers.localJob(context, environment, config.named.streams.makeLocalJob),
    localSchedule: makers.localSchedule(context, environment, config.named.endpoints.localSchedule),
    processDurableJob: makers.processDurableJob(context, environment, config.named.streams.processDurableJob),
    temporalJob: makers.temporalJob(context, environment, config.named.streams.makeTemporalJob),
    temporalSchedule: makers.temporalSchedule(context, environment, config.named.endpoints.temporalSchedule),
  };
}

export type ServiceFunctions = ReturnType<typeof initFunctions>;

function initClients() {
  return {
  };
}

export type ServiceClients = ReturnType<typeof initClients>;

function initRuntimeConnectors(environment: ServiceEnvironment): void {
  makeTemporalConnector(DataConnectorIds.TEMPORAL, environment);
}

function initStreams(
  config: Config,
  environment: ServiceEnvironment,
  functions: ServiceFunctions,
) {
  const consumeDurableJob = makeInputStream<string, string, Error>(config.named.streams.consumeDurableJob, environment);
  const localSchedule = makeInputStream<ScheduleTrigger, unknown, Error>(config.named.streams.localSchedule, environment);
  const makeLocalJob = makeMapStream<ScheduleTrigger, string>(config.named.streams.makeLocalJob, localSchedule, functions.localJob);
  const temporalSchedule = makeInputStream<ScheduleTrigger, unknown, Error>(config.named.streams.temporalSchedule, environment);
  const makeTemporalJob = makeMapStream<ScheduleTrigger, string>(config.named.streams.makeTemporalJob, temporalSchedule, functions.temporalJob);
  const mergeJobSubmissions = makeMergeStream<string>(config.named.streams.mergeJobSubmissions, makeLocalJob, makeTemporalJob);
  const processDurableJob = makeMapStream<string, string>(config.named.streams.processDurableJob, consumeDurableJob, functions.processDurableJob);
  const submitDurableJob = makeSinkStream<string, Error>(config.named.streams.submitDurableJob, mergeJobSubmissions);
  consumeDurableJob.setSource(processDurableJob);
  return {
    consumeDurableJob,
    localSchedule,
    makeLocalJob,
    temporalSchedule,
    makeTemporalJob,
    mergeJobSubmissions,
    processDurableJob,
    submitDurableJob,
  };
}

export type ServiceStreams = ReturnType<typeof initStreams>;

function initDataConnectors(
  streams: ServiceStreams,
  functions: ServiceFunctions,
  clients: ServiceClients,
) {
  const consumeDurableJob = makeTemporalEndpointConsumer(streams.consumeDurableJob);
  const localSchedule = makeCronEndpointConsumer(streams.localSchedule, functions.localSchedule);
  const temporalSchedule = makeTemporalScheduleEndpointConsumer(streams.temporalSchedule, functions.temporalSchedule);
  const submitDurableJob = makeTemporalSinkEndpointConsumer(streams.submitDurableJob);
  return {
    dataConnectors: {
      consumeDurableJob,
      localSchedule,
      temporalSchedule,
      submitDurableJob,
    },
    handlers: {
    },
  };
}

export type ServiceDataConnectors = ReturnType<typeof initDataConnectors>["dataConnectors"];
export type ServiceHandlers = ReturnType<typeof initDataConnectors>["handlers"];

export abstract class ServiceGenerated {
  protected readonly makers: ServiceMakers = defaultMakers();
  protected clients!: ServiceClients;
  protected functions!: ServiceFunctions;
  protected streams!: ServiceStreams;
  protected dataConnectors!: ServiceDataConnectors;
  protected handlers!: ServiceHandlers;

  protected customMakersInit(_context: MessageContext): void {}
  protected customFunctionsInit(_context: MessageContext): void {}
  protected createServiceAppOptions(_config: ServiceConfig): ServiceAppOptions { return {}; }
  protected onStart(_context: Context): Promise<void> { return Promise.resolve(); }
  protected onStop(_context: Context): Promise<void> { return Promise.resolve(); }

  public async run(arguments_: readonly string[]): Promise<void> {
    const config = await Config.load(arguments_);
    const configStore = new RuntimeConfigStore(config.runtime);
    const configPaths = Config.configPaths(arguments_);
    const serdeRegistry = makeDefaultSerdeRegistry();
    registerGeneratedSerdes(serdeRegistry);
    const serviceConfig = config.runtime.serviceById(ServiceIds.AUTOMATION_SERVICE);
    if (serviceConfig === undefined) {
      throw new Error("service config Automation Service not found");
    }
    const app = new ServiceApp(configStore, ServiceIds.AUTOMATION_SERVICE, {
      ...this.createServiceAppOptions(serviceConfig),
      serdeRegistry,
      configReload: {
        valuesPath: configPaths.valuesPath,
        load: async () => (await Config.load(arguments_)).runtime,
      },
    });
    const environment = app.environment();
    const messageContext = new MessageContext();
    this.customMakersInit(messageContext);
    this.clients = initClients();
    this.functions = initFunctions(messageContext, config, environment, this.makers);
    this.customFunctionsInit(messageContext);
    initRuntimeConnectors(environment);
    this.streams = initStreams(config, environment, this.functions);
    const bindings = initDataConnectors(this.streams, this.functions, this.clients);
    this.dataConnectors = bindings.dataConnectors;
    this.handlers = bindings.handlers;

    const context = Context.background();
    await this.onStart(context);
    await app.start(context);
    let terminationError: Error | undefined;
    try {
      terminationError = await waitForTermination();
    } finally {
      await this.onStop(context);
      await app.stop(context, environment.serviceConfig().shutdownTimeout);
    }
    if (terminationError !== undefined) throw terminationError;
  }
}

function waitForTermination(): Promise<Error | undefined> {
  return new Promise((resolve) => {
    const finish = (error?: Error): void => {
      process.off("SIGINT", done);
      process.off("SIGTERM", done);
      process.off("uncaughtException", fail);
      process.off("unhandledRejection", fail);
      resolve(error);
    };
    const done = (): void => {
      finish();
    };
    const fail = (reason: unknown): void => {
      finish(errorFromUnknown(reason));
    };
    process.once("SIGINT", done);
    process.once("SIGTERM", done);
    process.once("uncaughtException", fail);
    process.once("unhandledRejection", fail);
  });
}
