// Code generated by servicegen. DO NOT EDIT.

import type { RuntimeEnvironment } from "@gorundebug/tsservicelib/runtime/graph";
import {
  makeCaseStream, makeDelayStream, makeFilterStream, makeFlatMapIterableStream,
  makeFlatMapStream, makeInputStream, makeJoinStream, makeKeyByStream,
  makeLinkStream, makeMapStream, makeMergeStream, makeMultiJoinLink,
  makeMultiJoinStream, makeProcessStream, makeSinkStream,
  makeSinkStreamWithResult, makeSplitStream, makeSubStream, makeWhenStream,
} from "@gorundebug/tsservicelib/operators";
import type { AutomationJob } from "@gorundebug/model";

import type { ConfigSnapshot } from "../config/config-snapshot.generated.js";
import type { ServiceFunctions } from "./functions.generated.js";

export class ServiceStreams {
  public consumeActivityJob!: ReturnType<typeof initConsumeActivityJobStream>;
  public activityPause!: ReturnType<typeof initActivityPauseStream>;
  public consumeFanOutWorkflowJob!: ReturnType<typeof initConsumeFanOutWorkflowJobStream>;
  public callFanOutActivityA!: ReturnType<typeof initCallFanOutActivityAStream>;
  public splitActivityAResult!: ReturnType<typeof initSplitActivityAResultStream>;
  public callFanOutActivityB!: ReturnType<typeof initCallFanOutActivityBStream>;
  public callFanOutActivityC!: ReturnType<typeof initCallFanOutActivityCStream>;
  public consumeWorkflowJob!: ReturnType<typeof initConsumeWorkflowJobStream>;
  public workflowPause!: ReturnType<typeof initWorkflowPauseStream>;
  public callSequentialActivityA!: ReturnType<typeof initCallSequentialActivityAStream>;
  public callSequentialActivityB!: ReturnType<typeof initCallSequentialActivityBStream>;
  public consumeFanOutActivityA!: ReturnType<typeof initConsumeFanOutActivityAStream>;
  public consumeFanOutActivityB!: ReturnType<typeof initConsumeFanOutActivityBStream>;
  public consumeFanOutActivityC!: ReturnType<typeof initConsumeFanOutActivityCStream>;
  public consumeSequentialActivityA!: ReturnType<typeof initConsumeSequentialActivityAStream>;
  public consumeSequentialActivityB!: ReturnType<typeof initConsumeSequentialActivityBStream>;
  public localSchedule!: ReturnType<typeof initLocalScheduleStream>;
  public splitOnDemandJobs!: ReturnType<typeof initSplitOnDemandJobsStream>;
  public submitActivityJob!: ReturnType<typeof initSubmitActivityJobStream>;
  public observeActivityResult!: ReturnType<typeof initObserveActivityResultStream>;
  public observeFanOutActivityB!: ReturnType<typeof initObserveFanOutActivityBStream>;
  public observeFanOutActivityC!: ReturnType<typeof initObserveFanOutActivityCStream>;
  public submitWorkflowJob!: ReturnType<typeof initSubmitWorkflowJobStream>;
  public observeWorkflowResult!: ReturnType<typeof initObserveWorkflowResultStream>;
  public processActivityJob!: ReturnType<typeof initProcessActivityJobStream>;
  public processFanOutActivityA!: ReturnType<typeof initProcessFanOutActivityAStream>;
  public processFanOutActivityB!: ReturnType<typeof initProcessFanOutActivityBStream>;
  public processFanOutActivityC!: ReturnType<typeof initProcessFanOutActivityCStream>;
  public temporalActivitySchedule!: ReturnType<typeof initTemporalActivityScheduleStream>;
  public scheduledActivityPause!: ReturnType<typeof initScheduledActivityPauseStream>;
  public processScheduledActivity!: ReturnType<typeof initProcessScheduledActivityStream>;
  public temporalWorkflowSchedule!: ReturnType<typeof initTemporalWorkflowScheduleStream>;
  public scheduledWorkflowPause!: ReturnType<typeof initScheduledWorkflowPauseStream>;
  public processScheduledWorkflow!: ReturnType<typeof initProcessScheduledWorkflowStream>;
  public processSequentialActivityA!: ReturnType<typeof initProcessSequentialActivityAStream>;
  public processSequentialActivityB!: ReturnType<typeof initProcessSequentialActivityBStream>;
  public processWorkflowJob!: ReturnType<typeof initProcessWorkflowJobStream>;
  public submitFanOutWorkflowJob!: ReturnType<typeof initSubmitFanOutWorkflowJobStream>;

  public initStreams(config: ConfigSnapshot, environment: RuntimeEnvironment, functions: ServiceFunctions): void {
    const initializedConsumeActivityJob = initConsumeActivityJobStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.consumeActivityJob = initializedConsumeActivityJob;
    const initializedActivityPause = initActivityPauseStream(
      config, environment, functions,
      this.consumeActivityJob,
      undefined,
      [],
    );
    this.activityPause = initializedActivityPause;
    const initializedConsumeFanOutWorkflowJob = initConsumeFanOutWorkflowJobStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.consumeFanOutWorkflowJob = initializedConsumeFanOutWorkflowJob;
    const initializedCallFanOutActivityA = initCallFanOutActivityAStream(
      config, environment, functions,
      this.consumeFanOutWorkflowJob,
      undefined,
      [],
    );
    this.callFanOutActivityA = initializedCallFanOutActivityA;
    const initializedSplitActivityAResult = initSplitActivityAResultStream(
      config, environment, functions,
      this.callFanOutActivityA,
      undefined,
      [],
    );
    this.splitActivityAResult = initializedSplitActivityAResult;
    const initializedCallFanOutActivityB = initCallFanOutActivityBStream(
      config, environment, functions,
      this.splitActivityAResult.addStream(),
      undefined,
      [],
    );
    this.callFanOutActivityB = initializedCallFanOutActivityB;
    const initializedCallFanOutActivityC = initCallFanOutActivityCStream(
      config, environment, functions,
      this.splitActivityAResult.addStream(),
      undefined,
      [],
    );
    this.callFanOutActivityC = initializedCallFanOutActivityC;
    const initializedConsumeWorkflowJob = initConsumeWorkflowJobStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.consumeWorkflowJob = initializedConsumeWorkflowJob;
    const initializedWorkflowPause = initWorkflowPauseStream(
      config, environment, functions,
      this.consumeWorkflowJob,
      undefined,
      [],
    );
    this.workflowPause = initializedWorkflowPause;
    const initializedCallSequentialActivityA = initCallSequentialActivityAStream(
      config, environment, functions,
      this.workflowPause,
      undefined,
      [],
    );
    this.callSequentialActivityA = initializedCallSequentialActivityA;
    const initializedCallSequentialActivityB = initCallSequentialActivityBStream(
      config, environment, functions,
      this.callSequentialActivityA,
      undefined,
      [],
    );
    this.callSequentialActivityB = initializedCallSequentialActivityB;
    const initializedConsumeFanOutActivityA = initConsumeFanOutActivityAStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.consumeFanOutActivityA = initializedConsumeFanOutActivityA;
    const initializedConsumeFanOutActivityB = initConsumeFanOutActivityBStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.consumeFanOutActivityB = initializedConsumeFanOutActivityB;
    const initializedConsumeFanOutActivityC = initConsumeFanOutActivityCStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.consumeFanOutActivityC = initializedConsumeFanOutActivityC;
    const initializedConsumeSequentialActivityA = initConsumeSequentialActivityAStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.consumeSequentialActivityA = initializedConsumeSequentialActivityA;
    const initializedConsumeSequentialActivityB = initConsumeSequentialActivityBStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.consumeSequentialActivityB = initializedConsumeSequentialActivityB;
    const initializedLocalSchedule = initLocalScheduleStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.localSchedule = initializedLocalSchedule;
    const initializedSplitOnDemandJobs = initSplitOnDemandJobsStream(
      config, environment, functions,
      this.localSchedule,
      undefined,
      [],
    );
    this.splitOnDemandJobs = initializedSplitOnDemandJobs;
    const initializedSubmitActivityJob = initSubmitActivityJobStream(
      config, environment, functions,
      this.splitOnDemandJobs.addStream(),
      undefined,
      [],
    );
    this.submitActivityJob = initializedSubmitActivityJob;
    const initializedObserveActivityResult = initObserveActivityResultStream(
      config, environment, functions,
      this.submitActivityJob,
      undefined,
      [],
    );
    this.observeActivityResult = initializedObserveActivityResult;
    const initializedObserveFanOutActivityB = initObserveFanOutActivityBStream(
      config, environment, functions,
      this.callFanOutActivityB,
      undefined,
      [],
    );
    this.observeFanOutActivityB = initializedObserveFanOutActivityB;
    const initializedObserveFanOutActivityC = initObserveFanOutActivityCStream(
      config, environment, functions,
      this.callFanOutActivityC,
      undefined,
      [],
    );
    this.observeFanOutActivityC = initializedObserveFanOutActivityC;
    const initializedSubmitWorkflowJob = initSubmitWorkflowJobStream(
      config, environment, functions,
      this.splitOnDemandJobs.addStream(),
      undefined,
      [],
    );
    this.submitWorkflowJob = initializedSubmitWorkflowJob;
    const initializedObserveWorkflowResult = initObserveWorkflowResultStream(
      config, environment, functions,
      this.submitWorkflowJob,
      undefined,
      [],
    );
    this.observeWorkflowResult = initializedObserveWorkflowResult;
    const initializedProcessActivityJob = initProcessActivityJobStream(
      config, environment, functions,
      this.activityPause,
      undefined,
      [],
    );
    this.processActivityJob = initializedProcessActivityJob;
    const initializedProcessFanOutActivityA = initProcessFanOutActivityAStream(
      config, environment, functions,
      this.consumeFanOutActivityA,
      undefined,
      [],
    );
    this.processFanOutActivityA = initializedProcessFanOutActivityA;
    const initializedProcessFanOutActivityB = initProcessFanOutActivityBStream(
      config, environment, functions,
      this.consumeFanOutActivityB,
      undefined,
      [],
    );
    this.processFanOutActivityB = initializedProcessFanOutActivityB;
    const initializedProcessFanOutActivityC = initProcessFanOutActivityCStream(
      config, environment, functions,
      this.consumeFanOutActivityC,
      undefined,
      [],
    );
    this.processFanOutActivityC = initializedProcessFanOutActivityC;
    const initializedTemporalActivitySchedule = initTemporalActivityScheduleStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.temporalActivitySchedule = initializedTemporalActivitySchedule;
    const initializedScheduledActivityPause = initScheduledActivityPauseStream(
      config, environment, functions,
      this.temporalActivitySchedule,
      undefined,
      [],
    );
    this.scheduledActivityPause = initializedScheduledActivityPause;
    const initializedProcessScheduledActivity = initProcessScheduledActivityStream(
      config, environment, functions,
      this.scheduledActivityPause,
      undefined,
      [],
    );
    this.processScheduledActivity = initializedProcessScheduledActivity;
    const initializedTemporalWorkflowSchedule = initTemporalWorkflowScheduleStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.temporalWorkflowSchedule = initializedTemporalWorkflowSchedule;
    const initializedScheduledWorkflowPause = initScheduledWorkflowPauseStream(
      config, environment, functions,
      this.temporalWorkflowSchedule,
      undefined,
      [],
    );
    this.scheduledWorkflowPause = initializedScheduledWorkflowPause;
    const initializedProcessScheduledWorkflow = initProcessScheduledWorkflowStream(
      config, environment, functions,
      this.scheduledWorkflowPause,
      undefined,
      [],
    );
    this.processScheduledWorkflow = initializedProcessScheduledWorkflow;
    const initializedProcessSequentialActivityA = initProcessSequentialActivityAStream(
      config, environment, functions,
      this.consumeSequentialActivityA,
      undefined,
      [],
    );
    this.processSequentialActivityA = initializedProcessSequentialActivityA;
    const initializedProcessSequentialActivityB = initProcessSequentialActivityBStream(
      config, environment, functions,
      this.consumeSequentialActivityB,
      undefined,
      [],
    );
    this.processSequentialActivityB = initializedProcessSequentialActivityB;
    const initializedProcessWorkflowJob = initProcessWorkflowJobStream(
      config, environment, functions,
      this.callSequentialActivityB,
      undefined,
      [],
    );
    this.processWorkflowJob = initializedProcessWorkflowJob;
    const initializedSubmitFanOutWorkflowJob = initSubmitFanOutWorkflowJobStream(
      config, environment, functions,
      this.splitOnDemandJobs.addStream(),
      undefined,
      [],
    );
    this.submitFanOutWorkflowJob = initializedSubmitFanOutWorkflowJob;
  }

  public build(): void {
    this.consumeActivityJob.setSource(this.processActivityJob);
    this.consumeWorkflowJob.setSource(this.processWorkflowJob);
    this.consumeFanOutActivityA.setSource(this.processFanOutActivityA);
    this.consumeFanOutActivityB.setSource(this.processFanOutActivityB);
    this.consumeFanOutActivityC.setSource(this.processFanOutActivityC);
    this.consumeSequentialActivityA.setSource(this.processSequentialActivityA);
    this.consumeSequentialActivityB.setSource(this.processSequentialActivityB);
    this.temporalActivitySchedule.setSource(this.processScheduledActivity);
    this.temporalWorkflowSchedule.setSource(this.processScheduledWorkflow);
  }
}

export function initStreams(config: ConfigSnapshot, environment: RuntimeEnvironment, functions: ServiceFunctions): ServiceStreams {
  const streams = new ServiceStreams();
  streams.initStreams(config, environment, functions);
  streams.build();
  return streams;
}
export function initConsumeActivityJobStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, string, Error>(config.named.streams.consumeActivityJob, environment);
  return stream;
}
export function initActivityPauseStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeDelayStream<string>(config.named.streams.activityPause, source as never, functions.activityPause);
  return stream;
}
export function initConsumeFanOutWorkflowJobStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, unknown, Error>(config.named.streams.consumeFanOutWorkflowJob, environment);
  return stream;
}
export function initCallFanOutActivityAStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStreamWithResult<string, string, Error>(config.named.streams.callFanOutActivityA, source as never);
  return stream;
}
export function initSplitActivityAResultStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSplitStream<string>(config.named.streams.splitActivityAResult, source as never);
  return stream;
}
export function initCallFanOutActivityBStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStreamWithResult<string, string, Error>(config.named.streams.callFanOutActivityB, source as never);
  return stream;
}
export function initCallFanOutActivityCStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStreamWithResult<string, string, Error>(config.named.streams.callFanOutActivityC, source as never);
  return stream;
}
export function initConsumeWorkflowJobStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, string, Error>(config.named.streams.consumeWorkflowJob, environment);
  return stream;
}
export function initWorkflowPauseStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeDelayStream<string>(config.named.streams.workflowPause, source as never, functions.workflowPause);
  return stream;
}
export function initCallSequentialActivityAStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStreamWithResult<string, string, Error>(config.named.streams.callSequentialActivityA, source as never);
  return stream;
}
export function initCallSequentialActivityBStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStreamWithResult<string, string, Error>(config.named.streams.callSequentialActivityB, source as never);
  return stream;
}
export function initConsumeFanOutActivityAStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, string, Error>(config.named.streams.consumeFanOutActivityA, environment);
  return stream;
}
export function initConsumeFanOutActivityBStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, string, Error>(config.named.streams.consumeFanOutActivityB, environment);
  return stream;
}
export function initConsumeFanOutActivityCStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, string, Error>(config.named.streams.consumeFanOutActivityC, environment);
  return stream;
}
export function initConsumeSequentialActivityAStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, string, Error>(config.named.streams.consumeSequentialActivityA, environment);
  return stream;
}
export function initConsumeSequentialActivityBStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, string, Error>(config.named.streams.consumeSequentialActivityB, environment);
  return stream;
}
export function initLocalScheduleStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, unknown, Error>(config.named.streams.localSchedule, environment);
  return stream;
}
export function initSplitOnDemandJobsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSplitStream<string>(config.named.streams.splitOnDemandJobs, source as never);
  return stream;
}
export function initSubmitActivityJobStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStreamWithResult<string, string, Error>(config.named.streams.submitActivityJob, source as never);
  return stream;
}
export function initObserveActivityResultStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.observeActivityResult, source as never, functions.observeActivityResult);
  return stream;
}
export function initObserveFanOutActivityBStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.observeFanOutActivityB, source as never, functions.observeFanoutActivityB);
  return stream;
}
export function initObserveFanOutActivityCStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.observeFanOutActivityC, source as never, functions.observeFanoutActivityC);
  return stream;
}
export function initSubmitWorkflowJobStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStreamWithResult<string, string, Error>(config.named.streams.submitWorkflowJob, source as never);
  return stream;
}
export function initObserveWorkflowResultStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.observeWorkflowResult, source as never, functions.observeWorkflowResult);
  return stream;
}
export function initProcessActivityJobStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.processActivityJob, source as never, functions.processActivityJob);
  return stream;
}
export function initProcessFanOutActivityAStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.processFanOutActivityA, source as never, functions.processFanoutActivityA);
  return stream;
}
export function initProcessFanOutActivityBStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.processFanOutActivityB, source as never, functions.processFanoutActivityB);
  return stream;
}
export function initProcessFanOutActivityCStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.processFanOutActivityC, source as never, functions.processFanoutActivityC);
  return stream;
}
export function initTemporalActivityScheduleStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, string, Error>(config.named.streams.temporalActivitySchedule, environment);
  return stream;
}
export function initScheduledActivityPauseStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeDelayStream<string>(config.named.streams.scheduledActivityPause, source as never, functions.scheduledActivityPause);
  return stream;
}
export function initProcessScheduledActivityStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.processScheduledActivity, source as never, functions.processScheduledActivity);
  return stream;
}
export function initTemporalWorkflowScheduleStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, string, Error>(config.named.streams.temporalWorkflowSchedule, environment);
  return stream;
}
export function initScheduledWorkflowPauseStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeDelayStream<string>(config.named.streams.scheduledWorkflowPause, source as never, functions.scheduledWorkflowPause);
  return stream;
}
export function initProcessScheduledWorkflowStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.processScheduledWorkflow, source as never, functions.processScheduledWorkflow);
  return stream;
}
export function initProcessSequentialActivityAStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.processSequentialActivityA, source as never, functions.processSequentialActivityA);
  return stream;
}
export function initProcessSequentialActivityBStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.processSequentialActivityB, source as never, functions.processSequentialActivityB);
  return stream;
}
export function initProcessWorkflowJobStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<string, string>(config.named.streams.processWorkflowJob, source as never, functions.processWorkflowJob);
  return stream;
}
export function initSubmitFanOutWorkflowJobStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStream<string, Error>(config.named.streams.submitFanOutWorkflowJob, source as never);
  return stream;
}
