# Code generated by servicegen. DO NOT EDIT.
MODULE_DIR := $(abspath .)
TOOLS_DIR ?= $(MODULE_DIR)/tools
PROGRESS := ./scripts/run-with-progress.generated.sh
DEPENDENCY_PNPM_REGISTRY_ARG = $(if $(strip $(NPM_CONFIG_REGISTRY)),--config.registry=$(NPM_CONFIG_REGISTRY),)
DEPENDENCY_DOWNLOAD_ENV := $(or $(wildcard $(abspath ./dependency-download-env.generated.sh)),$(wildcard $(abspath ../dependency-download-env.generated.sh)),/bin/sh)
SHELL := $(DEPENDENCY_DOWNLOAD_ENV)
.SHELLFLAGS := -c
export
DEPENDENCY_DOCKER_TARGETS := docker-build
include dependency-proxy.generated.mk
PNPM ?= CI=true \
	corepack pnpm $(DEPENDENCY_PNPM_REGISTRY_ARG)

.PHONY: install generate build test docker-build clean

install:
	@if [ -f pnpm-lock.yaml ] || [ -f ../pnpm-lock.yaml ]; then \
		$(PROGRESS) "TypeScript dependency install" $(PNPM) install --frozen-lockfile; \
	else \
		$(PROGRESS) "TypeScript dependency install" $(PNPM) install; \
	fi

generate:
	@if [ "$(SKIP_INSTALL)" != "1" ]; then $(MAKE) install; fi
	@set -eu; for script in $$(find . -name 'generate-*.generated.sh' -type f | sort); do \
		$(PROGRESS) "Generate TypeScript artifacts with $$script" \
			env "$$script"; \
	done

build: generate
	@$(PROGRESS) "TypeScript package build" $(PNPM) build

test: build
	@$(PROGRESS) "TypeScript package tests" $(PNPM) test

docker-build: ## Verify this independent contract/model package in Docker
	@$(PROGRESS) "TypeScript package Docker build and export" \
		docker build $(DEPENDENCY_PROXY_DOCKER_ARGS) \
		--build-arg DEPENDENCY_DOCKER_REGISTRY="$${DEPENDENCY_DOCKER_REGISTRY:-docker.io}" \
		--build-arg NPM_CONFIG_REGISTRY="$${NPM_CONFIG_REGISTRY:-https://registry.npmjs.org/}" \
		--build-arg DEPENDENCY_GITHUB_RAW_URL="$${DEPENDENCY_GITHUB_RAW_URL:-https://github.com}" \
		-f Dockerfile.generated -t "model-typescript-package:latest" .

clean:
	@rm -rf dist tsconfig.tsbuildinfo
