# Code generated by servicegen. DO NOT EDIT.
-include .env
export

PROJECT_DIR := $(abspath .)
BIN_DIR := $(PROJECT_DIR)/bin
TOOLS_DIR := $(PROJECT_DIR)/tools
GOPRIVATE := github.com
MODULE_VERSION := v0.2.35
USE_LOCAL_MODULES ?= 1
OS := $(shell uname -s)
ARCH := $(shell uname -m)
DOCKER_COMPOSE_RUNTIME_FILES :=
DOCKER_COMPOSE_DEV_FILES := docker-compose.dev.generated.yml
DEPENDENCY_DOWNLOAD_ENV := $(abspath ./dependency-download-env.generated.sh)
SHELL := $(DEPENDENCY_DOWNLOAD_ENV)
.SHELLFLAGS := -c

LANG_BUILD_TARGETS :=
LANG_TEST_TARGETS :=
LANG_LINT_TARGETS :=
LANG_LINT_FIX_TARGETS :=
LANG_FMT_TARGETS :=
LANG_GEN_TARGETS :=
LANG_CLEAN_TARGETS :=
LANG_TOOL_TARGETS :=
LANG_HOST_PREP_TARGETS :=
LANG_DOCKER_BUILD_TARGETS :=
LANG_DOCKER_DEV_BUILD_TARGETS :=
LANG_DOCKER_VERIFY_TARGETS :=
LANG_INTEGRATION_TARGETS :=
include make.typescript.generated.mk

DEBUG_TARGETS := debug-analyticsservice debug-automationservice debug-inventoryservice debug-orderservice
ANALYTICS_SERVICE_DEBUG_PORT ?= 2345
export ANALYTICS_SERVICE_DEBUG_PORT
AUTOMATION_SERVICE_DEBUG_PORT ?= 2346
export AUTOMATION_SERVICE_DEBUG_PORT
INVENTORY_SERVICE_DEBUG_PORT ?= 2347
export INVENTORY_SERVICE_DEBUG_PORT
ORDER_SERVICE_DEBUG_PORT ?= 2348
export ORDER_SERVICE_DEBUG_PORT

DEPENDENCY_DOCKER_TARGETS := $(LANG_DOCKER_BUILD_TARGETS) $(LANG_DOCKER_DEV_BUILD_TARGETS) \
	$(LANG_DOCKER_VERIFY_TARGETS) $(DEBUG_TARGETS) docker-build docker-build-local docker-build-dev docker-up docker-start docker-up-dev \
	grafana-dashboards kubernetes-up kubernetes-build kubernetes-deploy
DEPENDENCY_HOST_TARGETS := $(LANG_HOST_PREP_TARGETS)
include dependency-proxy.generated.mk

ifneq ($(strip $(DEPENDENCY_PROXY_DIR)),)
export TSSERVICELIB_SOURCE_CONTEXT ?= $(DEPENDENCY_GIT_MIRROR_DOCKER_BASE)/github.com/gorundebug/tsservicelib.git\#v0.2.35
endif

export DOCKER_TARGET := runtime
DOCKER_COMPOSE := docker compose -f docker-compose.yml $(foreach file,$(DOCKER_COMPOSE_RUNTIME_FILES),-f $(file))
DOCKER_COMPOSE_DEV := docker compose -f docker-compose.yml $(foreach file,$(DOCKER_COMPOSE_DEV_FILES),-f $(file))

ACT_VERSION := v0.2.144
ACT := $(TOOLS_DIR)/act
GH_VERSION := v2.67.0
GH := $(TOOLS_DIR)/gh
GLAB_VERSION := v1.50.0
GLAB := $(TOOLS_DIR)/glab

.DEFAULT_GOAL := all

.PHONY: all init git-init build test lint lint-fix fmt gen clean ci tools \
	run integration-test act docker-build docker-build-local docker-build-dev docker-up docker-start docker-up-dev \
	docker-down docker-down-dev docker-restart docker-clean grafana-dashboards merge help \
	kubernetes-up kubernetes-build kubernetes-deploy kubernetes-test \
	kubernetes-status kubernetes-down kubernetes-clean \
	k8s-up k8s-build k8s-deploy k8s-test k8s-status k8s-down k8s-clean \
	dependency-cache-up dependency-cache-status dependency-cache-refresh dependency-cache-env \
	dependency-cache-docker-env dependency-cache-docker-build \
	dependency-cache-down dependency-cache-clean \
	dependency-source-cache-invalidate \
	git-push git-delete debug-analyticsservice debug-automationservice debug-inventoryservice debug-orderservice git-push-project git-delete-project

all: build ## Build all services (default)

init: tools gen fmt ## First-time setup: install tools, generate, and format

git-init: gen git-push ## Generate, publish repositories, and synchronize dependencies

build: $(LANG_BUILD_TARGETS) ## [mixed] Build all services using each language backend

test: $(LANG_TEST_TARGETS) ## [mixed] Run all tests using each language backend

lint: $(LANG_LINT_TARGETS) ## Run all language linters and type checks

lint-fix: $(LANG_LINT_FIX_TARGETS) ## Auto-fix lint and formatting issues

fmt: $(LANG_FMT_TARGETS) ## Format all source code

gen: $(LANG_GEN_TARGETS) ## Generate protobuf, OpenAPI, and transport code

clean: $(LANG_CLEAN_TARGETS) ## Remove build artifacts

tools: common-tools $(LANG_TOOL_TARGETS) ## Download or verify all required tools

ci: tools build test lint ## Run the full CI pipeline

integration-test: $(LANG_INTEGRATION_TARGETS) ## Run all integration tests

run: docker-up ## Run all services through Docker Compose

docker-build: $(LANG_DOCKER_BUILD_TARGETS) ## [Docker] Build all copied-source runtime images

docker-build-local: docker-build ## Build Docker images for local development

docker-build-dev: $(LANG_DOCKER_DEV_BUILD_TARGETS) ## Build source-mounted development images

grafana-dashboards: ## Generate Grafana dashboards for all services
	@cd analyticsservice/grafana && bash generate.generated.sh
	@cd automationservice/grafana && bash generate.generated.sh
	@cd inventoryservice/grafana && bash generate.generated.sh
	@cd orderservice/grafana && bash generate.generated.sh

docker-up: docker-build grafana-dashboards ## Start all services through Docker Compose
	@$(DOCKER_COMPOSE) up -d

docker-start: ## Start already-built runtime images without rebuilding
	@$(DOCKER_COMPOSE) up -d --no-build

docker-up-dev: docker-build-dev grafana-dashboards ## Start source-mounted development services
	@$(DOCKER_COMPOSE_DEV) up -d --no-build

debug-analyticsservice: ## Debug Analytics Service; set ANALYTICS_SERVICE_DEBUG_PORT (default 2345)
	@ANALYTICS_SERVICE_DEBUG=1 \
		DOCKER_TARGET=development $(DOCKER_COMPOSE_DEV) \
		up -d --no-deps --build --force-recreate analyticsservice

debug-automationservice: ## Debug Automation Service; set AUTOMATION_SERVICE_DEBUG_PORT (default 2346)
	@AUTOMATION_SERVICE_DEBUG=1 \
		DOCKER_TARGET=development $(DOCKER_COMPOSE_DEV) \
		up -d --no-deps --build --force-recreate automationservice

debug-inventoryservice: ## Debug Inventory Service; set INVENTORY_SERVICE_DEBUG_PORT (default 2347)
	@INVENTORY_SERVICE_DEBUG=1 \
		DOCKER_TARGET=development $(DOCKER_COMPOSE_DEV) \
		up -d --no-deps --build --force-recreate inventoryservice

debug-orderservice: ## Debug Order Service; set ORDER_SERVICE_DEBUG_PORT (default 2348)
	@ORDER_SERVICE_DEBUG=1 \
		DOCKER_TARGET=development $(DOCKER_COMPOSE_DEV) \
		up -d --no-deps --build --force-recreate orderservice



docker-down: ## Stop all services
	@$(DOCKER_COMPOSE) down

docker-down-dev: ## Stop source-mounted development services
	@$(DOCKER_COMPOSE_DEV) down

docker-restart: docker-down docker-up ## Restart all services

docker-clean: docker-down ## Stop services and remove persistent volumes
	@$(DOCKER_COMPOSE) down --volumes --remove-orphans

dependency-cache-up: ## Start and configure the shared local package proxy
	@bash scripts/dependency-cache.generated.sh up

dependency-cache-status: ## Show the shared local package proxy status
	@bash scripts/dependency-cache.generated.sh status

dependency-cache-refresh: ## Refresh every cached Git mirror from its upstream
	@bash scripts/dependency-cache.generated.sh refresh

dependency-cache-env: ## Print package-manager environment for the local proxy
	@bash scripts/dependency-cache.generated.sh env

dependency-cache-docker-env: ## Print proxy environment reachable from Docker Desktop builds
	@DEPENDENCY_PROXY_CLIENT_HOST=$${DEPENDENCY_PROXY_DOCKER_HOST:-host.docker.internal} \
		bash scripts/dependency-cache.generated.sh env

dependency-cache-docker-build: dependency-cache-up ## Build all images through the shared proxy
	@eval "$$(DEPENDENCY_PROXY_CLIENT_HOST=$${DEPENDENCY_PROXY_DOCKER_HOST:-host.docker.internal} \
		bash scripts/dependency-cache.generated.sh env)"; \
	$(MAKE) docker-build

dependency-cache-down: ## Stop the proxy while preserving downloaded artifacts
	@bash scripts/dependency-cache.generated.sh down

dependency-cache-clean: ## Stop the proxy and delete all downloaded artifacts
	@bash scripts/dependency-cache.generated.sh clean

dependency-source-cache-invalidate: ## Recreate C++ sources/CMake state, preserving ccache and Nexus
	@bash scripts/dependency-source-cache.generated.sh invalidate

kubernetes-up: ## Build, deploy and verify all services in local Kubernetes
	@bash scripts/kubernetes.generated.sh up

kubernetes-build: ## Build and publish runtime images to the local registry
	@bash scripts/kubernetes.generated.sh build

kubernetes-deploy: ## Install project infrastructure and service Helm releases
	@bash scripts/kubernetes.generated.sh deploy

kubernetes-test: ## Verify Kubernetes rollouts and service metrics
	@bash scripts/kubernetes.generated.sh test

kubernetes-status: ## Show local Kubernetes resources and Helm releases
	@bash scripts/kubernetes.generated.sh status

kubernetes-down: ## Stop local Kubernetes while preserving its volumes
	@bash scripts/kubernetes.generated.sh down

kubernetes-clean: ## Remove local Kubernetes and all project cluster volumes
	@bash scripts/kubernetes.generated.sh clean

k8s-up: kubernetes-up
k8s-build: kubernetes-build
k8s-deploy: kubernetes-deploy
k8s-test: kubernetes-test
k8s-status: kubernetes-status
k8s-down: kubernetes-down
k8s-clean: kubernetes-clean

act: $(ACT) ## Run GitHub Actions locally through act
	@$(ACT) push -W .github/workflows --env "GITHUB_TOKEN=$$($(GH) auth token)"

merge: ## Merge a generated archive (usage: make merge ARCHIVE=/path/archive.zip)
	@bash scripts/merge.generated.sh "$(ARCHIVE)"

merge-check: ## Preview a merge without changing files
	@bash scripts/merge.generated.sh --dry-run "$(ARCHIVE)"

merge-validate: ## Re-run generated/business interface checks
	@python3 scripts/merge_validate.generated.py --project .

$(ACT):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Downloading act $(ACT_VERSION)..."
	@curl --fail --location --silent --show-error --connect-timeout 15 --speed-limit 1024 --speed-time 60 --retry 8 --retry-delay 2 --retry-max-time 600 --retry-all-errors "$(DEPENDENCY_GITHUB_RAW_URL)/nektos/act/releases/download/$(ACT_VERSION)/act_$(OS)_$(ARCH).tar.gz" | tar -xz -C "$(TOOLS_DIR)" act

$(GH):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Downloading gh $(GH_VERSION)..."
	@_os=$$(uname -s | sed 's/Darwin/macOS/;s/Linux/linux/'); \
	_arch=$$(uname -m | sed 's/x86_64/amd64/'); \
	_ver=$$(echo "$(GH_VERSION)" | sed 's/v//'); \
	if [ "$$(uname -s)" = "Darwin" ]; then \
	  curl --fail --location --silent --show-error --connect-timeout 15 --speed-limit 1024 --speed-time 60 --retry 8 --retry-delay 2 --retry-max-time 600 --retry-all-errors "$(DEPENDENCY_GITHUB_RAW_URL)/cli/cli/releases/download/$(GH_VERSION)/gh_$${_ver}_$${_os}_$${_arch}.zip" -o /tmp/gh.zip; \
	  rm -rf /tmp/gh_extract; \
	  unzip -q /tmp/gh.zip "gh_$${_ver}_$${_os}_$${_arch}/bin/gh" -d /tmp/gh_extract; \
	  mv /tmp/gh_extract/gh_$${_ver}_$${_os}_$${_arch}/bin/gh "$(GH)"; \
	  rm -rf /tmp/gh.zip /tmp/gh_extract; \
	else \
	  curl --fail --location --silent --show-error --connect-timeout 15 --speed-limit 1024 --speed-time 60 --retry 8 --retry-delay 2 --retry-max-time 600 --retry-all-errors "$(DEPENDENCY_GITHUB_RAW_URL)/cli/cli/releases/download/$(GH_VERSION)/gh_$${_ver}_$${_os}_$${_arch}.tar.gz" | tar -xz -C /tmp; \
	  mv /tmp/gh_$${_ver}_$${_os}_$${_arch}/bin/gh "$(GH)"; \
	  rm -rf /tmp/gh_$${_ver}_$${_os}_$${_arch}; \
	fi
	@chmod +x "$(GH)"

$(GLAB):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Downloading glab $(GLAB_VERSION)..."
	@_os=$$(uname -s | tr '[:upper:]' '[:lower:]'); \
	_arch=$$(uname -m | sed 's/amd64/x86_64/'); \
	_ver=$$(echo "$(GLAB_VERSION)" | sed 's/v//'); \
	curl --fail --location --silent --show-error --connect-timeout 15 --speed-limit 1024 --speed-time 60 --retry 8 --retry-delay 2 --retry-max-time 600 --retry-all-errors "$(DEPENDENCY_GITLAB_RAW_URL)/gitlab-org/cli/-/releases/$(GLAB_VERSION)/downloads/glab_$${_ver}_$${_os}_$${_arch}.tar.gz" | \
	  tar -xz -C "$(TOOLS_DIR)" --strip-components=1 bin/glab
	@chmod +x "$(GLAB)"

common-tools: $(ACT) $(GH) $(GLAB)

define git-push-dir
	@set -eu; \
	host="$(3)"; \
	repo="$(4)"; \
	if [ "$$host" = "gitlab.com" ]; then \
	  $(GLAB) repo create $$repo --public 2>/dev/null || true; \
	else \
	  $(GH) repo create $$repo --public 2>/dev/null || true; \
	fi; \
	tmp=$$(mktemp -d); \
	trap 'rm -rf "$$tmp"' EXIT INT TERM; \
	stage="$$tmp/stage"; \
	work="$$tmp/repository"; \
	mkdir -p "$$stage"; \
	if [ "$(5)" = "cpp-service" ]; then \
	  ./scripts/package-cpp-service.generated.sh "./$(1)" "$$stage"; \
	elif [ "$(5)" = "python-service" ]; then \
	  ./scripts/package-python-service.generated.sh "./$(1)" "$$stage"; \
	elif [ "$(5)" = "rust-service" ]; then \
	  ./scripts/package-rust-service.generated.sh "./$(1)" "$$stage"; \
	elif [ "$(5)" = "typescript-service" ]; then \
	  ./scripts/package-typescript-service.generated.sh "./$(1)" "$$stage"; \
	else \
	  cp -r ./$(1)/. "$$stage/"; \
	fi; \
	rm -rf "$$stage/.git"; \
	git clone -q "git@$$host:$$repo.git" "$$work"; \
	git -C "$$work" rm -rq --ignore-unmatch .; \
	cp -r "$$stage/." "$$work/"; \
	git -C "$$work" add -A; \
	if ! git -C "$$work" diff --cached --quiet; then \
	  git -C "$$work" -c user.email="local@dev" -c user.name="local" commit -q -m "release $(2)"; \
	fi; \
	git -C "$$work" tag $(2); \
	git -C "$$work" push --atomic origin HEAD:main refs/tags/$(2)
endef

git-push-project: $(GH) ## Push project root to github.com/gorundebug/tsexample
	$(call git-push-dir,.,$(MODULE_VERSION),github.com,gorundebug/tsexample)

git-delete-project: $(GH) ## Delete project repository github.com/gorundebug/tsexample
	@$(GH) repo delete gorundebug/tsexample --yes 2>/dev/null || true


git-push: gen $(GH) ## Generate and push all modules, services, and project repositories
	@$(GH) auth status >/dev/null 2>&1 || { echo "ERROR: authenticate first with: $(GH) auth login"; exit 1; }

	@$(MAKE) git-push-project

git-delete: $(GH) ## Delete all generated remote repositories
	@$(MAKE) git-delete-project

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-32s %s\n", $$1, $$2}'