# Code generated by servicegen. DO NOT EDIT.
-include .env
export

PROJECT_DIR := $(abspath .)
BIN_DIR := $(PROJECT_DIR)/bin
TOOLS_DIR := $(PROJECT_DIR)/tools
GOPRIVATE := github.com
MODULE_VERSION := v0.2.8
OS := $(shell uname -s)
ARCH := $(shell uname -m)
RUNTIME_IMAGE ?= 0
DOCKER_COMPOSE_RUNTIME_FILES :=
SERVICEGEN_GITHUB_RAW_URL ?= https://github.com
SERVICEGEN_GITLAB_RAW_URL ?= https://gitlab.com

# A shared dependency proxy is opt-in through one host directory. Merely
# setting the variable makes all generated host commands use the long-running
# Nexus instance; Docker/Kubernetes targets switch to its Docker-reachable
# address below.
ifneq ($(strip $(SERVICEGEN_DEPENDENCY_PROXY_DIR)),)
SERVICEGEN_DEPENDENCY_PROXY_HOST ?= localhost
SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST ?= host.docker.internal
SERVICEGEN_DEPENDENCY_PROXY_PORT ?= $(SERVICEGEN_NEXUS_PORT)
SERVICEGEN_DEPENDENCY_PROXY_PORT := $(if $(SERVICEGEN_DEPENDENCY_PROXY_PORT),$(SERVICEGEN_DEPENDENCY_PROXY_PORT),18081)
SERVICEGEN_DEPENDENCY_PROXY_BASE := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository
SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository
export GOPROXY := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/go-proxy/
export GOSUMDB := off
export NPM_CONFIG_REGISTRY := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/npm-proxy/
export PIP_INDEX_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/pypi-proxy/simple
export PIP_TRUSTED_HOST := $(SERVICEGEN_DEPENDENCY_PROXY_HOST)
export UV_INDEX_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/pypi-proxy/simple
export CARGO_REGISTRIES_CRATES_IO_INDEX := sparse+$(SERVICEGEN_DEPENDENCY_PROXY_BASE)/cargo-proxy/
export SERVICEGEN_MAVEN_CENTRAL_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/maven-central
export SERVICEGEN_GITHUB_RAW_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/github-raw
export SERVICEGEN_GITLAB_RAW_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/gitlab-raw
export SERVICEGEN_APT_UBUNTU_ARCHIVE_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/apt-ubuntu-archive
export SERVICEGEN_APT_UBUNTU_SECURITY_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/apt-ubuntu-security
export SERVICEGEN_APT_UBUNTU_PORTS_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/apt-ubuntu-ports
export SERVICEGEN_APT_DEBIAN_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/apt-debian
export SERVICEGEN_APT_DEBIAN_SECURITY_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/apt-debian-security
export TSSERVICELIB_SOURCE_CONTEXT ?= $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/github-raw/gorundebug/tsservicelib/archive/refs/tags/v0.2.8.tar.gz
export SERVICEGEN_HELM_PROMETHEUS_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/helm-prometheus
export SERVICEGEN_HELM_GRAFANA_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/helm-grafana
export SERVICEGEN_HELM_OPENTELEMETRY_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/helm-opentelemetry
export SERVICEGEN_HELM_JAEGER_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/helm-jaeger
export SERVICEGEN_HELM_REDPANDA_URL := $(SERVICEGEN_DEPENDENCY_PROXY_BASE)/helm-redpanda
endif

LANG_BUILD_TARGETS :=
LANG_TEST_TARGETS :=
LANG_LINT_TARGETS :=
LANG_LINT_FIX_TARGETS :=
LANG_FMT_TARGETS :=
LANG_GEN_TARGETS :=
LANG_CLEAN_TARGETS :=
LANG_TOOL_TARGETS :=
LANG_DOCKER_BUILD_TARGETS :=
LANG_INTEGRATION_TARGETS :=
include make.typescript.generated.mk

ifeq ($(RUNTIME_IMAGE),1)
export SERVICEGEN_DOCKER_TARGET := runtime
DOCKER_COMPOSE := docker compose -f docker-compose.yml $(foreach file,$(DOCKER_COMPOSE_RUNTIME_FILES),-f $(file))
else
DOCKER_COMPOSE := docker compose
endif

ACT_VERSION := v0.2.84
ACT := $(TOOLS_DIR)/act
GH_VERSION := v2.67.0
GH := $(TOOLS_DIR)/gh
GLAB_VERSION := v1.50.0
GLAB := $(TOOLS_DIR)/glab

.DEFAULT_GOAL := all

.PHONY: all init git-init build test lint lint-fix fmt gen clean ci tools \
	run integration-test act docker-build docker-build-local docker-up \
	docker-down docker-restart docker-clean grafana-dashboards merge help \
	kubernetes-up kubernetes-build kubernetes-deploy kubernetes-test \
	kubernetes-status kubernetes-down kubernetes-clean \
	k8s-up k8s-build k8s-deploy k8s-test k8s-status k8s-down k8s-clean \
	dependency-cache-up dependency-cache-status dependency-cache-env \
	dependency-cache-docker-env dependency-cache-docker-build \
	dependency-cache-down dependency-cache-clean \
	git-push git-delete git-push-inventory_service_api git-delete-inventory_service_api git-push-model git-delete-model git-push-order_service_api git-delete-order_service_api git-push-analyticsservice git-delete-analyticsservice git-push-inventoryservice git-delete-inventoryservice git-push-orderservice git-delete-orderservice git-push-project git-delete-project

all: build ## Build all services (default)

init: tools gen fmt ## First-time setup: install tools, generate, and format

git-init: gen git-push ## Generate, publish repositories, and synchronize dependencies

build: $(LANG_BUILD_TARGETS) ## Build all services

test: $(LANG_TEST_TARGETS) ## Run all tests

lint: $(LANG_LINT_TARGETS) ## Run all language linters and type checks

lint-fix: $(LANG_LINT_FIX_TARGETS) ## Auto-fix lint and formatting issues

fmt: $(LANG_FMT_TARGETS) ## Format all source code

gen: $(LANG_GEN_TARGETS) ## Generate protobuf, OpenAPI, and transport code

clean: $(LANG_CLEAN_TARGETS) ## Remove build artifacts

tools: common-tools $(LANG_TOOL_TARGETS) ## Download or verify all required tools

ci: tools build test lint ## Run the full CI pipeline

integration-test: $(LANG_INTEGRATION_TARGETS) ## Run all integration tests

run: docker-up ## Run all services through Docker Compose

docker-build: $(LANG_DOCKER_BUILD_TARGETS) ## Build all service Docker images

docker-build-local: docker-build ## Build Docker images for local development

ifneq ($(strip $(SERVICEGEN_DEPENDENCY_PROXY_DIR)),)
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export GOPROXY := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/go-proxy/
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export GOSUMDB := off
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export NPM_CONFIG_REGISTRY := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/npm-proxy/
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export PIP_INDEX_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/pypi-proxy/simple
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export PIP_TRUSTED_HOST := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST)
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export UV_INDEX_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/pypi-proxy/simple
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export CARGO_REGISTRIES_CRATES_IO_INDEX := sparse+$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/cargo-proxy/
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_MAVEN_CENTRAL_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/maven-central
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_GITHUB_RAW_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/github-raw
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_GITLAB_RAW_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/gitlab-raw
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_APT_UBUNTU_ARCHIVE_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/apt-ubuntu-archive
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_APT_UBUNTU_SECURITY_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/apt-ubuntu-security
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_APT_UBUNTU_PORTS_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/apt-ubuntu-ports
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_APT_DEBIAN_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/apt-debian
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_APT_DEBIAN_SECURITY_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/apt-debian-security
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_HELM_PROMETHEUS_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/helm-prometheus
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_HELM_GRAFANA_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/helm-grafana
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_HELM_OPENTELEMETRY_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/helm-opentelemetry
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_HELM_JAEGER_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/helm-jaeger
docker-build docker-build-local docker-up kubernetes-up kubernetes-build kubernetes-deploy: export SERVICEGEN_HELM_REDPANDA_URL := $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_BASE)/helm-redpanda
endif

grafana-dashboards: ## Generate Grafana dashboards for all services
	@cd analyticsservice/grafana && bash generate.generated.sh
	@cd inventoryservice/grafana && bash generate.generated.sh
	@cd orderservice/grafana && bash generate.generated.sh

docker-up: docker-build grafana-dashboards ## Start all services through Docker Compose
	@$(DOCKER_COMPOSE) up -d

docker-down: ## Stop all services
	@$(DOCKER_COMPOSE) down

docker-restart: docker-down docker-up ## Restart all services

docker-clean: docker-down ## Stop services and remove persistent volumes
	@$(DOCKER_COMPOSE) down --volumes --remove-orphans

dependency-cache-up: ## Start and configure the shared local package proxy
	@bash scripts/dependency-cache.generated.sh up

dependency-cache-status: ## Show the shared local package proxy status
	@bash scripts/dependency-cache.generated.sh status

dependency-cache-env: ## Print package-manager environment for the local proxy
	@bash scripts/dependency-cache.generated.sh env

dependency-cache-docker-env: ## Print proxy environment reachable from Docker Desktop builds
	@SERVICEGEN_NEXUS_CLIENT_HOST=$${SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST:-$${SERVICEGEN_NEXUS_DOCKER_HOST:-host.docker.internal}} \
		bash scripts/dependency-cache.generated.sh env

dependency-cache-docker-build: dependency-cache-up ## Build all images through the shared proxy
	@eval "$$(SERVICEGEN_NEXUS_CLIENT_HOST=$${SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST:-$${SERVICEGEN_NEXUS_DOCKER_HOST:-host.docker.internal}} \
		bash scripts/dependency-cache.generated.sh env)"; \
	$(MAKE) docker-build

dependency-cache-down: ## Stop the proxy while preserving downloaded artifacts
	@bash scripts/dependency-cache.generated.sh down

dependency-cache-clean: ## Stop the proxy and delete all downloaded artifacts
	@bash scripts/dependency-cache.generated.sh clean

kubernetes-up: ## Build, deploy and verify all services in local Kubernetes
	@bash scripts/kubernetes.generated.sh up

kubernetes-build: ## Build and publish runtime images to the local registry
	@bash scripts/kubernetes.generated.sh build

kubernetes-deploy: ## Install project infrastructure and service Helm releases
	@bash scripts/kubernetes.generated.sh deploy

kubernetes-test: ## Verify Kubernetes rollouts and service metrics
	@bash scripts/kubernetes.generated.sh test

kubernetes-status: ## Show local Kubernetes resources and Helm releases
	@bash scripts/kubernetes.generated.sh status

kubernetes-down: ## Stop local Kubernetes while preserving its volumes
	@bash scripts/kubernetes.generated.sh down

kubernetes-clean: ## Remove local Kubernetes and all project cluster volumes
	@bash scripts/kubernetes.generated.sh clean

k8s-up: kubernetes-up
k8s-build: kubernetes-build
k8s-deploy: kubernetes-deploy
k8s-test: kubernetes-test
k8s-status: kubernetes-status
k8s-down: kubernetes-down
k8s-clean: kubernetes-clean

act: $(ACT) ## Run GitHub Actions locally through act
	@$(ACT) push -W .github/workflows --env "GITHUB_TOKEN=$$($(GH) auth token)"

merge: ## Merge a generated archive (usage: make merge ARCHIVE=/path/archive.zip)
	@bash scripts/merge.generated.sh "$(ARCHIVE)"

merge-check: ## Preview a merge without changing files
	@bash scripts/merge.generated.sh --dry-run "$(ARCHIVE)"

merge-validate: ## Re-run generated/business interface checks
	@python3 scripts/merge_validate.generated.py --project .

$(ACT):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Downloading act $(ACT_VERSION)..."
	@curl -sSL "$(SERVICEGEN_GITHUB_RAW_URL)/nektos/act/releases/download/$(ACT_VERSION)/act_$(OS)_$(ARCH).tar.gz" | tar -xz -C "$(TOOLS_DIR)" act

$(GH):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Downloading gh $(GH_VERSION)..."
	@_os=$$(uname -s | sed 's/Darwin/macOS/;s/Linux/linux/'); \
	_arch=$$(uname -m | sed 's/x86_64/amd64/'); \
	_ver=$$(echo "$(GH_VERSION)" | sed 's/v//'); \
	if [ "$$(uname -s)" = "Darwin" ]; then \
	  curl -sSL "$(SERVICEGEN_GITHUB_RAW_URL)/cli/cli/releases/download/$(GH_VERSION)/gh_$${_ver}_$${_os}_$${_arch}.zip" -o /tmp/gh.zip; \
	  rm -rf /tmp/gh_extract; \
	  unzip -q /tmp/gh.zip "gh_$${_ver}_$${_os}_$${_arch}/bin/gh" -d /tmp/gh_extract; \
	  mv /tmp/gh_extract/gh_$${_ver}_$${_os}_$${_arch}/bin/gh "$(GH)"; \
	  rm -rf /tmp/gh.zip /tmp/gh_extract; \
	else \
	  curl -sSL "$(SERVICEGEN_GITHUB_RAW_URL)/cli/cli/releases/download/$(GH_VERSION)/gh_$${_ver}_$${_os}_$${_arch}.tar.gz" | tar -xz -C /tmp; \
	  mv /tmp/gh_$${_ver}_$${_os}_$${_arch}/bin/gh "$(GH)"; \
	  rm -rf /tmp/gh_$${_ver}_$${_os}_$${_arch}; \
	fi
	@chmod +x "$(GH)"

$(GLAB):
	@mkdir -p "$(TOOLS_DIR)"
	@echo "Downloading glab $(GLAB_VERSION)..."
	@_os=$$(uname -s | tr '[:upper:]' '[:lower:]'); \
	_arch=$$(uname -m | sed 's/amd64/x86_64/'); \
	_ver=$$(echo "$(GLAB_VERSION)" | sed 's/v//'); \
	curl -sSL "$(SERVICEGEN_GITLAB_RAW_URL)/gitlab-org/cli/-/releases/$(GLAB_VERSION)/downloads/glab_$${_ver}_$${_os}_$${_arch}.tar.gz" | \
	  tar -xz -C "$(TOOLS_DIR)" --strip-components=1 bin/glab
	@chmod +x "$(GLAB)"

common-tools: $(ACT) $(GH) $(GLAB)

define git-push-dir
	@set -eu; \
	host="$(3)"; \
	repo="$(4)"; \
	if [ "$$host" = "gitlab.com" ]; then \
	  $(GLAB) repo create $$repo --private 2>/dev/null || true; \
	else \
	  $(GH) repo create $$repo --private 2>/dev/null || true; \
	fi; \
	tmp=$$(mktemp -d); \
	trap 'rm -rf "$$tmp"' EXIT INT TERM; \
	stage="$$tmp/stage"; \
	work="$$tmp/repository"; \
	mkdir -p "$$stage"; \
	if [ "$(5)" = "cpp-service" ]; then \
	  ./scripts/package-cpp-service.generated.sh "./$(1)" "$$stage"; \
	elif [ "$(5)" = "python-service" ]; then \
	  ./scripts/package-python-service.generated.sh "./$(1)" "$$stage"; \
	elif [ "$(5)" = "rust-service" ]; then \
	  ./scripts/package-rust-service.generated.sh "./$(1)" "$$stage"; \
	elif [ "$(5)" = "typescript-service" ]; then \
	  ./scripts/package-typescript-service.generated.sh "./$(1)" "$$stage"; \
	else \
	  cp -r ./$(1)/. "$$stage/"; \
	fi; \
	rm -rf "$$stage/.git"; \
	git clone -q "git@$$host:$$repo.git" "$$work"; \
	git -C "$$work" rm -rq --ignore-unmatch .; \
	cp -r "$$stage/." "$$work/"; \
	git -C "$$work" add -A; \
	if ! git -C "$$work" diff --cached --quiet; then \
	  git -C "$$work" -c user.email="local@dev" -c user.name="local" commit -q -m "release $(2)"; \
	fi; \
	git -C "$$work" tag $(2); \
	git -C "$$work" push --atomic origin HEAD:main refs/tags/$(2)
endef

git-push-inventory_service_api: $(GH) ## Push module inventory_service_api to github.com/gorundebug/tsexample-inventory-service-api
	$(call git-push-dir,inventory_service_api,$(MODULE_VERSION),github.com,gorundebug/tsexample-inventory-service-api)

git-delete-inventory_service_api: $(GH) ## Delete module inventory_service_api from remote
	@$(GH) repo delete gorundebug/tsexample-inventory-service-api --yes 2>/dev/null || true


git-push-model: $(GH) ## Push module model to github.com/gorundebug/tsexample-model
	$(call git-push-dir,model,$(MODULE_VERSION),github.com,gorundebug/tsexample-model)

git-delete-model: $(GH) ## Delete module model from remote
	@$(GH) repo delete gorundebug/tsexample-model --yes 2>/dev/null || true


git-push-order_service_api: $(GH) ## Push module order_service_api to github.com/gorundebug/tsexample-order-service-api
	$(call git-push-dir,order_service_api,$(MODULE_VERSION),github.com,gorundebug/tsexample-order-service-api)

git-delete-order_service_api: $(GH) ## Delete module order_service_api from remote
	@$(GH) repo delete gorundebug/tsexample-order-service-api --yes 2>/dev/null || true


git-push-analyticsservice: $(GH) ## Push service Analytics Service to github.com/gorundebug/tsexample-analyticsservice
	$(call git-push-dir,analyticsservice,$(MODULE_VERSION),github.com,gorundebug/tsexample-analyticsservice,typescript-service)

git-delete-analyticsservice: $(GH) ## Delete service Analytics Service from remote
	@$(GH) repo delete gorundebug/tsexample-analyticsservice --yes 2>/dev/null || true


git-push-inventoryservice: $(GH) ## Push service Inventory Service to github.com/gorundebug/tsexample-inventoryservice
	$(call git-push-dir,inventoryservice,$(MODULE_VERSION),github.com,gorundebug/tsexample-inventoryservice,typescript-service)

git-delete-inventoryservice: $(GH) ## Delete service Inventory Service from remote
	@$(GH) repo delete gorundebug/tsexample-inventoryservice --yes 2>/dev/null || true


git-push-orderservice: $(GH) ## Push service Order Service to github.com/gorundebug/tsexample-orderservice
	$(call git-push-dir,orderservice,$(MODULE_VERSION),github.com,gorundebug/tsexample-orderservice,typescript-service)

git-delete-orderservice: $(GH) ## Delete service Order Service from remote
	@$(GH) repo delete gorundebug/tsexample-orderservice --yes 2>/dev/null || true


git-push-project: $(GH) ## Push project root to github.com/gorundebug/tsexample
	$(call git-push-dir,.,$(MODULE_VERSION),github.com,gorundebug/tsexample)

git-delete-project: $(GH) ## Delete project repository github.com/gorundebug/tsexample
	@$(GH) repo delete gorundebug/tsexample --yes 2>/dev/null || true


git-push: gen $(GH) ## Generate and push all modules, services, and project repositories
	@$(GH) auth status >/dev/null 2>&1 || { echo "ERROR: authenticate first with: $(GH) auth login"; exit 1; }

	@$(MAKE) git-push-inventory_service_api git-push-model git-push-order_service_api git-push-analyticsservice git-push-inventoryservice git-push-orderservice git-push-project

git-delete: $(GH) ## Delete all generated remote repositories
	@$(MAKE) git-delete-inventory_service_api git-delete-model git-delete-order_service_api git-delete-analyticsservice git-delete-inventoryservice git-delete-orderservice git-delete-project

help: ## Show this help
	@grep -hE '^[a-zA-Z0-9_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  %-32s %s\n", $$1, $$2}'