# Code generated by servicegen. DO NOT EDIT.

TYPESCRIPT_SERVICES := analyticsservice inventoryservice orderservice
TYPESCRIPT_PNPM ?= env CI=true corepack pnpm
TYPESCRIPT_PROGRESS := ./scripts/run-with-progress.generated.sh
CONFORMANCE_DIR ?= $(abspath $(PROJECT_DIR)/../conformance)
BENCHMARK_ARGS ?=
PROFILING_ARGS ?=
TYPESCRIPT_BUF_VERSION := v1.47.2
TYPESCRIPT_BUF := $(TOOLS_DIR)/typescript-buf

LANG_BUILD_TARGETS += typescript-build
LANG_TEST_TARGETS += typescript-test
LANG_LINT_TARGETS += typescript-lint
LANG_FMT_TARGETS += typescript-format
LANG_GEN_TARGETS += typescript-gen
LANG_CLEAN_TARGETS += typescript-clean
LANG_DOCKER_BUILD_TARGETS += typescript-docker-build
DOCKER_COMPOSE_RUNTIME_FILES += docker-compose.typescript-runtime.generated.yml
LANG_TOOL_TARGETS += typescript-tools

.PHONY: typecheck coverage profile benchmark typescript-install typescript-build typescript-test \
	typescript-typecheck typescript-coverage typescript-lint \
	typescript-format typescript-gen typescript-clean typescript-docker-build \
	typescript-package typescript-package-analyticsservice debug-analyticsservice typescript-package-inventoryservice debug-inventoryservice typescript-package-orderservice debug-orderservice typescript-tools

typescript-install:
	@if [ -f pnpm-lock.yaml ]; then \
		$(TYPESCRIPT_PROGRESS) "TypeScript dependency install" $(TYPESCRIPT_PNPM) install --frozen-lockfile; \
	else \
		$(TYPESCRIPT_PROGRESS) "TypeScript dependency install" $(TYPESCRIPT_PNPM) install; \
	fi

typescript-gen: typescript-install $(TYPESCRIPT_BUF)
	@$(TYPESCRIPT_PROGRESS) "Generate TypeScript module inventory_service_api" \
		$(MAKE) -C ./inventory_service_api generate SKIP_INSTALL=1 BUF="$(TYPESCRIPT_BUF)"
	@$(TYPESCRIPT_PROGRESS) "Generate TypeScript module model" \
		$(MAKE) -C ./model generate SKIP_INSTALL=1
	@$(TYPESCRIPT_PROGRESS) "Generate TypeScript module order_service_api" \
		$(MAKE) -C ./order_service_api generate SKIP_INSTALL=1

typescript-build: typescript-gen
	@$(TYPESCRIPT_PROGRESS) "TypeScript workspace build" $(TYPESCRIPT_PNPM) --recursive build

typescript-test: typescript-build
	@$(TYPESCRIPT_PROGRESS) "TypeScript workspace tests" $(TYPESCRIPT_PNPM) --recursive test

typescript-typecheck: typescript-gen
	@$(TYPESCRIPT_PROGRESS) "TypeScript workspace typecheck" $(TYPESCRIPT_PNPM) exec tsc --build --pretty false

typecheck: typescript-typecheck ## Type-check every TypeScript workspace package

typescript-coverage: typescript-build
	@$(TYPESCRIPT_PROGRESS) "TypeScript workspace coverage" $(TYPESCRIPT_PNPM) --recursive --if-present test:coverage

coverage: typescript-coverage ## Run TypeScript service tests with Node coverage

typescript-lint: typescript-install
	@$(TYPESCRIPT_PROGRESS) "TypeScript workspace lint" $(TYPESCRIPT_PNPM) exec eslint . --max-warnings 0

typescript-format: typescript-install
	@$(TYPESCRIPT_PROGRESS) "TypeScript workspace format" $(TYPESCRIPT_PNPM) exec prettier --write \
		'analyticsservice/**/*.ts' \
		'inventoryservice/**/*.ts' \
		'orderservice/**/*.ts' \
		'inventory_service_api/**/*.ts' \
		'model/**/*.ts' \
		'order_service_api/**/*.ts' \
		'eslint.config.js'

typescript-docker-build: ## Build TypeScript service Docker images
	@$(TYPESCRIPT_PROGRESS) "TypeScript Docker build and export" \
		$(DOCKER_COMPOSE) build $(TYPESCRIPT_SERVICES)

benchmark: ## Benchmark this TypeScript example and its native baseline
	@test -f "$(CONFORMANCE_DIR)/benchmarks/examples/run.py" || { \
		echo "ERROR: conformance checkout not found at $(CONFORMANCE_DIR); set CONFORMANCE_DIR" >&2; \
		exit 1; \
	}
	@BENCHMARK_DEPENDENCIES_DIR="$(abspath $(PROJECT_DIR)/..)" \
		python3 "$(CONFORMANCE_DIR)/benchmarks/examples/run.py" \
		--language typescript --language typescript-native $(BENCHMARK_ARGS)

profile: ## Profile this TypeScript example and its native baseline
	@test -f "$(CONFORMANCE_DIR)/profiling/examples/run.py" || { \
		echo "ERROR: conformance checkout not found at $(CONFORMANCE_DIR); set CONFORMANCE_DIR" >&2; \
		exit 1; \
	}
	@PROFILING_DEPENDENCIES_DIR="$(abspath $(PROJECT_DIR)/..)" \
		python3 "$(CONFORMANCE_DIR)/profiling/examples/run.py" \
		--language typescript --language typescript-native $(PROFILING_ARGS)

debug-analyticsservice: typescript-install ## Start Analytics Service with the Node inspector on localhost:2345
	@ANALYTICS_SERVICE_DEBUG=1 $(DOCKER_COMPOSE) \
		up -d --no-deps --build --force-recreate analyticsservice

debug-inventoryservice: typescript-install ## Start Inventory Service with the Node inspector on localhost:2346
	@INVENTORY_SERVICE_DEBUG=1 $(DOCKER_COMPOSE) \
		up -d --no-deps --build --force-recreate inventoryservice

debug-orderservice: typescript-install ## Start Order Service with the Node inspector on localhost:2347
	@ORDER_SERVICE_DEBUG=1 $(DOCKER_COMPOSE) \
		up -d --no-deps --build --force-recreate orderservice



typescript-package: typescript-package-analyticsservice typescript-package-inventoryservice typescript-package-orderservice ## Package every TypeScript service as a standalone repository

typescript-package-analyticsservice: ## Package analyticsservice as a standalone TypeScript service
	@rm -rf "dist/analyticsservice"
	@mkdir -p "dist/analyticsservice"
	@./scripts/package-typescript-service.generated.sh \
		"./analyticsservice" "dist/analyticsservice"

typescript-package-inventoryservice: ## Package inventoryservice as a standalone TypeScript service
	@rm -rf "dist/inventoryservice"
	@mkdir -p "dist/inventoryservice"
	@./scripts/package-typescript-service.generated.sh \
		"./inventoryservice" "dist/inventoryservice"

typescript-package-orderservice: ## Package orderservice as a standalone TypeScript service
	@rm -rf "dist/orderservice"
	@mkdir -p "dist/orderservice"
	@./scripts/package-typescript-service.generated.sh \
		"./orderservice" "dist/orderservice"



typescript-clean:
	@rm -rf ./analyticsservice/dist ./analyticsservice/dist-test \
		./analyticsservice/.cache ./analyticsservice/tsconfig.tsbuildinfo
	@rm -rf ./inventoryservice/dist ./inventoryservice/dist-test \
		./inventoryservice/.cache ./inventoryservice/tsconfig.tsbuildinfo
	@rm -rf ./orderservice/dist ./orderservice/dist-test \
		./orderservice/.cache ./orderservice/tsconfig.tsbuildinfo
	@rm -rf ./inventory_service_api/dist ./inventory_service_api/tsconfig.tsbuildinfo
	@rm -rf ./model/dist ./model/tsconfig.tsbuildinfo
	@rm -rf ./order_service_api/dist ./order_service_api/tsconfig.tsbuildinfo
$(TYPESCRIPT_BUF):
	@mkdir -p "$(TOOLS_DIR)"
	@$(TYPESCRIPT_PROGRESS) "Download buf $(TYPESCRIPT_BUF_VERSION)" \
		curl --fail --location --silent --show-error \
		"https://github.com/bufbuild/buf/releases/download/$(TYPESCRIPT_BUF_VERSION)/buf-$(OS)-$(ARCH)" \
		-o "$(TYPESCRIPT_BUF)"
	@chmod +x "$(TYPESCRIPT_BUF)"

typescript-tools: $(TYPESCRIPT_BUF) ## Install TypeScript code-generation tools
