packages:
  - "analyticsservice"
  - "automationservice"
  - "inventoryservice"
  - "orderservice"
  - "inventory_service_api"
  - "model"
  - "order_service_api"

allowBuilds:
  '@confluentinc/kafka-javascript': true
  '@swc/core': true
  esbuild: true
  protobufjs: false
