packages:
  - "analyticsservice"
  - "automationservice"
  - "inventoryservice"
  - "orderservice"
  - "inventory_service_api"
  - "model_ts"
  - "order_service_api"

injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
overrides:
  "@gorundebug/inventory-service-api": "workspace:*"
  "@gorundebug/model": "workspace:*"
  "@gorundebug/order-service-api": "workspace:*"
allowBuilds:
  '@confluentinc/kafka-javascript': true
  '@swc/core': true
  esbuild: true
  protobufjs: false
