// Code generated by servicegen. DO NOT EDIT.

import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

import { replayTemporalWorkflowHistory } from "@gorundebug/tsservicelib/datasource/temporal";

const historyPath = process.argv[2];
if (historyPath === undefined) {
  throw new Error("usage: temporal-replay.generated.js <temporal-history.json> [workflow-id]");
}

const history = JSON.parse(await readFile(historyPath, "utf8")) as unknown;
await replayTemporalWorkflowHistory(
  fileURLToPath(
    new URL("./internal/app/temporal-workflows.generated.js", import.meta.url),
  ),
  history,
  process.argv[3] ?? "servicegen-replay",
);
