// Code generated by servicegen. DO NOT EDIT.

import {
  canonicalConfigSchema,
  loadRuntimeConfig,
  parseConfigArguments,
  type EnvironmentPatch,
  type RuntimeConfig,
  type CaseStreamConfigDocument,
  type CronDataConnectorConfigDocument,
  type CronEndpointConfigDocument,
  type CustomDataConnectorConfigDocument,
  type CustomEndpointConfigDocument,
  type CycleLinkStreamConfigDocument,
  type FilterStreamConfigDocument,
  type InputStreamConfigDocument,
  type JoinStreamConfigDocument,
  type KafkaDataConnectorConfigDocument,
  type KafkaEndpointConfigDocument,
  type KeyByStreamConfigDocument,
  type MapStreamConfigDocument,
  type MergeStreamConfigDocument,
  type ModuleConfigDocument,
  type MultiJoinStreamConfigDocument,
  type ProcessStreamConfigDocument,
  type ServiceConfigDocument,
  type SinkStreamConfigDocument,
  type SplitStreamConfigDocument,
  type TypeConfigDocument,
  type WhenStreamConfigDocument,
} from "@gorundebug/tsservicelib/runtime/config";

import { ConfigSnapshot } from "./config-snapshot.generated.js";

export {
  DataConnectorIds,
  EndpointIds,
  ServiceIds,
  StreamIds,
  type NamedConfig,
} from "./config-snapshot.generated.js";

interface DefaultConfig {
  readonly services: {
    readonly "analyticsService": ServiceConfigDocument;
  };
  readonly streams: {
    readonly "advanceCycleAnalytics": MapStreamConfigDocument;
    readonly "analyticsOrders": InputStreamConfigDocument;
    readonly "analyticsPayments": InputStreamConfigDocument;
    readonly "analyticsSchedule": InputStreamConfigDocument;
    readonly "analyticsShipments": InputStreamConfigDocument;
    readonly "completeCycleAnalytics": FilterStreamConfigDocument;
    readonly "consumeOrderProcessed": InputStreamConfigDocument;
    readonly "continueCycleAnalytics": FilterStreamConfigDocument;
    readonly "countOrderProcessed": ProcessStreamConfigDocument;
    readonly "cycleAnalyticsInput": InputStreamConfigDocument;
    readonly "cycleAnalyticsLink": CycleLinkStreamConfigDocument;
    readonly "highValueAnalytics": WhenStreamConfigDocument;
    readonly "joinOrderPaymentAnalytics": JoinStreamConfigDocument;
    readonly "keyOrdersForJoin": KeyByStreamConfigDocument;
    readonly "keyOrdersForMultiJoin": KeyByStreamConfigDocument;
    readonly "keyPaymentsForJoin": KeyByStreamConfigDocument;
    readonly "keyPaymentsForMultiJoin": KeyByStreamConfigDocument;
    readonly "keyShipmentsForMultiJoin": KeyByStreamConfigDocument;
    readonly "mergeCycleAnalytics": MergeStreamConfigDocument;
    readonly "multiJoinAnalyticsEvents": MultiJoinStreamConfigDocument;
    readonly "routeAnalyticsResult": CaseStreamConfigDocument;
    readonly "splitAnalyticsOrders": SplitStreamConfigDocument;
    readonly "splitAnalyticsPayments": SplitStreamConfigDocument;
    readonly "splitCycleAnalytics": SplitStreamConfigDocument;
    readonly "standardAnalytics": WhenStreamConfigDocument;
    readonly "writeCycleAnalytics": SinkStreamConfigDocument;
    readonly "writeHighValueAnalytics": SinkStreamConfigDocument;
    readonly "writeJoinedAnalytics": SinkStreamConfigDocument;
    readonly "writeStandardAnalytics": SinkStreamConfigDocument;
  };
  readonly dataConnectors: {
    readonly "analyticsFunctions": CustomDataConnectorConfigDocument;
    readonly "localCron": CronDataConnectorConfigDocument;
    readonly "orderEvents": KafkaDataConnectorConfigDocument;
  };
  readonly endpoints: {
    readonly "analyticsOrders": CustomEndpointConfigDocument;
    readonly "analyticsPayments": CustomEndpointConfigDocument;
    readonly "analyticsSchedule": CronEndpointConfigDocument;
    readonly "analyticsShipments": CustomEndpointConfigDocument;
    readonly "cycleAnalyticsInput": CustomEndpointConfigDocument;
    readonly "cycleAnalyticsResult": CustomEndpointConfigDocument;
    readonly "highValueAnalytics": CustomEndpointConfigDocument;
    readonly "joinedAnalytics": CustomEndpointConfigDocument;
    readonly "orderProcessed": KafkaEndpointConfigDocument;
    readonly "standardAnalytics": CustomEndpointConfigDocument;
  };
  readonly pools: {
  };
  readonly links: {
  };
  readonly modules: {
    readonly "inventoryServiceApi": ModuleConfigDocument;
    readonly "model": ModuleConfigDocument;
    readonly "orderServiceApi": ModuleConfigDocument;
  };
  readonly types: {
    readonly "analyticsEvent": TypeConfigDocument;
    readonly "analyticsKey": TypeConfigDocument;
    readonly "analyticsResult": TypeConfigDocument;
    readonly "automationJob": TypeConfigDocument;
    readonly "orderProcessed": TypeConfigDocument;
  };
}

const DEFAULT_CONFIG = {
  "services": {
    "analyticsService": {
      "color": "#05ABF7",
      "defaultCallSemantics": 2,
      "defaultGrpcTimeout": 0,
      "environment": "",
      "golangVersion": "1.25.4",
      "grpcHost": "0.0.0.0",
      "grpcPort": 9203,
      "httpHost": "0.0.0.0",
      "httpPort": 9093,
      "id": 1,
      "metricsHandler": "metrics",
      "startupHandler": "health/startup",
      "readinessHandler": "health/ready",
      "livenessHandler": "health/live",
      "kubernetesWorkloadType": "Deployment",
      "modulePath": "github.com/gorundebug/tsexample-analyticsservice",
      "name": "Analytics Service",
      "shutdownTimeout": 30000,
      "statusHandler": "status"
    }
  },
  "streams": {
    "advanceCycleAnalytics": {
      "functionDescription": "Increment the cycle counter while preserving the analytics event identity.",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "AdvanceCycleAnalytics",
      "functionPackage": "cycleanalytics",
      "id": 9,
      "idService": 1,
      "idSource": 14,
      "name": "Advance Cycle Analytics",
      "pipeline": "cycleAnalytics",
      "type": 2,
      "valueType": "AnalyticsEvent",
      "xPos": -1100,
      "yPos": 1160
    },
    "analyticsOrders": {
      "id": 4,
      "idEndpoint": 1,
      "idService": 1,
      "idSource": 0,
      "name": "Analytics Orders",
      "pipeline": "analyticsSources",
      "type": 1,
      "valueType": "AnalyticsEvent",
      "xPos": -1600,
      "yPos": 220
    },
    "analyticsPayments": {
      "id": 5,
      "idEndpoint": 2,
      "idService": 1,
      "idSource": 0,
      "name": "Analytics Payments",
      "pipeline": "analyticsSources",
      "type": 1,
      "valueType": "AnalyticsEvent",
      "xPos": -1600,
      "yPos": 430
    },
    "analyticsSchedule": {
      "id": 1,
      "idEndpoint": 9,
      "idService": 1,
      "idSource": 0,
      "name": "Analytics Schedule",
      "pipeline": "analytics",
      "type": 1,
      "valueType": "AutomationJob",
      "xPos": -1600,
      "yPos": -205
    },
    "analyticsShipments": {
      "id": 6,
      "idEndpoint": 3,
      "idService": 1,
      "idSource": 0,
      "name": "Analytics Shipments",
      "pipeline": "analyticsSources",
      "type": 1,
      "valueType": "AnalyticsEvent",
      "xPos": -1600,
      "yPos": 780
    },
    "completeCycleAnalytics": {
      "functionDescription": "Keep the terminal analytics event once its cycle counter reaches three.",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "CompleteCycleAnalytics",
      "functionPackage": "cycleanalytics",
      "id": 10,
      "idService": 1,
      "idSource": 15,
      "name": "Complete Cycle Analytics",
      "pipeline": "cycleAnalytics",
      "type": 3,
      "xPos": -600,
      "yPos": 1260
    },
    "consumeOrderProcessed": {
      "id": 2,
      "idEndpoint": 10,
      "idService": 1,
      "idSource": 3,
      "name": "Consume Order Processed",
      "pipeline": "analytics",
      "type": 1,
      "valueType": "OrderProcessed",
      "xPos": -1190,
      "yPos": -205
    },
    "continueCycleAnalytics": {
      "functionDescription": "Keep intermediate analytics events whose cycle counter is below three.",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "ContinueCycleAnalytics",
      "functionPackage": "cycleanalytics",
      "id": 11,
      "idService": 1,
      "idSource": 15,
      "name": "Continue Cycle Analytics",
      "pipeline": "cycleAnalytics",
      "type": 3,
      "xPos": -600,
      "yPos": 1060
    },
    "countOrderProcessed": {
      "functionDescription": "Count successful and unsuccessful orders independently, then return the event unchanged.\n",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "CountOrderProcessed",
      "functionPackage": "analytics",
      "id": 3,
      "idService": 1,
      "idSource": 2,
      "name": "Count Order Processed",
      "pipeline": "analytics",
      "type": 6,
      "xPos": -1390,
      "yPos": -19
    },
    "cycleAnalyticsInput": {
      "id": 12,
      "idEndpoint": 4,
      "idService": 1,
      "idSource": 0,
      "name": "Cycle Analytics Input",
      "pipeline": "cycleAnalytics",
      "type": 1,
      "valueType": "AnalyticsEvent",
      "xPos": -1600,
      "yPos": 1160
    },
    "cycleAnalyticsLink": {
      "id": 13,
      "idService": 1,
      "idSource": 11,
      "name": "Cycle Analytics Link",
      "pipeline": "cycleAnalytics",
      "type": 14,
      "xPos": -1100,
      "yPos": 960
    },
    "highValueAnalytics": {
      "id": 21,
      "idService": 1,
      "idSource": 26,
      "name": "High Value Analytics",
      "pipeline": "multiJoinAnalytics",
      "type": 17,
      "valueType": "AnalyticsResult",
      "xPos": -400,
      "yPos": 650
    },
    "joinOrderPaymentAnalytics": {
      "functionDescription": "Join matching order and payment analytics events and emit their combined total.",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "JoinOrderPaymentAnalytics",
      "functionPackage": "joinanalytics",
      "id": 17,
      "idService": 1,
      "idSource": 18,
      "idSources": [
        19
      ],
      "joinStorage": 1,
      "joinType": 1,
      "name": "Join Order Payment Analytics",
      "pipeline": "joinAnalytics",
      "renewTTL": true,
      "ttl": 60000,
      "type": 4,
      "valueType": "AnalyticsResult",
      "xPos": -900,
      "yPos": 260
    },
    "keyOrdersForJoin": {
      "functionDescription": "Key the order analytics event by correlation key.",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "KeyOrdersForJoin",
      "functionPackage": "joinanalytics",
      "id": 18,
      "idService": 1,
      "idSource": 7,
      "keyType": "AnalyticsKey",
      "name": "Key Orders For Join",
      "pipeline": "joinAnalytics",
      "type": 9,
      "valueType": "AnalyticsEvent",
      "xPos": -1160,
      "yPos": 170
    },
    "keyOrdersForMultiJoin": {
      "functionDescription": "Key the order analytics event for the multi-way join.",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "KeyOrdersForMultiJoin",
      "functionPackage": "multijoinanalytics",
      "id": 22,
      "idService": 1,
      "idSource": 7,
      "keyType": "AnalyticsKey",
      "name": "Key Orders For Multi Join",
      "pipeline": "multiJoinAnalytics",
      "type": 9,
      "valueType": "AnalyticsEvent",
      "xPos": -1160,
      "yPos": 570
    },
    "keyPaymentsForJoin": {
      "functionDescription": "Key the payment analytics event by correlation key.",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "KeyPaymentsForJoin",
      "functionPackage": "joinanalytics",
      "id": 19,
      "idService": 1,
      "idSource": 8,
      "keyType": "AnalyticsKey",
      "name": "Key Payments For Join",
      "pipeline": "joinAnalytics",
      "type": 9,
      "valueType": "AnalyticsEvent",
      "xPos": -1160,
      "yPos": 350
    },
    "keyPaymentsForMultiJoin": {
      "functionDescription": "Key the payment analytics event for the multi-way join.",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "KeyPaymentsForMultiJoin",
      "functionPackage": "multijoinanalytics",
      "id": 23,
      "idService": 1,
      "idSource": 8,
      "keyType": "AnalyticsKey",
      "name": "Key Payments For Multi Join",
      "pipeline": "multiJoinAnalytics",
      "type": 9,
      "valueType": "AnalyticsEvent",
      "xPos": -1160,
      "yPos": 740
    },
    "keyShipmentsForMultiJoin": {
      "functionDescription": "Key the shipment analytics event for the multi-way join.",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "KeyShipmentsForMultiJoin",
      "functionPackage": "multijoinanalytics",
      "id": 24,
      "idService": 1,
      "idSource": 6,
      "keyType": "AnalyticsKey",
      "name": "Key Shipments For Multi Join",
      "pipeline": "multiJoinAnalytics",
      "type": 9,
      "valueType": "AnalyticsEvent",
      "xPos": -1160,
      "yPos": 910
    },
    "mergeCycleAnalytics": {
      "id": 14,
      "idService": 1,
      "idSource": 0,
      "idSources": [
        12,
        13
      ],
      "name": "Merge Cycle Analytics",
      "pipeline": "cycleAnalytics",
      "type": 10,
      "xPos": -1350,
      "yPos": 1160
    },
    "multiJoinAnalyticsEvents": {
      "functionDescription": "Combine matching order, payment, and shipment analytics events.",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "MultiJoinAnalyticsEvents",
      "functionPackage": "multijoinanalytics",
      "id": 25,
      "idService": 1,
      "idSource": 22,
      "idSources": [
        23,
        24
      ],
      "joinStorage": 1,
      "name": "Multi Join Analytics Events",
      "pipeline": "multiJoinAnalytics",
      "renewTTL": true,
      "ttl": 60000,
      "type": 5,
      "valueType": "AnalyticsResult",
      "xPos": -900,
      "yPos": 740
    },
    "routeAnalyticsResult": {
      "functionDescription": "Route high-value analytics results to the first branch and all others to the second branch.",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "RouteAnalyticsResult",
      "functionPackage": "multijoinanalytics",
      "id": 26,
      "idService": 1,
      "idSource": 25,
      "name": "Route Analytics Result",
      "pipeline": "multiJoinAnalytics",
      "type": 12,
      "xPos": -650,
      "yPos": 740
    },
    "splitAnalyticsOrders": {
      "id": 7,
      "idService": 1,
      "idSource": 4,
      "name": "Split Analytics Orders",
      "pipeline": "analyticsSources",
      "type": 11,
      "xPos": -1390,
      "yPos": 220
    },
    "splitAnalyticsPayments": {
      "id": 8,
      "idService": 1,
      "idSource": 5,
      "name": "Split Analytics Payments",
      "pipeline": "analyticsSources",
      "type": 11,
      "xPos": -1390,
      "yPos": 430
    },
    "splitCycleAnalytics": {
      "id": 15,
      "idService": 1,
      "idSource": 9,
      "name": "Split Cycle Analytics",
      "pipeline": "cycleAnalytics",
      "type": 11,
      "xPos": -850,
      "yPos": 1160
    },
    "standardAnalytics": {
      "id": 27,
      "idService": 1,
      "idSource": 26,
      "name": "Standard Analytics",
      "pipeline": "multiJoinAnalytics",
      "type": 17,
      "valueType": "AnalyticsResult",
      "xPos": -400,
      "yPos": 830
    },
    "writeCycleAnalytics": {
      "id": 16,
      "idEndpoint": 5,
      "idService": 1,
      "idSource": 10,
      "name": "Write Cycle Analytics",
      "pipeline": "cycleAnalytics",
      "type": 13,
      "valueType": "AnalyticsEvent",
      "xPos": -350,
      "yPos": 1260
    },
    "writeHighValueAnalytics": {
      "id": 28,
      "idEndpoint": 6,
      "idService": 1,
      "idSource": 21,
      "name": "Write High Value Analytics",
      "pipeline": "multiJoinAnalytics",
      "type": 13,
      "valueType": "AnalyticsResult",
      "xPos": -130,
      "yPos": 650
    },
    "writeJoinedAnalytics": {
      "id": 20,
      "idEndpoint": 7,
      "idService": 1,
      "idSource": 17,
      "name": "Write Joined Analytics",
      "pipeline": "joinAnalytics",
      "type": 13,
      "valueType": "AnalyticsResult",
      "xPos": -640,
      "yPos": 260
    },
    "writeStandardAnalytics": {
      "id": 29,
      "idEndpoint": 8,
      "idService": 1,
      "idSource": 27,
      "name": "Write Standard Analytics",
      "pipeline": "multiJoinAnalytics",
      "type": 13,
      "valueType": "AnalyticsResult",
      "xPos": -130,
      "yPos": 830
    }
  },
  "dataConnectors": {
    "analyticsFunctions": {
      "id": 1,
      "implementation": "function",
      "name": "Analytics Functions",
      "type": 4
    },
    "localCron": {
      "id": 2,
      "implementation": "node/croner",
      "name": "Local Cron",
      "type": 5
    },
    "orderEvents": {
      "brokers": "redpanda:9092",
      "dialTimeout": 5000,
      "id": 3,
      "implementation": "confluent/kafka-javascript",
      "name": "Order Events",
      "password": "",
      "saslMechanism": "SCRAM-SHA-512",
      "securityProtocol": "PLAINTEXT",
      "type": 3,
      "username": "",
      "version": "2.8.0"
    }
  },
  "endpoints": {
    "analyticsOrders": {
      "functionDescription": "Produce a deterministic order analytics event for the canonical join examples.",
      "functionInitializerGroup": "",
      "functionName": "AnalyticsOrders",
      "functionPackage": "endpoint",
      "id": 1,
      "idDataConnector": 1,
      "name": "Analytics Orders",
      "publicFunction": false
    },
    "analyticsPayments": {
      "functionDescription": "Produce a deterministic payment analytics event for the canonical join examples.",
      "functionInitializerGroup": "",
      "functionName": "AnalyticsPayments",
      "functionPackage": "endpoint",
      "id": 2,
      "idDataConnector": 1,
      "name": "Analytics Payments",
      "publicFunction": false
    },
    "analyticsSchedule": {
      "enabled": true,
      "functionDescription": "Create an analytics job message identifying the local scheduled firing.\n",
      "functionInitializerGroup": "",
      "functionName": "AnalyticsSchedule",
      "functionPackage": "cron",
      "id": 9,
      "idDataConnector": 2,
      "missedRunPolicy": "FireOnce",
      "name": "Analytics Schedule",
      "overlapPolicy": "Skip",
      "publicFunction": false,
      "schedule": "*/5 * * * *",
      "timezone": "UTC",
      "tracingEnabled": false
    },
    "analyticsShipments": {
      "functionDescription": "Produce a deterministic shipment analytics event for the canonical multi-way join example.",
      "functionInitializerGroup": "",
      "functionName": "AnalyticsShipments",
      "functionPackage": "endpoint",
      "id": 3,
      "idDataConnector": 1,
      "name": "Analytics Shipments",
      "publicFunction": false
    },
    "cycleAnalyticsInput": {
      "functionDescription": "Produce one deterministic analytics event that exercises the finite feedback cycle.",
      "functionInitializerGroup": "",
      "functionName": "CycleAnalyticsInput",
      "functionPackage": "endpoint",
      "id": 4,
      "idDataConnector": 1,
      "name": "Cycle Analytics Input",
      "publicFunction": false
    },
    "cycleAnalyticsResult": {
      "functionDescription": "Validate the terminal event emitted after three passes through the feedback cycle.",
      "functionInitializerGroup": "",
      "functionName": "CycleAnalyticsResult",
      "functionPackage": "endpoint",
      "id": 5,
      "idDataConnector": 1,
      "name": "Cycle Analytics Result",
      "publicFunction": false
    },
    "highValueAnalytics": {
      "functionDescription": "Validate and record analytics results routed to the high-value Case branch.",
      "functionInitializerGroup": "",
      "functionName": "HighValueAnalytics",
      "functionPackage": "endpoint",
      "id": 6,
      "idDataConnector": 1,
      "name": "High Value Analytics",
      "publicFunction": false
    },
    "joinedAnalytics": {
      "functionDescription": "Validate and record the result of the two-way analytics join.",
      "functionInitializerGroup": "",
      "functionName": "JoinedAnalytics",
      "functionPackage": "endpoint",
      "id": 7,
      "idDataConnector": 1,
      "name": "Joined Analytics",
      "publicFunction": false
    },
    "orderProcessed": {
      "consumerGroup": "analytics-service",
      "createTopic": true,
      "enabled": true,
      "functionDescription": "Exchange OrderProcessed events keyed by order ID.\nProducers include the final status, processing time, total and confirmed item counts, and a failure reason for unsuccessful orders.\nConsumers decode the event and mark its Kafka message processed only after the pipeline handles it successfully.\n",
      "functionInitializerGroup": "",
      "functionName": "OrderProcessedEndpoint",
      "functionPackage": "endpoint",
      "id": 10,
      "idDataConnector": 3,
      "name": "Order Processed",
      "partitions": 1,
      "publicFunction": false,
      "replicationFactor": 1,
      "topic": "order-processed"
    },
    "standardAnalytics": {
      "functionDescription": "Validate and record analytics results routed to the standard Case branch.",
      "functionInitializerGroup": "",
      "functionName": "StandardAnalytics",
      "functionPackage": "endpoint",
      "id": 8,
      "idDataConnector": 1,
      "name": "Standard Analytics",
      "publicFunction": false
    }
  },
  "pools": {},
  "links": {},
  "modules": {
    "inventoryServiceApi": {
      "name": "inventory_service_api",
      "path": "github.com/gorundebug/tsexample-inventory-service-api"
    },
    "model": {
      "name": "model",
      "path": "github.com/gorundebug/tsexample-model"
    },
    "orderServiceApi": {
      "name": "order_service_api",
      "path": "github.com/gorundebug/tsexample-order-service-api"
    }
  },
  "types": {
    "analyticsEvent": {
      "name": "AnalyticsEvent",
      "type": "struct",
      "typeDefinition": "AnalyticsEvent",
      "typeImport": "./internal/types/analytics-event.js",
      "definitionFormat": 1
    },
    "analyticsKey": {
      "name": "AnalyticsKey",
      "type": "string",
      "typeDefinition": "string",
      "typeImport": "./internal/types/analytics-key.js"
    },
    "analyticsResult": {
      "name": "AnalyticsResult",
      "type": "struct",
      "typeDefinition": "AnalyticsResult",
      "typeImport": "./internal/types/analytics-result.js",
      "definitionFormat": 1
    },
    "automationJob": {
      "name": "AutomationJob",
      "type": "string",
      "typeDefinition": "string",
      "typeImport": "@gorundebug/model/types/automation-job.js",
      "module": "model",
      "publicType": true
    },
    "orderProcessed": {
      "name": "OrderProcessed",
      "type": "struct",
      "typeDefinition": "OrderProcessed",
      "typeImport": "@gorundebug/model/types/order-processed.js",
      "module": "model",
      "definitionFormat": 1
    }
  }
} as const satisfies DefaultConfig;

export function parseStringEnvironment(value: string): string { return value; }

export function parseIntegerEnvironment(value: string): number {
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed)) throw new Error(`expected an integer, got ${value}`);
  return parsed;
}

export function parseNumberEnvironment(value: string): number {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) throw new Error(`expected a number, got ${value}`);
  return parsed;
}

export function parseBooleanEnvironment(value: string): boolean {
  switch (value.trim().toLowerCase()) {
    case "1": case "true": case "yes": case "on": return true;
    case "0": case "false": case "no": case "off": return false;
    default: throw new Error(`expected a boolean, got ${value}`);
  }
}

export function parseStringListEnvironment(value: string): readonly string[] {
  return value.split(",").map((item) => item.trim()).filter((item) => item.length > 0);
}

export function parseIntegerListEnvironment(value: string): readonly number[] {
  return parseStringListEnvironment(value).map(parseIntegerEnvironment);
}

const ENVIRONMENT_PATCHES: readonly EnvironmentPatch[] = [
  { environment: "ANALYTICS_SCHEDULE_ENABLED", path: ["endpoints", "analyticsSchedule", "enabled", ], parse: parseBooleanEnvironment },
  { environment: "ANALYTICS_SCHEDULE_MISSED_RUN_POLICY", path: ["endpoints", "analyticsSchedule", "missedRunPolicy", ], parse: parseStringEnvironment },
  { environment: "ANALYTICS_SCHEDULE_OVERLAP_POLICY", path: ["endpoints", "analyticsSchedule", "overlapPolicy", ], parse: parseStringEnvironment },
  { environment: "ANALYTICS_SCHEDULE_SCHEDULE", path: ["endpoints", "analyticsSchedule", "schedule", ], parse: parseStringEnvironment },
  { environment: "ANALYTICS_SCHEDULE_TIMEZONE", path: ["endpoints", "analyticsSchedule", "timezone", ], parse: parseStringEnvironment },
  { environment: "ANALYTICS_SCHEDULE_TRACING_ENABLED", path: ["endpoints", "analyticsSchedule", "tracingEnabled", ], parse: parseBooleanEnvironment },
  { environment: "ANALYTICS_SERVICE_DEFAULT_GRPC_TIMEOUT", path: ["services", "analyticsService", "defaultGrpcTimeout", ], parse: parseIntegerEnvironment },
  { environment: "ANALYTICS_SERVICE_ENVIRONMENT", path: ["services", "analyticsService", "environment", ], parse: parseStringEnvironment },
  { environment: "ANALYTICS_SERVICE_GRPC_HOST", path: ["services", "analyticsService", "grpcHost", ], parse: parseStringEnvironment },
  { environment: "ANALYTICS_SERVICE_GRPC_PORT", path: ["services", "analyticsService", "grpcPort", ], parse: parseIntegerEnvironment },
  { environment: "ANALYTICS_SERVICE_HTTP_HOST", path: ["services", "analyticsService", "httpHost", ], parse: parseStringEnvironment },
  { environment: "ANALYTICS_SERVICE_HTTP_PORT", path: ["services", "analyticsService", "httpPort", ], parse: parseIntegerEnvironment },
  { environment: "ORDER_EVENTS_BROKERS", path: ["dataConnectors", "orderEvents", "brokers", ], parse: parseStringEnvironment },
  { environment: "ORDER_EVENTS_PASSWORD", path: ["dataConnectors", "orderEvents", "password", ], parse: parseStringEnvironment },
  { environment: "ORDER_EVENTS_SASL_MECHANISM", path: ["dataConnectors", "orderEvents", "saslMechanism", ], parse: parseStringEnvironment },
  { environment: "ORDER_EVENTS_SECURITY_PROTOCOL", path: ["dataConnectors", "orderEvents", "securityProtocol", ], parse: parseStringEnvironment },
  { environment: "ORDER_EVENTS_USERNAME", path: ["dataConnectors", "orderEvents", "username", ], parse: parseStringEnvironment },
  { environment: "ORDER_PROCESSED_ENABLED", path: ["endpoints", "orderProcessed", "enabled", ], parse: parseBooleanEnvironment },
];

export class ConfigGenerated extends ConfigSnapshot {

  public static configPaths(arguments_: readonly string[]) {
    return parseConfigArguments(arguments_);
  }

  protected static async loadRuntime(arguments_: readonly string[]): Promise<RuntimeConfig> {
    const paths = ConfigGenerated.configPaths(arguments_);
    const runtime = await loadRuntimeConfig({
      configPath: paths.configPath,
      valuesPath: paths.valuesPath,
      overridesPath: paths.overridesPath,
      defaults: DEFAULT_CONFIG,
      patches: ENVIRONMENT_PATCHES,
      schema: canonicalConfigSchema
    });
    return runtime;
  }
}
