// Code generated by servicegen. DO NOT EDIT.

import {
  canonicalConfigSchema,
  loadRuntimeConfig,
  parseConfigArguments,
  type EnvironmentPatch,
  type RuntimeConfig,
  type InputStreamConfigDocument,
  type KafkaDataConnectorConfigDocument,
  type KafkaEndpointConfigDocument,
  type ModuleConfigDocument,
  type ProcessStreamConfigDocument,
  type ServiceConfigDocument,
  type TypeConfigDocument,
} from "@gorundebug/tsservicelib/runtime/config";

import { ConfigSnapshot } from "./config-snapshot.generated.js";

export {
  DataConnectorIds,
  EndpointIds,
  ServiceIds,
  StreamIds,
  type NamedConfig,
} from "./config-snapshot.generated.js";

interface DefaultConfig {
  readonly services: {
    readonly "analyticsService": ServiceConfigDocument;
  };
  readonly streams: {
    readonly "consumeOrderProcessed": InputStreamConfigDocument;
    readonly "countOrderProcessed": ProcessStreamConfigDocument;
  };
  readonly dataConnectors: {
    readonly "orderEvents": KafkaDataConnectorConfigDocument;
  };
  readonly endpoints: {
    readonly "orderProcessed": KafkaEndpointConfigDocument;
  };
  readonly pools: {
  };
  readonly links: {
  };
  readonly modules: {
    readonly "inventoryServiceApi": ModuleConfigDocument;
    readonly "model": ModuleConfigDocument;
    readonly "orderServiceApi": ModuleConfigDocument;
  };
  readonly types: {
    readonly "orderProcessed": TypeConfigDocument;
  };
}

const DEFAULT_CONFIG = {
  "services": {
    "analyticsService": {
      "color": "#05ABF7",
      "defaultCallSemantics": 2,
      "defaultGrpcTimeout": 0,
      "environment": "",
      "golangVersion": "1.25.4",
      "grpcHost": "0.0.0.0",
      "grpcPort": 9203,
      "httpHost": "0.0.0.0",
      "httpPort": 9093,
      "id": 1,
      "metricsHandler": "metrics",
      "startupHandler": "health/startup",
      "readinessHandler": "health/ready",
      "livenessHandler": "health/live",
      "kubernetesWorkloadType": "Deployment",
      "modulePath": "github.com/gorundebug/tsexample-analyticsservice",
      "name": "Analytics Service",
      "shutdownTimeout": 30000,
      "statusHandler": "status"
    }
  },
  "streams": {
    "consumeOrderProcessed": {
      "id": 1,
      "idEndpoint": 1,
      "idService": 1,
      "idSource": 2,
      "name": "Consume Order Processed",
      "pipeline": "analytics",
      "type": 1,
      "valueType": "OrderProcessed",
      "xPos": -1190,
      "yPos": -205
    },
    "countOrderProcessed": {
      "functionDescription": "Count successful and unsuccessful orders independently, then return the event unchanged.\n",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "CountOrderProcessed",
      "functionPackage": "",
      "id": 2,
      "idService": 1,
      "idSource": 1,
      "name": "Count Order Processed",
      "pipeline": "analytics",
      "type": 6,
      "xPos": -1390,
      "yPos": -19
    }
  },
  "dataConnectors": {
    "orderEvents": {
      "brokers": "redpanda:9092",
      "id": 1,
      "implementation": "confluent/kafka-javascript",
      "name": "Order Events",
      "password": "",
      "saslMechanism": "SCRAM-SHA-512",
      "securityProtocol": "PLAINTEXT",
      "type": 3,
      "username": "",
      "version": "2.8.0"
    }
  },
  "endpoints": {
    "orderProcessed": {
      "consumerGroup": "analytics-service",
      "createTopic": true,
      "enabled": true,
      "functionDescription": "Exchange OrderProcessed events keyed by order ID.\nProducers include the final status, processing time, total and confirmed item counts, and a failure reason for unsuccessful orders.\nConsumers decode the event and mark its Kafka message processed only after the pipeline handles it successfully.\n",
      "functionInitializerGroup": "",
      "functionName": "OrderProcessedEndpoint",
      "functionPackage": "",
      "id": 1,
      "idDataConnector": 1,
      "name": "Order Processed",
      "partitions": 1,
      "publicFunction": false,
      "replicationFactor": 1,
      "topic": "order-processed"
    }
  },
  "pools": {},
  "links": {},
  "modules": {
    "inventoryServiceApi": {
      "name": "inventory_service_api",
      "path": "github.com/gorundebug/tsexample-inventory-service-api"
    },
    "model": {
      "name": "model",
      "path": "github.com/gorundebug/tsexample-model"
    },
    "orderServiceApi": {
      "name": "order_service_api",
      "path": "github.com/gorundebug/tsexample-order-service-api"
    }
  },
  "types": {
    "orderProcessed": {
      "name": "OrderProcessed",
      "type": "struct",
      "typeDefinition": "OrderProcessed",
      "typeImport": "@gorundebug/model/types/order-processed.js",
      "module": "model",
      "definitionFormat": 1
    }
  }
} as const satisfies DefaultConfig;

export function parseStringEnvironment(value: string): string { return value; }

export function parseIntegerEnvironment(value: string): number {
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed)) throw new Error(`expected an integer, got ${value}`);
  return parsed;
}

export function parseNumberEnvironment(value: string): number {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) throw new Error(`expected a number, got ${value}`);
  return parsed;
}

export function parseBooleanEnvironment(value: string): boolean {
  switch (value.trim().toLowerCase()) {
    case "1": case "true": case "yes": case "on": return true;
    case "0": case "false": case "no": case "off": return false;
    default: throw new Error(`expected a boolean, got ${value}`);
  }
}

export function parseStringListEnvironment(value: string): readonly string[] {
  return value.split(",").map((item) => item.trim()).filter((item) => item.length > 0);
}

export function parseIntegerListEnvironment(value: string): readonly number[] {
  return parseStringListEnvironment(value).map(parseIntegerEnvironment);
}

const ENVIRONMENT_PATCHES: readonly EnvironmentPatch[] = [
  { environment: "ANALYTICS_SERVICE_DEFAULT_GRPC_TIMEOUT", path: ["services", "analyticsService", "defaultGrpcTimeout", ], parse: parseIntegerEnvironment },
  { environment: "ANALYTICS_SERVICE_ENVIRONMENT", path: ["services", "analyticsService", "environment", ], parse: parseStringEnvironment },
  { environment: "ANALYTICS_SERVICE_GRPC_HOST", path: ["services", "analyticsService", "grpcHost", ], parse: parseStringEnvironment },
  { environment: "ANALYTICS_SERVICE_GRPC_PORT", path: ["services", "analyticsService", "grpcPort", ], parse: parseIntegerEnvironment },
  { environment: "ANALYTICS_SERVICE_HTTP_HOST", path: ["services", "analyticsService", "httpHost", ], parse: parseStringEnvironment },
  { environment: "ANALYTICS_SERVICE_HTTP_PORT", path: ["services", "analyticsService", "httpPort", ], parse: parseIntegerEnvironment },
  { environment: "ORDER_EVENTS_BROKERS", path: ["dataConnectors", "orderEvents", "brokers", ], parse: parseStringEnvironment },
  { environment: "ORDER_EVENTS_PASSWORD", path: ["dataConnectors", "orderEvents", "password", ], parse: parseStringEnvironment },
  { environment: "ORDER_EVENTS_SASL_MECHANISM", path: ["dataConnectors", "orderEvents", "saslMechanism", ], parse: parseStringEnvironment },
  { environment: "ORDER_EVENTS_SECURITY_PROTOCOL", path: ["dataConnectors", "orderEvents", "securityProtocol", ], parse: parseStringEnvironment },
  { environment: "ORDER_EVENTS_USERNAME", path: ["dataConnectors", "orderEvents", "username", ], parse: parseStringEnvironment },
  { environment: "ORDER_PROCESSED_ENABLED", path: ["endpoints", "orderProcessed", "enabled", ], parse: parseBooleanEnvironment },
];

export class ConfigGenerated extends ConfigSnapshot {

  public static configPaths(arguments_: readonly string[]) {
    return parseConfigArguments(arguments_);
  }

  protected static async loadRuntime(arguments_: readonly string[]): Promise<RuntimeConfig> {
    const paths = ConfigGenerated.configPaths(arguments_);
    const runtime = await loadRuntimeConfig({
      configPath: paths.configPath,
      valuesPath: paths.valuesPath,
      defaults: DEFAULT_CONFIG,
      patches: ENVIRONMENT_PATCHES,
      schema: canonicalConfigSchema
    });
    return runtime;
  }
}
