dataConnectors:
  temporal:
    address: $temporalAddress
endpoints:
  activityJob:
    enabled: $activityJobEnabled
  fanOutActivityA:
    enabled: $fanOutActivityAEnabled
  fanOutActivityB:
    enabled: $fanOutActivityBEnabled
  fanOutActivityC:
    enabled: $fanOutActivityCEnabled
  fanOutWorkflowJob:
    enabled: $fanOutWorkflowJobEnabled
  localSchedule:
    enabled: $localScheduleEnabled
  sequentialActivityA:
    enabled: $sequentialActivityAEnabled
  sequentialActivityB:
    enabled: $sequentialActivityBEnabled
  temporalActivitySchedule:
    enabled: $temporalActivityScheduleEnabled
  temporalWorkflowSchedule:
    enabled: $temporalWorkflowScheduleEnabled
  workflowJob:
    enabled: $workflowJobEnabled
pools:
  defaultPool:
    executorsCount: $defaultPoolExecutorsCount
services:
  automationService:
    defaultGrpcTimeout: $automationServiceDefaultGrpcTimeout
    environment: $automationServiceEnvironment
    grpcHost: $automationServiceGrpcHost
    grpcPort: $automationServiceGrpcPort
    httpHost: $automationServiceHttpHost
    httpPort: $automationServiceHttpPort
streams:
  activityPause:
    duration: $activityPauseDuration
  scheduledActivityPause:
    duration: $scheduledActivityPauseDuration
  scheduledWorkflowPause:
    duration: $scheduledWorkflowPauseDuration
  workflowPause:
    duration: $workflowPauseDuration
