dataConnectors:
  temporal:
    address: temporal:7233
endpoints:
  activityJob:
    enabled: true
    tracingEnabled: false
  fanOutActivityA:
    enabled: true
    tracingEnabled: false
  fanOutActivityB:
    enabled: true
    tracingEnabled: false
  fanOutActivityC:
    enabled: true
    tracingEnabled: false
  fanOutWorkflowJob:
    enabled: true
    tracingEnabled: false
  localSchedule:
    enabled: true
    tracingEnabled: false
  sequentialActivityA:
    enabled: true
    tracingEnabled: false
  sequentialActivityB:
    enabled: true
    tracingEnabled: false
  temporalActivitySchedule:
    enabled: true
    tracingEnabled: false
  temporalWorkflowSchedule:
    enabled: true
    tracingEnabled: false
  workflowJob:
    enabled: true
    tracingEnabled: false
pools:
  defaultPool:
    executorsCount: 2
services:
  automationService:
    defaultGrpcTimeout: 0
    environment: ""
    grpcHost: 0.0.0.0
    grpcPort: 9204
    httpHost: 0.0.0.0
    httpPort: 9094
streams:
  activityPause:
    duration: 250
  scheduledActivityPause:
    duration: 250
  scheduledWorkflowPause:
    duration: 250
  workflowPause:
    duration: 250
