dataConnectors:
  temporal:
    address: temporal:7233
endpoints:
  activityJob:
    enabled: true
  fanOutActivityA:
    enabled: true
  fanOutActivityB:
    enabled: true
  fanOutActivityC:
    enabled: true
  fanOutWorkflowJob:
    enabled: true
  localSchedule:
    enabled: true
  sequentialActivityA:
    enabled: true
  sequentialActivityB:
    enabled: true
  temporalActivitySchedule:
    enabled: true
  temporalWorkflowSchedule:
    enabled: true
  workflowJob:
    enabled: true
services:
  automationService:
    defaultGrpcTimeout: 0
    environment: ""
    grpcHost: 0.0.0.0
    grpcPort: 9204
    httpHost: 0.0.0.0
    httpPort: 9094
