// Code generated by servicegen. DO NOT EDIT.
import { NodeHttpDataSource, makeNodeHttpEndpointConsumer as makeNodeHttpSourceEndpointConsumer } from "@gorundebug/tsservicelib/datasource/http";
import { makeKafkaEndpointConsumer as makeKafkaSinkEndpointConsumer } from "@gorundebug/tsservicelib/datasink/kafka";
import {
  GrpcJsDataSink,
  makeGrpcNoStreamingEndpointConsumer as makeGrpcNoStreamingSinkEndpointConsumer,
} from "@gorundebug/tsservicelib/datasink/grpc";
import { InventoryServiceApi } from "@gorundebug/inventory-service-api";
import type { ServiceClients } from "./clients.generated.js";
import type { ServiceFunctions } from "./functions.generated.js";
import type { ServiceStreams } from "./streams.generated.js";

function initDataConnectors(
  streams: ServiceStreams,
  functions: ServiceFunctions,
  clients: ServiceClients,
) {
  const [processOrder, processOrderHandler] = makeNodeHttpSourceEndpointConsumer(streams.processOrder, functions.processOrderSource);
  const processOrderItem = makeGrpcNoStreamingSinkEndpointConsumer(streams.processOrderItem, InventoryServiceApi, InventoryServiceApi.method.processOrderItem, functions.processOrderItemSink);
  const publishOrderProcessed = makeKafkaSinkEndpointConsumer(streams.publishOrderProcessed, functions.orderProcessedEndpointSink);
  return {
    dataConnectors: {
      processOrder,
      processOrderItem,
      publishOrderProcessed,
    },
    handlers: {
      processOrder: processOrderHandler,
    },
  };
}

export type ServiceDataConnectors = ReturnType<typeof initDataConnectors>["dataConnectors"];
export type ServiceHandlers = ReturnType<typeof initDataConnectors>["handlers"];


export class ServiceEndpoints {
  public dataConnectors!: ServiceDataConnectors;
  public handlers!: ServiceHandlers;

  public bind(streams: ServiceStreams, functions: ServiceFunctions, clients: ServiceClients) {
    const bindings = initDataConnectors(streams, functions, clients);
    this.dataConnectors = bindings.dataConnectors;
    this.handlers = bindings.handlers;
    return bindings;
  }
}
