// Code generated by servicegen. DO NOT EDIT.

import type { MessageContext, RuntimeEnvironment } from "@gorundebug/tsservicelib/runtime/graph";
import type { ConfigSnapshot } from "../config/config-snapshot.generated.js";
import type { ServiceMakers } from "./makers.generated.js";
import type {
  OrderProcessedEndpointSink,
  ProcessOrderItemSink,
  ProcessOrderSource,
  MapOrderItemResultToOrderState,
  MapToOrderProcessed,
  MapToOrderState,
  ProcessOrderItems,
  SoftDeadline,
} from "../functions/index.generated.js";

export class ServiceFunctions {
  public orderProcessedEndpointSink!: OrderProcessedEndpointSink;
  public processOrderItemSink!: ProcessOrderItemSink;
  public processOrderSource!: ProcessOrderSource;
  public mapOrderItemResultToOrderState!: MapOrderItemResultToOrderState;
  public mapToOrderProcessed!: MapToOrderProcessed;
  public mapToOrderState!: MapToOrderState;
  public processOrderItems!: ProcessOrderItems;
  public softDeadline!: SoftDeadline;
}

export async function initFunctions(
  context: MessageContext,
  _config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  makers: ServiceMakers,
): Promise<ServiceFunctions> {
  const functions = new ServiceFunctions();
  {
    const controller = new AbortController();
    const makerContext = context.withExternalCancellation(controller.signal);
    let firstError: unknown;
    let failed = false;
    const invokeMaker = async <T>(maker: () => Promise<T>): Promise<T> => {
      try {
        return await maker();
      } catch (error) {
        if (!failed) {
          failed = true;
          firstError = error;
          controller.abort(error);
        }
        throw error;
      }
    };
    const group = await Promise.allSettled([
      invokeMaker(async () => {
        functions.orderProcessedEndpointSink = await makers.orderProcessedEndpointSink(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.processOrderItemSink = await makers.processOrderItemSink(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.processOrderSource = await makers.processOrderSource(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.mapOrderItemResultToOrderState = await makers.mapOrderItemResultToOrderState(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.mapToOrderProcessed = await makers.mapToOrderProcessed(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.mapToOrderState = await makers.mapToOrderState(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.processOrderItems = await makers.processOrderItems(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.softDeadline = await makers.softDeadline(makerContext, environment);
      }),
    ]);
    controller.abort();
    if (failed) throw firstError;
    for (const result of group) {
      if (result.status === "rejected") throw result.reason;
    }
  }
  return functions;
}

export async function initFunctionsParallel(
  context: MessageContext,
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  makers: ServiceMakers,
): Promise<ServiceFunctions> {
  return initFunctions(context, config, environment, makers);
}
