// Code generated by servicegen. DO NOT EDIT.

import { MessageContext, ServiceEnvironment, ServiceHTTPServer, type ServiceConfig } from "@gorundebug/tsservicelib/runtime";
import type { Config } from "../config/config.js";
import { NodeHttpDataSource, makeNodeHttpEndpointConsumer as makeNodeHttpSourceEndpointConsumer } from "@gorundebug/tsservicelib/datasource/http";
import { makeKafkaEndpointConsumer as makeKafkaSinkEndpointConsumer } from "@gorundebug/tsservicelib/datasink/kafka";
import {
  GrpcJsDataSink,
  makeGrpcNoStreamingEndpointConsumer as makeGrpcNoStreamingSinkEndpointConsumer,
} from "@gorundebug/tsservicelib/datasink/grpc";
import { InventoryServiceApi } from "@gorundebug/inventory-service-api";
import { ServiceClients } from "./clients.generated.js";
import { ServiceServers } from "./servers.generated.js";
import { ServiceConnectors } from "./connectors.generated.js";
export interface ServiceInfrastructureMakers {
  serviceHttpServer: (
    context: MessageContext,
    environment: ServiceEnvironment,
    config: ServiceConfig,
  ) => Promise<ServiceHTTPServer>;
  orderServiceApiHttpDataSource: (
    context: MessageContext,
    environment: ServiceEnvironment,
    config: Config["named"]["dataConnectors"]["orderServiceApi"],
  ) => Promise<NodeHttpDataSource>;
  inventoryServiceApiGrpcDataSink: (
    context: MessageContext,
    environment: ServiceEnvironment,
    config: Config["named"]["dataConnectors"]["inventoryServiceApi"],
  ) => Promise<GrpcJsDataSink>;
}

export function defaultInfrastructureMakers(): ServiceInfrastructureMakers {
  return {
    serviceHttpServer: async (_context, environment, _config) =>
      new ServiceHTTPServer(() => environment.serviceConfig()),
    orderServiceApiHttpDataSource: async (_context, environment, config) =>
      new NodeHttpDataSource(config.id, environment),
    inventoryServiceApiGrpcDataSink: async (_context, environment, config) =>
      new GrpcJsDataSink(config.id, environment, InventoryServiceApi),
  };
}


export async function initInfrastructure(
  context: MessageContext,
  config: Config,
  environment: ServiceEnvironment,
  makers: ServiceInfrastructureMakers,
  servers: ServiceServers,
  clients: ServiceClients,
  connectors: ServiceConnectors,
): Promise<void> {
  const controller = new AbortController();
  const makerContext = context.withExternalCancellation(controller.signal);
  let firstError: unknown;
  let failed = false;
  const invokeMaker = async <T>(maker: () => Promise<T>): Promise<T> => {
    try {
      return await maker();
    } catch (error) {
      if (!failed) {
        failed = true;
        firstError = error;
        controller.abort(error);
      }
      throw error;
    }
  };
  await Promise.allSettled([
    ...servers.makerCalls(makerContext, config, environment, makers, invokeMaker),
    ...clients.makerCalls(makerContext, config, environment, makers, invokeMaker),
    ...connectors.makerCalls(makerContext, config, environment, makers, invokeMaker),
  ]);
  controller.abort();
  if (failed) throw firstError;
  servers.bind(environment);
  connectors.bind(environment);
}
