// Code generated by servicegen. DO NOT EDIT.

import type { MessageContext, RuntimeEnvironment } from "@gorundebug/tsservicelib/runtime/graph";
import {
  makeOrderProcessedEndpointSink,
  makeProcessOrderItemSink,
  makeProcessOrderSource,
  makeMapOrderItemResultToOrderState,
  makeMapToOrderProcessed,
  makeMapToOrderState,
  makeProcessOrderItems,
  makeSoftDeadline,
} from "../functions/index.generated.js";
import type {
  OrderProcessedEndpointSink,
  ProcessOrderItemSink,
  ProcessOrderSource,
  MapOrderItemResultToOrderState,
  MapToOrderProcessed,
  MapToOrderState,
  ProcessOrderItems,
  SoftDeadline,
} from "../functions/index.generated.js";

export class ServiceMakers {
  public orderProcessedEndpointSink: (context: MessageContext, environment: RuntimeEnvironment) => Promise<OrderProcessedEndpointSink> = makeOrderProcessedEndpointSink;
  public processOrderItemSink: (context: MessageContext, environment: RuntimeEnvironment) => Promise<ProcessOrderItemSink> = makeProcessOrderItemSink;
  public processOrderSource: (context: MessageContext, environment: RuntimeEnvironment) => Promise<ProcessOrderSource> = makeProcessOrderSource;
  public mapOrderItemResultToOrderState: (context: MessageContext, environment: RuntimeEnvironment) => Promise<MapOrderItemResultToOrderState> = makeMapOrderItemResultToOrderState;
  public mapToOrderProcessed: (context: MessageContext, environment: RuntimeEnvironment) => Promise<MapToOrderProcessed> = makeMapToOrderProcessed;
  public mapToOrderState: (context: MessageContext, environment: RuntimeEnvironment) => Promise<MapToOrderState> = makeMapToOrderState;
  public processOrderItems: (context: MessageContext, environment: RuntimeEnvironment) => Promise<ProcessOrderItems> = makeProcessOrderItems;
  public softDeadline: (context: MessageContext, environment: RuntimeEnvironment) => Promise<SoftDeadline> = makeSoftDeadline;

  public static async initMakers(context: MessageContext, customize: (context: MessageContext) => void | Promise<void>): Promise<void> {
    await customize(context);
  }
}

export type WorkflowServiceMakers = ServiceMakers;
export function defaultMakers(): ServiceMakers { return new ServiceMakers(); }
export function defaultWorkflowMakers(): WorkflowServiceMakers { return new ServiceMakers(); }
