// Code generated by servicegen. DO NOT EDIT.

import type { MessageContext, RuntimeEnvironment } from "@gorundebug/tsservicelib/runtime/graph";
import {
  makeCaseStream, makeDelayStream, makeFilterStream, makeFlatMapIterableStream,
  makeFlatMapStream, makeInputStream, makeJoinStream, makeKeyByStream,
  makeLinkStream, makeMapStream, makeMergeStream, makeMultiJoinLink,
  makeMultiJoinStream, makeProcessStream, makeSinkStream,
  makeSinkStreamWithResult, makeSplitStream, makeSubStream, makeWhenStream,
} from "@gorundebug/tsservicelib/operators";
import type { Order, OrderState } from "../types/index.generated.js";
import type { OrderItem, OrderItemResult, OrderProcessed } from "@gorundebug/model";
import type { ConfigSnapshot } from "../config/config-snapshot.generated.js";
import type { ServiceFunctions, ServiceStreams } from "./graph.generated.js";
import {
  makeOrderProcessedEndpointSink,
  makeProcessOrderItemSink,
  makeProcessOrderSource,
  makeMapOrderItemResultToOrderState,
  makeMapToOrderProcessed,
  makeMapToOrderState,
  makeProcessOrderItems,
  makeSoftDeadline,
} from "../functions/index.generated.js";
import type {
  OrderProcessedEndpointSink,
  ProcessOrderItemSink,
  ProcessOrderSource,
  MapOrderItemResultToOrderState,
  MapToOrderProcessed,
  MapToOrderState,
  ProcessOrderItems,
  SoftDeadline,
} from "../functions/index.generated.js";

export interface OrderPipelineMakers {
  orderProcessedEndpointSink: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").KafkaEndpointConfig,
  ) => Promise<OrderProcessedEndpointSink>;
  processOrderItemSink: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").GrpcEndpointConfig,
  ) => Promise<ProcessOrderItemSink>;
  processOrderSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").HttpEndpointConfig,
  ) => Promise<ProcessOrderSource>;
  mapOrderItemResultToOrderState: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => Promise<MapOrderItemResultToOrderState>;
  mapToOrderProcessed: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => Promise<MapToOrderProcessed>;
  mapToOrderState: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => Promise<MapToOrderState>;
  processOrderItems: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").FlatMapStreamConfig,
  ) => Promise<ProcessOrderItems>;
  softDeadline: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").DelayStreamConfig,
  ) => Promise<SoftDeadline>;
}

export function defaultOrderPipelineMakers(): OrderPipelineMakers {
  return {
    orderProcessedEndpointSink: makeOrderProcessedEndpointSink,
    processOrderItemSink: makeProcessOrderItemSink,
    processOrderSource: makeProcessOrderSource,
    mapOrderItemResultToOrderState: makeMapOrderItemResultToOrderState,
    mapToOrderProcessed: makeMapToOrderProcessed,
    mapToOrderState: makeMapToOrderState,
    processOrderItems: makeProcessOrderItems,
    softDeadline: makeSoftDeadline,
  };
}

export interface OrderPipelineFunctions {
  orderProcessedEndpointSink: OrderProcessedEndpointSink;
  processOrderItemSink: ProcessOrderItemSink;
  processOrderSource: ProcessOrderSource;
  mapOrderItemResultToOrderState: MapOrderItemResultToOrderState;
  mapToOrderProcessed: MapToOrderProcessed;
  mapToOrderState: MapToOrderState;
  processOrderItems: ProcessOrderItems;
  softDeadline: SoftDeadline;
}

export interface OrderPipelineStreams {
  processOrder: ReturnType<typeof initOrderProcessOrderStream>;
  splitPipeline: ReturnType<typeof initOrderSplitPipelineStream>;
  processOrderItems: ReturnType<typeof initOrderProcessOrderItemsStream>;
  processOrderItem: ReturnType<typeof initOrderProcessOrderItemStream>["stream"];
  processOrderItemError: ReturnType<typeof initOrderProcessOrderItemStream>["errorStream"];
  mapOrderItemResultToOrderState: ReturnType<typeof initOrderMapOrderItemResultToOrderStateStream>;
  softDeadline: ReturnType<typeof initOrderSoftDeadlineStream>;
  mapToOrderState: ReturnType<typeof initOrderMapToOrderStateStream>;
  mergeResults: ReturnType<typeof initOrderMergeResultsStream>;
  splitOrderResult: ReturnType<typeof initOrderSplitOrderResultStream>;
  mapToOrderProcessed: ReturnType<typeof initOrderMapToOrderProcessedStream>;
  publishOrderProcessed: ReturnType<typeof initOrderPublishOrderProcessedStream>;
}

export function initOrderPipelineStreams(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  streams: ServiceStreams,
): void {
  const initializedProcessOrder = initOrderProcessOrderStream(
    config,
    environment,
    functions,
    undefined,
    undefined,
    [],
  );
  streams.processOrder = initializedProcessOrder;
  const initializedSplitPipeline = initOrderSplitPipelineStream(
    config,
    environment,
    functions,
    streams.processOrder,
    undefined,
    [],
  );
  streams.splitPipeline = initializedSplitPipeline;
  const initializedProcessOrderItems = initOrderProcessOrderItemsStream(
    config,
    environment,
    functions,
    streams.splitPipeline.addStream(),
    undefined,
    [],
  );
  streams.processOrderItems = initializedProcessOrderItems;
  const initializedProcessOrderItem = initOrderProcessOrderItemStream(
    config,
    environment,
    functions,
    streams.processOrderItems,
    undefined,
    [],
  );
  streams.processOrderItem = initializedProcessOrderItem.stream;
  streams.processOrderItemError = initializedProcessOrderItem.errorStream;
  const initializedMapOrderItemResultToOrderState = initOrderMapOrderItemResultToOrderStateStream(
    config,
    environment,
    functions,
    streams.processOrderItem,
    undefined,
    [],
  );
  streams.mapOrderItemResultToOrderState = initializedMapOrderItemResultToOrderState;
  const initializedSoftDeadline = initOrderSoftDeadlineStream(
    config,
    environment,
    functions,
    streams.splitPipeline.addStream(),
    undefined,
    [],
  );
  streams.softDeadline = initializedSoftDeadline;
  const initializedMapToOrderState = initOrderMapToOrderStateStream(
    config,
    environment,
    functions,
    streams.softDeadline,
    undefined,
    [],
  );
  streams.mapToOrderState = initializedMapToOrderState;
  const initializedMergeResults = initOrderMergeResultsStream(
    config,
    environment,
    functions,
    undefined,
    undefined,
    [streams.mapToOrderState, streams.mapOrderItemResultToOrderState, streams.processOrderItemError],
  );
  streams.mergeResults = initializedMergeResults;
  const initializedSplitOrderResult = initOrderSplitOrderResultStream(
    config,
    environment,
    functions,
    streams.mergeResults,
    undefined,
    [],
  );
  streams.splitOrderResult = initializedSplitOrderResult;
  const initializedMapToOrderProcessed = initOrderMapToOrderProcessedStream(
    config,
    environment,
    functions,
    streams.splitOrderResult.addStream(),
    undefined,
    [],
  );
  streams.mapToOrderProcessed = initializedMapToOrderProcessed;
  const initializedPublishOrderProcessed = initOrderPublishOrderProcessedStream(
    config,
    environment,
    functions,
    streams.mapToOrderProcessed,
    undefined,
    [],
  );
  streams.publishOrderProcessed = initializedPublishOrderProcessed;
}

export function postInitOrderPipelineStreams(streams: ServiceStreams): void {
  bindOrderProcessOrderStream(
    streams.processOrder,
    streams.splitOrderResult.addStream(),
  );
}
export function initOrderProcessOrderStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<Order, OrderState, Error>(config.named.streams.processOrder, environment);
  return stream;
}
export function initOrderSplitPipelineStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSplitStream<Order>(config.named.streams.splitPipeline, source as never);
  return stream;
}
export function initOrderProcessOrderItemsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeFlatMapStream<Order, OrderItem>(config.named.streams.processOrderItems, source as never, functions.processOrderItems);
  return stream;
}
export function initOrderProcessOrderItemStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStreamWithResult<OrderItem, OrderItemResult, OrderState>(config.named.streams.processOrderItem, source as never);
  return { stream, errorStream: stream.errorStream() };
}
export function initOrderMapOrderItemResultToOrderStateStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<OrderItemResult, OrderState>(config.named.streams.mapOrderItemResultToOrderState, source as never, functions.mapOrderItemResultToOrderState);
  return stream;
}
export function initOrderSoftDeadlineStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeDelayStream<Order>(config.named.streams.softDeadline, source as never, functions.softDeadline);
  return stream;
}
export function initOrderMapToOrderStateStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<Order, OrderState>(config.named.streams.mapToOrderState, source as never, functions.mapToOrderState);
  return stream;
}
export function initOrderMergeResultsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMergeStream<OrderState>(config.named.streams.mergeResults, sources[0] as never, sources[1] as never, sources[2] as never);
  return stream;
}
export function initOrderSplitOrderResultStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSplitStream<OrderState>(config.named.streams.splitOrderResult, source as never);
  return stream;
}
export function initOrderMapToOrderProcessedStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<OrderState, OrderProcessed>(config.named.streams.mapToOrderProcessed, source as never, functions.mapToOrderProcessed);
  return stream;
}
export function initOrderPublishOrderProcessedStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStream<OrderProcessed, Error>(config.named.streams.publishOrderProcessed, source as never);
  return stream;
}
export function bindOrderProcessOrderStream<T>(stream: { setSource(source: T): void }, source: T): void {
  stream.setSource(source);
}
