// Code generated by servicegen. DO NOT EDIT.

import { MessageContext, ServiceEnvironment, ServiceHTTPServer, type ServiceConfig } from "@gorundebug/tsservicelib/runtime";
import type { Config } from "../config/config.js";
import type { ServiceInfrastructureMakers } from "./infrastructure-makers.generated.js";

export class ServiceClients {
  public makerCalls(context: MessageContext, config: Config, environment: ServiceEnvironment,
    makers: ServiceInfrastructureMakers, invokeMaker: <T>(maker: () => Promise<T>) => Promise<T>): Promise<void>[] {
    return [
    ];
  }
}
