// Code generated by servicegen. DO NOT EDIT.
import { makeKafkaEndpointConsumer as makeKafkaSourceEndpointConsumer } from "@gorundebug/tsservicelib/datasource/kafka";
import { makeCustomEndpointConsumer as makeCustomSourceEndpointConsumer } from "@gorundebug/tsservicelib/datasource/localsource";
import { makeCustomEndpointConsumer as makeCustomSinkEndpointConsumer } from "@gorundebug/tsservicelib/datasink/localsink";
import { makeCronEndpointConsumer } from "@gorundebug/tsservicelib/datasource/cron";
import type { ServiceClients } from "./clients.generated.js";
import type { ServiceFunctions } from "./functions.generated.js";
import type { ServiceStreams } from "./streams.generated.js";

function initDataConnectors(
  streams: ServiceStreams,
  functions: ServiceFunctions,
  clients: ServiceClients,
) {
  const analyticsSchedule = makeCronEndpointConsumer(streams.analyticsSchedule, functions.analyticsScheduleSource);
  const consumeOrderProcessed = makeKafkaSourceEndpointConsumer(streams.consumeOrderProcessed, functions.orderProcessedEndpointSource);
  const analyticsOrders = makeCustomSourceEndpointConsumer(streams.analyticsOrders, functions.analyticsOrdersSource, functions.analyticsOrdersSource);
  const analyticsPayments = makeCustomSourceEndpointConsumer(streams.analyticsPayments, functions.analyticsPaymentsSource, functions.analyticsPaymentsSource);
  const analyticsShipments = makeCustomSourceEndpointConsumer(streams.analyticsShipments, functions.analyticsShipmentsSource, functions.analyticsShipmentsSource);
  const cycleAnalyticsInput = makeCustomSourceEndpointConsumer(streams.cycleAnalyticsInput, functions.cycleAnalyticsInputSource, functions.cycleAnalyticsInputSource);
  const writeCycleAnalytics = makeCustomSinkEndpointConsumer(streams.writeCycleAnalytics, functions.cycleAnalyticsResultSink);
  const writeJoinedAnalytics = makeCustomSinkEndpointConsumer(streams.writeJoinedAnalytics, functions.joinedAnalyticsSink);
  const writeHighValueAnalytics = makeCustomSinkEndpointConsumer(streams.writeHighValueAnalytics, functions.highValueAnalyticsSink);
  const writeStandardAnalytics = makeCustomSinkEndpointConsumer(streams.writeStandardAnalytics, functions.standardAnalyticsSink);
  const substreamAnalyticsInput = makeCustomSourceEndpointConsumer(streams.substreamAnalyticsInput, functions.substreamAnalyticsInputSource, functions.substreamAnalyticsInputSource);
  const writeSubstreamAnalytics = makeCustomSinkEndpointConsumer(streams.writeSubstreamAnalytics, functions.substreamAnalyticsResultSink);
  return {
    dataConnectors: {
      analyticsSchedule,
      consumeOrderProcessed,
      analyticsOrders,
      analyticsPayments,
      analyticsShipments,
      cycleAnalyticsInput,
      writeCycleAnalytics,
      writeJoinedAnalytics,
      writeHighValueAnalytics,
      writeStandardAnalytics,
      substreamAnalyticsInput,
      writeSubstreamAnalytics,
    },
    handlers: {
    },
  };
}

export type ServiceDataConnectors = ReturnType<typeof initDataConnectors>["dataConnectors"];
export type ServiceHandlers = ReturnType<typeof initDataConnectors>["handlers"];


export class ServiceEndpoints {
  public dataConnectors!: ServiceDataConnectors;
  public handlers!: ServiceHandlers;

  public bind(streams: ServiceStreams, functions: ServiceFunctions, clients: ServiceClients) {
    const bindings = initDataConnectors(streams, functions, clients);
    this.dataConnectors = bindings.dataConnectors;
    this.handlers = bindings.handlers;
    return bindings;
  }
}
