// Code generated by servicegen. DO NOT EDIT.

import type { MessageContext, RuntimeEnvironment } from "@gorundebug/tsservicelib/runtime/graph";
import type { ConfigSnapshot } from "../config/config-snapshot.generated.js";
import type { ServiceMakers } from "./makers.generated.js";
import type {
  CountOrderProcessed,
  AnalyticsScheduleSource,
  AdvanceCycleAnalytics,
  CompleteCycleAnalytics,
  ContinueCycleAnalytics,
  AnalyticsOrdersSource,
  AnalyticsPaymentsSource,
  AnalyticsShipmentsSource,
  CycleAnalyticsInputSource,
  CycleAnalyticsResultSink,
  HighValueAnalyticsSink,
  JoinedAnalyticsSink,
  OrderProcessedEndpointSource,
  StandardAnalyticsSink,
  SubstreamAnalyticsInputSource,
  SubstreamAnalyticsResultSink,
  JoinOrderPaymentAnalytics,
  KeyOrdersForJoin,
  KeyPaymentsForJoin,
  KeyOrdersForMultiJoin,
  KeyPaymentsForMultiJoin,
  KeyShipmentsForMultiJoin,
  MultiJoinAnalyticsEvents,
  RouteAnalyticsResult,
  BuildSubstreamAnalyticsResult,
  InvokeAnalyticsSubstream,
} from "../functions/index.generated.js";

export class ServiceFunctions {
  public countOrderProcessed!: CountOrderProcessed;
  public analyticsScheduleSource!: AnalyticsScheduleSource;
  public advanceCycleAnalytics!: AdvanceCycleAnalytics;
  public completeCycleAnalytics!: CompleteCycleAnalytics;
  public continueCycleAnalytics!: ContinueCycleAnalytics;
  public analyticsOrdersSource!: AnalyticsOrdersSource;
  public analyticsPaymentsSource!: AnalyticsPaymentsSource;
  public analyticsShipmentsSource!: AnalyticsShipmentsSource;
  public cycleAnalyticsInputSource!: CycleAnalyticsInputSource;
  public cycleAnalyticsResultSink!: CycleAnalyticsResultSink;
  public highValueAnalyticsSink!: HighValueAnalyticsSink;
  public joinedAnalyticsSink!: JoinedAnalyticsSink;
  public orderProcessedEndpointSource!: OrderProcessedEndpointSource;
  public standardAnalyticsSink!: StandardAnalyticsSink;
  public substreamAnalyticsInputSource!: SubstreamAnalyticsInputSource;
  public substreamAnalyticsResultSink!: SubstreamAnalyticsResultSink;
  public joinOrderPaymentAnalytics!: JoinOrderPaymentAnalytics;
  public keyOrdersForJoin!: KeyOrdersForJoin;
  public keyPaymentsForJoin!: KeyPaymentsForJoin;
  public keyOrdersForMultiJoin!: KeyOrdersForMultiJoin;
  public keyPaymentsForMultiJoin!: KeyPaymentsForMultiJoin;
  public keyShipmentsForMultiJoin!: KeyShipmentsForMultiJoin;
  public multiJoinAnalyticsEvents!: MultiJoinAnalyticsEvents;
  public routeAnalyticsResult!: RouteAnalyticsResult;
  public buildSubstreamAnalyticsResult!: BuildSubstreamAnalyticsResult;
  public invokeAnalyticsSubstream!: InvokeAnalyticsSubstream;
}

export async function initFunctions(
  context: MessageContext,
  _config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  makers: ServiceMakers,
): Promise<ServiceFunctions> {
  const functions = new ServiceFunctions();
  {
    const controller = new AbortController();
    const makerContext = context.withExternalCancellation(controller.signal);
    let firstError: unknown;
    let failed = false;
    const invokeMaker = async <T>(maker: () => Promise<T>): Promise<T> => {
      try {
        return await maker();
      } catch (error) {
        if (!failed) {
          failed = true;
          firstError = error;
          controller.abort(error);
        }
        throw error;
      }
    };
    const group = await Promise.allSettled([
      invokeMaker(async () => {
        functions.countOrderProcessed = await makers.countOrderProcessed(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.analyticsScheduleSource = await makers.analyticsScheduleSource(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.advanceCycleAnalytics = await makers.advanceCycleAnalytics(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.completeCycleAnalytics = await makers.completeCycleAnalytics(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.continueCycleAnalytics = await makers.continueCycleAnalytics(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.analyticsOrdersSource = await makers.analyticsOrdersSource(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.analyticsPaymentsSource = await makers.analyticsPaymentsSource(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.analyticsShipmentsSource = await makers.analyticsShipmentsSource(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.cycleAnalyticsInputSource = await makers.cycleAnalyticsInputSource(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.cycleAnalyticsResultSink = await makers.cycleAnalyticsResultSink(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.highValueAnalyticsSink = await makers.highValueAnalyticsSink(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.joinedAnalyticsSink = await makers.joinedAnalyticsSink(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.orderProcessedEndpointSource = await makers.orderProcessedEndpointSource(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.standardAnalyticsSink = await makers.standardAnalyticsSink(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.substreamAnalyticsInputSource = await makers.substreamAnalyticsInputSource(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.substreamAnalyticsResultSink = await makers.substreamAnalyticsResultSink(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.joinOrderPaymentAnalytics = await makers.joinOrderPaymentAnalytics(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.keyOrdersForJoin = await makers.keyOrdersForJoin(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.keyPaymentsForJoin = await makers.keyPaymentsForJoin(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.keyOrdersForMultiJoin = await makers.keyOrdersForMultiJoin(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.keyPaymentsForMultiJoin = await makers.keyPaymentsForMultiJoin(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.keyShipmentsForMultiJoin = await makers.keyShipmentsForMultiJoin(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.multiJoinAnalyticsEvents = await makers.multiJoinAnalyticsEvents(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.routeAnalyticsResult = await makers.routeAnalyticsResult(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.buildSubstreamAnalyticsResult = await makers.buildSubstreamAnalyticsResult(makerContext, environment);
      }),
      invokeMaker(async () => {
        functions.invokeAnalyticsSubstream = await makers.invokeAnalyticsSubstream(makerContext, environment);
      }),
    ]);
    controller.abort();
    if (failed) throw firstError;
    for (const result of group) {
      if (result.status === "rejected") throw result.reason;
    }
  }
  return functions;
}

export async function initFunctionsParallel(
  context: MessageContext,
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  makers: ServiceMakers,
): Promise<ServiceFunctions> {
  return initFunctions(context, config, environment, makers);
}
