// Code generated by servicegen. DO NOT EDIT.

import {
  JsonSerde, MessageContext, SerdeRegistry, SerdeType,
  type RuntimeEnvironment,
  boolSerdeType, bytesSerdeType, errorSerdeType,
  float32SerdeType, float64SerdeType,
  int8SerdeType, int16SerdeType, int32SerdeType, int64SerdeType, intSerdeType,
  makeStreamSerde, runeSerdeType,
  stringSerdeType,
  uint8SerdeType, uint16SerdeType, uint32SerdeType, uint64SerdeType, uintSerdeType,
} from "@gorundebug/tsservicelib/runtime/graph";
import {
  makeCaseStream, makeDelayStream, makeFilterStream, makeFlatMapIterableStream,
  makeFlatMapStream, makeInputStream, makeJoinStream, makeKeyByStream,
  makeLinkStream, makeMapStream, makeMergeStream, makeMultiJoinLink,
  makeMultiJoinStream, makeProcessStream, makeSinkStream,
  makeSinkStreamWithResult, makeSplitStream, makeWhenStream,
} from "@gorundebug/tsservicelib/operators";
import type { AutomationJob, OrderProcessed } from "@gorundebug/model";
import {
  StreamIds,
  type ConfigSnapshot,
} from "../config/config-snapshot.generated.js";
import {
  CountOrderProcessed, makeCountOrderProcessed,
  AnalyticsScheduleSource, makeAnalyticsScheduleSource,
  OrderProcessedEndpointSource, makeOrderProcessedEndpointSource,
} from "../functions/index.generated.js";

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const serdeTypes = {
  automationJob: new SerdeType<AutomationJob>("AutomationJob", (value): value is AutomationJob => typeof value === "string"),
  orderProcessed: new SerdeType<OrderProcessed>("OrderProcessed", (value): value is OrderProcessed => isRecord(value)),
} as const;

export function registerGeneratedSerdes(registry: SerdeRegistry): void {
  registry.register(serdeTypes.automationJob, registry.require(stringSerdeType));
  registry.register(serdeTypes.orderProcessed, makeStreamSerde(new JsonSerde(serdeTypes.orderProcessed)));
  registry.registerStreamValueType(StreamIds.ANALYTICS_SCHEDULE, serdeTypes.automationJob);
  registry.registerStreamErrorType(StreamIds.ANALYTICS_SCHEDULE, errorSerdeType);
  registry.registerStreamValueType(StreamIds.CONSUME_ORDER_PROCESSED, serdeTypes.orderProcessed);
  registry.registerStreamErrorType(StreamIds.CONSUME_ORDER_PROCESSED, errorSerdeType);
  registry.registerStreamValueType(StreamIds.COUNT_ORDER_PROCESSED, serdeTypes.orderProcessed);
  registry.registerStreamErrorType(StreamIds.COUNT_ORDER_PROCESSED, errorSerdeType);
}

export interface ServiceMakers {
  countOrderProcessed: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").ProcessStreamConfig,
  ) => CountOrderProcessed;
  analyticsScheduleSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").CronEndpointConfig,
  ) => AnalyticsScheduleSource;
  orderProcessedEndpointSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").KafkaEndpointConfig,
  ) => OrderProcessedEndpointSource;
}

export function defaultMakers(): ServiceMakers {
  return {
    countOrderProcessed: makeCountOrderProcessed,
    analyticsScheduleSource: makeAnalyticsScheduleSource,
    orderProcessedEndpointSource: makeOrderProcessedEndpointSource,
  };
}

export function initFunctions(
  context: MessageContext,
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  makers: ServiceMakers,
) {
  return {
    countOrderProcessed: makers.countOrderProcessed(context, environment, config.named.streams.countOrderProcessed),
    analyticsScheduleSource: makers.analyticsScheduleSource(context, environment, config.named.endpoints.analyticsSchedule),
    orderProcessedEndpointSource: makers.orderProcessedEndpointSource(context, environment, config.named.endpoints.orderProcessed),
  };
}

export type ServiceFunctions = ReturnType<typeof initFunctions>;

export function initStreams(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
) {
  const analyticsSchedule = makeInputStream<string, unknown, Error>(config.named.streams.analyticsSchedule, environment);
  const consumeOrderProcessed = makeInputStream<OrderProcessed, OrderProcessed, Error>(config.named.streams.consumeOrderProcessed, environment);
  const countOrderProcessed = makeProcessStream<OrderProcessed, OrderProcessed, Error>(config.named.streams.countOrderProcessed, consumeOrderProcessed, functions.countOrderProcessed);
  consumeOrderProcessed.setSource(countOrderProcessed);
  return {
    analyticsSchedule,
    consumeOrderProcessed,
    countOrderProcessed,
  };
}

export type ServiceStreams = ReturnType<typeof initStreams>;
