// Code generated by servicegen. DO NOT EDIT.

import { MessageContext, ServiceEnvironment, ServiceHTTPServer, type ServiceConfig } from "@gorundebug/tsservicelib/runtime";
import { makeKafkaEndpointConsumer as makeKafkaSourceEndpointConsumer } from "@gorundebug/tsservicelib/datasource/kafka";
import { makeCustomEndpointConsumer as makeCustomSourceEndpointConsumer } from "@gorundebug/tsservicelib/datasource/localsource";
import { makeCustomEndpointConsumer as makeCustomSinkEndpointConsumer } from "@gorundebug/tsservicelib/datasink/localsink";
import { makeCronEndpointConsumer } from "@gorundebug/tsservicelib/datasource/cron";

import type { Config } from "../config/config.js";
import { ServiceClients } from "./clients.generated.js";
import { ServiceServers } from "./servers.generated.js";
import { ServiceConnectors } from "./connectors.generated.js";
export interface ServiceInfrastructureMakers {
  serviceHttpServer: (
    context: MessageContext,
    environment: ServiceEnvironment,
    config: ServiceConfig,
  ) => Promise<ServiceHTTPServer>;
}

// Preserve synchronous construction and convert constructor failures to rejections.
function construct<T>(factory: () => T): Promise<T> {
  return new Promise((resolve) => {
    resolve(factory());
  });
}

export function defaultInfrastructureMakers(): ServiceInfrastructureMakers {
  return {
    serviceHttpServer: (_context, environment, _config) =>
      construct(() => new ServiceHTTPServer(() => environment.serviceConfig())),
  };
}


export async function initInfrastructure(
  context: MessageContext,
  config: Config,
  environment: ServiceEnvironment,
  makers: ServiceInfrastructureMakers,
  servers: ServiceServers,
  clients: ServiceClients,
  connectors: ServiceConnectors,
): Promise<void> {
  const controller = new AbortController();
  const makerContext = context.withExternalCancellation(controller.signal);
  const failure: { failed: boolean; error?: unknown } = { failed: false };
  const invokeMaker = async <T>(maker: () => Promise<T>): Promise<T> => {
    try {
      return await maker();
    } catch (error) {
      if (!failure.failed) {
        failure.failed = true;
        failure.error = error;
        controller.abort(error);
      }
      throw error;
    }
  };
  await Promise.allSettled([
    ...servers.makerCalls(makerContext, config, environment, makers, invokeMaker),
    ...clients.makerCalls(makerContext, config, environment, makers, invokeMaker),
    ...connectors.makerCalls(makerContext, config, environment, makers, invokeMaker),
  ]);
  controller.abort();
  if (failure.failed) throw failure.error;
  servers.bind(environment);
  connectors.bind(environment);
}
