// Code generated by servicegen. DO NOT EDIT.

import type { MessageContext, RuntimeEnvironment } from "@gorundebug/tsservicelib/runtime/graph";
import {
  makeCaseStream, makeDelayStream, makeFilterStream, makeFlatMapIterableStream,
  makeFlatMapStream, makeInputStream, makeJoinStream, makeKeyByStream,
  makeLinkStream, makeMapStream, makeMergeStream, makeMultiJoinLink,
  makeMultiJoinStream, makeProcessStream, makeSinkStream,
  makeSinkStreamWithResult, makeSplitStream, makeSubStream, makeWhenStream,
} from "@gorundebug/tsservicelib/operators";
import type { AnalyticsEvent, AnalyticsKey, AnalyticsResult } from "../types/index.generated.js";
import type { AutomationJob, OrderProcessed } from "@gorundebug/model";
import type { ConfigSnapshot } from "../config/config-snapshot.generated.js";
import type { ServiceFunctions, ServiceStreams } from "./graph.generated.js";
import {
  makeJoinedAnalyticsSink,
  makeJoinOrderPaymentAnalytics,
  makeKeyOrdersForJoin,
  makeKeyPaymentsForJoin,
} from "../functions/index.generated.js";
import type {
  JoinedAnalyticsSink,
  JoinOrderPaymentAnalytics,
  KeyOrdersForJoin,
  KeyPaymentsForJoin,
} from "../functions/index.generated.js";

export interface JoinAnalyticsPipelineMakers {
  joinedAnalyticsSink: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").CustomEndpointConfig,
  ) => Promise<JoinedAnalyticsSink>;
  joinOrderPaymentAnalytics: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").JoinStreamConfig,
  ) => Promise<JoinOrderPaymentAnalytics>;
  keyOrdersForJoin: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").KeyByStreamConfig,
  ) => Promise<KeyOrdersForJoin>;
  keyPaymentsForJoin: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").KeyByStreamConfig,
  ) => Promise<KeyPaymentsForJoin>;
}

export function defaultJoinAnalyticsPipelineMakers(): JoinAnalyticsPipelineMakers {
  return {
    joinedAnalyticsSink: makeJoinedAnalyticsSink,
    joinOrderPaymentAnalytics: makeJoinOrderPaymentAnalytics,
    keyOrdersForJoin: makeKeyOrdersForJoin,
    keyPaymentsForJoin: makeKeyPaymentsForJoin,
  };
}

export interface JoinAnalyticsPipelineFunctions {
  joinedAnalyticsSink: JoinedAnalyticsSink;
  joinOrderPaymentAnalytics: JoinOrderPaymentAnalytics;
  keyOrdersForJoin: KeyOrdersForJoin;
  keyPaymentsForJoin: KeyPaymentsForJoin;
}

export interface JoinAnalyticsPipelineStreams {
  keyOrdersForJoin: ReturnType<typeof initJoinAnalyticsKeyOrdersForJoinStream>;
  keyPaymentsForJoin: ReturnType<typeof initJoinAnalyticsKeyPaymentsForJoinStream>;
  joinOrderPaymentAnalytics: ReturnType<typeof initJoinAnalyticsJoinOrderPaymentAnalyticsStream>;
  writeJoinedAnalytics: ReturnType<typeof initJoinAnalyticsWriteJoinedAnalyticsStream>;
}

export function initJoinAnalyticsPipelineStreams(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  streams: ServiceStreams,
): void {
  const initializedKeyOrdersForJoin = initJoinAnalyticsKeyOrdersForJoinStream(
    config,
    environment,
    functions,
    streams.splitAnalyticsOrders.addStream(),
    undefined,
    [],
  );
  streams.keyOrdersForJoin = initializedKeyOrdersForJoin;
  const initializedKeyPaymentsForJoin = initJoinAnalyticsKeyPaymentsForJoinStream(
    config,
    environment,
    functions,
    streams.splitAnalyticsPayments.addStream(),
    undefined,
    [],
  );
  streams.keyPaymentsForJoin = initializedKeyPaymentsForJoin;
  const initializedJoinOrderPaymentAnalytics = initJoinAnalyticsJoinOrderPaymentAnalyticsStream(
    config,
    environment,
    functions,
    streams.keyOrdersForJoin,
    streams.keyPaymentsForJoin,
    [],
  );
  streams.joinOrderPaymentAnalytics = initializedJoinOrderPaymentAnalytics;
  const initializedWriteJoinedAnalytics = initJoinAnalyticsWriteJoinedAnalyticsStream(
    config,
    environment,
    functions,
    streams.joinOrderPaymentAnalytics,
    undefined,
    [],
  );
  streams.writeJoinedAnalytics = initializedWriteJoinedAnalytics;
}

export function postInitJoinAnalyticsPipelineStreams(streams: ServiceStreams): void {
}
export function initJoinAnalyticsKeyOrdersForJoinStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeKeyByStream<AnalyticsEvent, string, AnalyticsEvent>(config.named.streams.keyOrdersForJoin, source as never, functions.keyOrdersForJoin);
  return stream;
}
export function initJoinAnalyticsKeyPaymentsForJoinStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeKeyByStream<AnalyticsEvent, string, AnalyticsEvent>(config.named.streams.keyPaymentsForJoin, source as never, functions.keyPaymentsForJoin);
  return stream;
}
export function initJoinAnalyticsJoinOrderPaymentAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeJoinStream<string, AnalyticsEvent, AnalyticsEvent, AnalyticsResult>(config.named.streams.joinOrderPaymentAnalytics, source as never, right as never, functions.joinOrderPaymentAnalytics);
  return stream;
}
export function initJoinAnalyticsWriteJoinedAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStream<AnalyticsResult, Error>(config.named.streams.writeJoinedAnalytics, source as never);
  return stream;
}
