// Code generated by servicegen. DO NOT EDIT.

import type { MessageContext, RuntimeEnvironment } from "@gorundebug/tsservicelib/runtime/graph";
import {
  makeCaseStream, makeDelayStream, makeFilterStream, makeFlatMapIterableStream,
  makeFlatMapStream, makeInputStream, makeJoinStream, makeKeyByStream,
  makeLinkStream, makeMapStream, makeMergeStream, makeMultiJoinLink,
  makeMultiJoinStream, makeProcessStream, makeSinkStream,
  makeSinkStreamWithResult, makeSplitStream, makeSubStream, makeWhenStream,
} from "@gorundebug/tsservicelib/operators";
import type { AnalyticsEvent, AnalyticsKey, AnalyticsResult } from "../types/index.generated.js";
import type { AutomationJob, OrderProcessed } from "@gorundebug/model";
import type { ConfigSnapshot } from "../config/config-snapshot.generated.js";
import type { ServiceFunctions, ServiceStreams } from "./graph.generated.js";
import {
  makeCountOrderProcessed,
  makeAnalyticsScheduleSource,
  makeOrderProcessedEndpointSource,
} from "../functions/index.generated.js";
import type {
  CountOrderProcessed,
  AnalyticsScheduleSource,
  OrderProcessedEndpointSource,
} from "../functions/index.generated.js";

export interface AnalyticsPipelineMakers {
  countOrderProcessed: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").ProcessStreamConfig,
  ) => Promise<CountOrderProcessed>;
  analyticsScheduleSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").CronEndpointConfig,
  ) => Promise<AnalyticsScheduleSource>;
  orderProcessedEndpointSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").KafkaEndpointConfig,
  ) => Promise<OrderProcessedEndpointSource>;
}

export function defaultAnalyticsPipelineMakers(): AnalyticsPipelineMakers {
  return {
    countOrderProcessed: makeCountOrderProcessed,
    analyticsScheduleSource: makeAnalyticsScheduleSource,
    orderProcessedEndpointSource: makeOrderProcessedEndpointSource,
  };
}

export interface AnalyticsPipelineFunctions {
  countOrderProcessed: CountOrderProcessed;
  analyticsScheduleSource: AnalyticsScheduleSource;
  orderProcessedEndpointSource: OrderProcessedEndpointSource;
}

export interface AnalyticsPipelineStreams {
  analyticsSchedule: ReturnType<typeof initAnalyticsAnalyticsScheduleStream>;
  consumeOrderProcessed: ReturnType<typeof initAnalyticsConsumeOrderProcessedStream>;
  countOrderProcessed: ReturnType<typeof initAnalyticsCountOrderProcessedStream>;
}

export function initAnalyticsPipelineStreams(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  streams: ServiceStreams,
): void {
  const initializedAnalyticsSchedule = initAnalyticsAnalyticsScheduleStream(
    config,
    environment,
    functions,
    undefined,
    undefined,
    [],
  );
  streams.analyticsSchedule = initializedAnalyticsSchedule;
  const initializedConsumeOrderProcessed = initAnalyticsConsumeOrderProcessedStream(
    config,
    environment,
    functions,
    undefined,
    undefined,
    [],
  );
  streams.consumeOrderProcessed = initializedConsumeOrderProcessed;
  const initializedCountOrderProcessed = initAnalyticsCountOrderProcessedStream(
    config,
    environment,
    functions,
    streams.consumeOrderProcessed,
    undefined,
    [],
  );
  streams.countOrderProcessed = initializedCountOrderProcessed;
}

export function postInitAnalyticsPipelineStreams(streams: ServiceStreams): void {
  bindAnalyticsConsumeOrderProcessedStream(
    streams.consumeOrderProcessed,
    streams.countOrderProcessed,
  );
}
export function initAnalyticsAnalyticsScheduleStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, unknown, Error>(config.named.streams.analyticsSchedule, environment);
  return stream;
}
export function initAnalyticsConsumeOrderProcessedStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<OrderProcessed, OrderProcessed, Error>(config.named.streams.consumeOrderProcessed, environment);
  return stream;
}
export function initAnalyticsCountOrderProcessedStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeProcessStream<OrderProcessed, OrderProcessed, Error>(config.named.streams.countOrderProcessed, source as never, functions.countOrderProcessed);
  return stream;
}
export function bindAnalyticsConsumeOrderProcessedStream<T>(stream: { setSource(source: T): void }, source: T): void {
  stream.setSource(source);
}
