// Code generated by servicegen. DO NOT EDIT.
import {
  Context, MessageContext, RuntimeConfigStore,
  ServiceApp, ServiceEnvironment, ServiceHTTPServer,
  type ServiceAppOptions, type ServiceConfig,
  errorFromUnknown,
  makeDefaultSerdeRegistry,
} from "@gorundebug/tsservicelib/runtime";
import { makeKafkaEndpointConsumer as makeKafkaSourceEndpointConsumer } from "@gorundebug/tsservicelib/datasource/kafka";
import { makeCronEndpointConsumer } from "@gorundebug/tsservicelib/datasource/cron";
import { Config } from "../config/config.js";
import { DataConnectorIds, ServiceIds } from "../config/config.generated.js";
import {
  defaultMakers, initFunctionsParallel, initStreams, registerGeneratedSerdes,
  type ServiceFunctions, type ServiceMakers, type ServiceStreams,
} from "./graph.generated.js";

export interface ServiceInfrastructureMakers {
  serviceHttpServer: (
    context: MessageContext,
    environment: ServiceEnvironment,
    config: ServiceConfig,
  ) => Promise<ServiceHTTPServer>;
}

function defaultInfrastructureMakers(): ServiceInfrastructureMakers {
  return {
    serviceHttpServer: async (_context, environment, _config) =>
      new ServiceHTTPServer(() => environment.serviceConfig()),
  };
}

async function initInfrastructure(
  context: MessageContext,
  config: Config,
  environment: ServiceEnvironment,
  makers: ServiceInfrastructureMakers,
) {
  const controller = new AbortController();
  const makerContext = context.withExternalCancellation(controller.signal);
  let firstError: unknown;
  let failed = false;
  const invokeMaker = async <T>(maker: () => Promise<T>): Promise<T> => {
    try {
      return await maker();
    } catch (error) {
      if (!failed) {
        failed = true;
        firstError = error;
        controller.abort(error);
      }
      throw error;
    }
  };
  let serviceHttpServer: ServiceHTTPServer | undefined;
  await Promise.allSettled([
    invokeMaker(async () => {
      serviceHttpServer = await makers.serviceHttpServer(
        makerContext, environment, environment.serviceConfig(),
      );
    }),
  ] as const);
  controller.abort();
  if (failed) throw firstError;
  if (serviceHttpServer === undefined) {
    throw new Error("service HTTP server maker returned no server");
  }
  environment.replaceHttpServer(serviceHttpServer);
  return {
  };
}

export type ServiceClients = Awaited<ReturnType<typeof initInfrastructure>>;

function initRuntimeConnectors(environment: ServiceEnvironment): void {
  void environment;
}


function initDataConnectors(
  streams: ServiceStreams,
  functions: ServiceFunctions,
  clients: ServiceClients,
) {
  const analyticsSchedule = makeCronEndpointConsumer(streams.analyticsSchedule, functions.analyticsScheduleSource);
  const consumeOrderProcessed = makeKafkaSourceEndpointConsumer(streams.consumeOrderProcessed, functions.orderProcessedEndpointSource);
  return {
    dataConnectors: {
      analyticsSchedule,
      consumeOrderProcessed,
    },
    handlers: {
    },
  };
}

export type ServiceDataConnectors = ReturnType<typeof initDataConnectors>["dataConnectors"];
export type ServiceHandlers = ReturnType<typeof initDataConnectors>["handlers"];

export abstract class ServiceGenerated {
  protected readonly makers: ServiceMakers = defaultMakers();
  protected readonly infrastructureMakers: ServiceInfrastructureMakers =
    defaultInfrastructureMakers();
  protected clients!: ServiceClients;
  protected functions!: ServiceFunctions;
  protected streams!: ServiceStreams;
  protected dataConnectors!: ServiceDataConnectors;
  protected handlers!: ServiceHandlers;

  protected customMakersInit(_context: MessageContext): void | Promise<void> {}
  protected customFunctionsInit(_context: MessageContext): void | Promise<void> {}
  protected createServiceAppOptions(_config: ServiceConfig): ServiceAppOptions { return {}; }
  protected onStart(_context: Context): Promise<void> { return Promise.resolve(); }
  protected onStop(_context: Context): Promise<void> { return Promise.resolve(); }

  public async run(arguments_: readonly string[]): Promise<void> {
    const config = await Config.load(arguments_);
    const configStore = new RuntimeConfigStore(config.runtime);
    const configPaths = Config.configPaths(arguments_);
    const serdeRegistry = makeDefaultSerdeRegistry();
    registerGeneratedSerdes(serdeRegistry);
    const serviceConfig = config.runtime.serviceById(ServiceIds.ANALYTICS_SERVICE);
    if (serviceConfig === undefined) {
      throw new Error("service config Analytics Service not found");
    }
    const app = new ServiceApp(configStore, ServiceIds.ANALYTICS_SERVICE, {
      ...this.createServiceAppOptions(serviceConfig),
      serdeRegistry,
      configReload: {
        paths: [
          configPaths.configPath,
          configPaths.valuesPath,
          configPaths.overridesPath,
        ].filter((path): path is string => path !== undefined),
        load: async () => (await Config.load(arguments_)).runtime,
      },
    });
    const environment = app.environment();
    const messageContext = new MessageContext();
    await this.customMakersInit(messageContext);
    this.clients = await initInfrastructure(
      messageContext, config, environment, this.infrastructureMakers,
    );
    this.functions = await initFunctionsParallel(
      messageContext, config, environment, this.makers,
    );
    await this.customFunctionsInit(messageContext);
    initRuntimeConnectors(environment);
    this.streams = initStreams(config, environment, this.functions);
    const bindings = initDataConnectors(this.streams, this.functions, this.clients);
    this.dataConnectors = bindings.dataConnectors;
    this.handlers = bindings.handlers;

    const context = Context.background();
    await this.onStart(context);
    await app.start(context);
    let terminationError: Error | undefined;
    try {
      terminationError = await waitForTermination();
    } finally {
      await this.onStop(context);
      await app.stop(context, environment.serviceConfig().shutdownTimeout);
    }
    if (terminationError !== undefined) throw terminationError;
  }
}

function waitForTermination(): Promise<Error | undefined> {
  return new Promise((resolve) => {
    const finish = (error?: Error): void => {
      process.off("SIGINT", done);
      process.off("SIGTERM", done);
      process.off("uncaughtException", fail);
      process.off("unhandledRejection", fail);
      resolve(error);
    };
    const done = (): void => {
      finish();
    };
    const fail = (reason: unknown): void => {
      finish(errorFromUnknown(reason));
    };
    process.once("SIGINT", done);
    process.once("SIGTERM", done);
    process.once("uncaughtException", fail);
    process.once("unhandledRejection", fail);
  });
}
