// Code generated by servicegen. DO NOT EDIT.

import type { RuntimeEnvironment } from "@gorundebug/tsservicelib/runtime/graph";
import {
  makeCaseStream, makeDelayStream, makeFilterStream, makeFlatMapIterableStream,
  makeFlatMapStream, makeInputStream, makeJoinStream, makeKeyByStream,
  makeLinkStream, makeMapStream, makeMergeStream, makeMultiJoinLink,
  makeMultiJoinStream, makeProcessStream, makeSinkStream,
  makeSinkStreamWithResult, makeSplitStream, makeSubStream, makeWhenStream,
} from "@gorundebug/tsservicelib/operators";
import type { AnalyticsEvent, AnalyticsKey, AnalyticsResult } from "../types/index.generated.js";
import type { AutomationJob, OrderProcessed } from "@gorundebug/model";
import type { KeyValue } from "@gorundebug/tsservicelib/runtime/graph";

import type { ConfigSnapshot } from "../config/config-snapshot.generated.js";
import type { ServiceFunctions } from "./functions.generated.js";

export class ServiceStreams {
  public cycleAnalyticsLink!: ReturnType<typeof initCycleAnalyticsLinkStream>;
  public analyticsSchedule!: ReturnType<typeof initAnalyticsScheduleStream>;
  public consumeOrderProcessed!: ReturnType<typeof initConsumeOrderProcessedStream>;
  public countOrderProcessed!: ReturnType<typeof initCountOrderProcessedStream>;
  public analyticsOrders!: ReturnType<typeof initAnalyticsOrdersStream>;
  public analyticsPayments!: ReturnType<typeof initAnalyticsPaymentsStream>;
  public analyticsShipments!: ReturnType<typeof initAnalyticsShipmentsStream>;
  public splitAnalyticsOrders!: ReturnType<typeof initSplitAnalyticsOrdersStream>;
  public splitAnalyticsPayments!: ReturnType<typeof initSplitAnalyticsPaymentsStream>;
  public cycleAnalyticsInput!: ReturnType<typeof initCycleAnalyticsInputStream>;
  public mergeCycleAnalytics!: ReturnType<typeof initMergeCycleAnalyticsStream>;
  public advanceCycleAnalytics!: ReturnType<typeof initAdvanceCycleAnalyticsStream>;
  public splitCycleAnalytics!: ReturnType<typeof initSplitCycleAnalyticsStream>;
  public completeCycleAnalytics!: ReturnType<typeof initCompleteCycleAnalyticsStream>;
  public continueCycleAnalytics!: ReturnType<typeof initContinueCycleAnalyticsStream>;
  public writeCycleAnalytics!: ReturnType<typeof initWriteCycleAnalyticsStream>;
  public keyOrdersForJoin!: ReturnType<typeof initKeyOrdersForJoinStream>;
  public keyPaymentsForJoin!: ReturnType<typeof initKeyPaymentsForJoinStream>;
  public joinOrderPaymentAnalytics!: ReturnType<typeof initJoinOrderPaymentAnalyticsStream>;
  public writeJoinedAnalytics!: ReturnType<typeof initWriteJoinedAnalyticsStream>;
  public keyOrdersForMultiJoin!: ReturnType<typeof initKeyOrdersForMultiJoinStream>;
  public keyPaymentsForMultiJoin!: ReturnType<typeof initKeyPaymentsForMultiJoinStream>;
  public keyShipmentsForMultiJoin!: ReturnType<typeof initKeyShipmentsForMultiJoinStream>;
  public multiJoinAnalyticsEvents!: ReturnType<typeof initMultiJoinAnalyticsEventsStream>;
  public routeAnalyticsResult!: ReturnType<typeof initRouteAnalyticsResultStream>;
  public highValueAnalytics!: ReturnType<typeof initHighValueAnalyticsStream>;
  public standardAnalytics!: ReturnType<typeof initStandardAnalyticsStream>;
  public writeHighValueAnalytics!: ReturnType<typeof initWriteHighValueAnalyticsStream>;
  public writeStandardAnalytics!: ReturnType<typeof initWriteStandardAnalyticsStream>;
  public analyzeAnalyticsSubstream!: ReturnType<typeof initAnalyzeAnalyticsSubstreamStream>;
  public buildSubstreamAnalyticsResult!: ReturnType<typeof initBuildSubstreamAnalyticsResultStream>;
  public substreamAnalyticsInput!: ReturnType<typeof initSubstreamAnalyticsInputStream>;
  public invokeAnalyticsSubstream!: ReturnType<typeof initInvokeAnalyticsSubstreamStream>;
  public writeSubstreamAnalytics!: ReturnType<typeof initWriteSubstreamAnalyticsStream>;

  public initStreams(config: ConfigSnapshot, environment: RuntimeEnvironment, functions: ServiceFunctions): void {
    const initializedCycleAnalyticsLink = initCycleAnalyticsLinkStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.cycleAnalyticsLink = initializedCycleAnalyticsLink;
    const initializedAnalyticsSchedule = initAnalyticsScheduleStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.analyticsSchedule = initializedAnalyticsSchedule;
    const initializedConsumeOrderProcessed = initConsumeOrderProcessedStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.consumeOrderProcessed = initializedConsumeOrderProcessed;
    const initializedCountOrderProcessed = initCountOrderProcessedStream(
      config, environment, functions,
      this.consumeOrderProcessed,
      undefined,
      [],
    );
    this.countOrderProcessed = initializedCountOrderProcessed;
    const initializedAnalyticsOrders = initAnalyticsOrdersStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.analyticsOrders = initializedAnalyticsOrders;
    const initializedAnalyticsPayments = initAnalyticsPaymentsStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.analyticsPayments = initializedAnalyticsPayments;
    const initializedAnalyticsShipments = initAnalyticsShipmentsStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.analyticsShipments = initializedAnalyticsShipments;
    const initializedSplitAnalyticsOrders = initSplitAnalyticsOrdersStream(
      config, environment, functions,
      this.analyticsOrders,
      undefined,
      [],
    );
    this.splitAnalyticsOrders = initializedSplitAnalyticsOrders;
    const initializedSplitAnalyticsPayments = initSplitAnalyticsPaymentsStream(
      config, environment, functions,
      this.analyticsPayments,
      undefined,
      [],
    );
    this.splitAnalyticsPayments = initializedSplitAnalyticsPayments;
    const initializedCycleAnalyticsInput = initCycleAnalyticsInputStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.cycleAnalyticsInput = initializedCycleAnalyticsInput;
    const initializedMergeCycleAnalytics = initMergeCycleAnalyticsStream(
      config, environment, functions,
      undefined,
      undefined,
      [this.cycleAnalyticsInput, this.cycleAnalyticsLink],
    );
    this.mergeCycleAnalytics = initializedMergeCycleAnalytics;
    const initializedAdvanceCycleAnalytics = initAdvanceCycleAnalyticsStream(
      config, environment, functions,
      this.mergeCycleAnalytics,
      undefined,
      [],
    );
    this.advanceCycleAnalytics = initializedAdvanceCycleAnalytics;
    const initializedSplitCycleAnalytics = initSplitCycleAnalyticsStream(
      config, environment, functions,
      this.advanceCycleAnalytics,
      undefined,
      [],
    );
    this.splitCycleAnalytics = initializedSplitCycleAnalytics;
    const initializedCompleteCycleAnalytics = initCompleteCycleAnalyticsStream(
      config, environment, functions,
      this.splitCycleAnalytics.addStream(),
      undefined,
      [],
    );
    this.completeCycleAnalytics = initializedCompleteCycleAnalytics;
    const initializedContinueCycleAnalytics = initContinueCycleAnalyticsStream(
      config, environment, functions,
      this.splitCycleAnalytics.addStream(),
      undefined,
      [],
    );
    this.continueCycleAnalytics = initializedContinueCycleAnalytics;
    const initializedWriteCycleAnalytics = initWriteCycleAnalyticsStream(
      config, environment, functions,
      this.completeCycleAnalytics,
      undefined,
      [],
    );
    this.writeCycleAnalytics = initializedWriteCycleAnalytics;
    const initializedKeyOrdersForJoin = initKeyOrdersForJoinStream(
      config, environment, functions,
      this.splitAnalyticsOrders.addStream(),
      undefined,
      [],
    );
    this.keyOrdersForJoin = initializedKeyOrdersForJoin;
    const initializedKeyPaymentsForJoin = initKeyPaymentsForJoinStream(
      config, environment, functions,
      this.splitAnalyticsPayments.addStream(),
      undefined,
      [],
    );
    this.keyPaymentsForJoin = initializedKeyPaymentsForJoin;
    const initializedJoinOrderPaymentAnalytics = initJoinOrderPaymentAnalyticsStream(
      config, environment, functions,
      this.keyOrdersForJoin,
      this.keyPaymentsForJoin,
      [],
    );
    this.joinOrderPaymentAnalytics = initializedJoinOrderPaymentAnalytics;
    const initializedWriteJoinedAnalytics = initWriteJoinedAnalyticsStream(
      config, environment, functions,
      this.joinOrderPaymentAnalytics,
      undefined,
      [],
    );
    this.writeJoinedAnalytics = initializedWriteJoinedAnalytics;
    const initializedKeyOrdersForMultiJoin = initKeyOrdersForMultiJoinStream(
      config, environment, functions,
      this.splitAnalyticsOrders.addStream(),
      undefined,
      [],
    );
    this.keyOrdersForMultiJoin = initializedKeyOrdersForMultiJoin;
    const initializedKeyPaymentsForMultiJoin = initKeyPaymentsForMultiJoinStream(
      config, environment, functions,
      this.splitAnalyticsPayments.addStream(),
      undefined,
      [],
    );
    this.keyPaymentsForMultiJoin = initializedKeyPaymentsForMultiJoin;
    const initializedKeyShipmentsForMultiJoin = initKeyShipmentsForMultiJoinStream(
      config, environment, functions,
      this.analyticsShipments,
      undefined,
      [],
    );
    this.keyShipmentsForMultiJoin = initializedKeyShipmentsForMultiJoin;
    const initializedMultiJoinAnalyticsEvents = initMultiJoinAnalyticsEventsStream(
      config, environment, functions,
      this.keyOrdersForMultiJoin,
      undefined,
      [this.keyPaymentsForMultiJoin, this.keyShipmentsForMultiJoin],
    );
    this.multiJoinAnalyticsEvents = initializedMultiJoinAnalyticsEvents;
    const initializedRouteAnalyticsResult = initRouteAnalyticsResultStream(
      config, environment, functions,
      this.multiJoinAnalyticsEvents,
      undefined,
      [],
    );
    this.routeAnalyticsResult = initializedRouteAnalyticsResult;
    const initializedHighValueAnalytics = initHighValueAnalyticsStream(
      config, environment, functions,
      this.routeAnalyticsResult,
      undefined,
      [],
    );
    this.highValueAnalytics = initializedHighValueAnalytics;
    const initializedStandardAnalytics = initStandardAnalyticsStream(
      config, environment, functions,
      this.routeAnalyticsResult,
      undefined,
      [],
    );
    this.standardAnalytics = initializedStandardAnalytics;
    const initializedWriteHighValueAnalytics = initWriteHighValueAnalyticsStream(
      config, environment, functions,
      this.highValueAnalytics,
      undefined,
      [],
    );
    this.writeHighValueAnalytics = initializedWriteHighValueAnalytics;
    const initializedWriteStandardAnalytics = initWriteStandardAnalyticsStream(
      config, environment, functions,
      this.standardAnalytics,
      undefined,
      [],
    );
    this.writeStandardAnalytics = initializedWriteStandardAnalytics;
    const initializedAnalyzeAnalyticsSubstream = initAnalyzeAnalyticsSubstreamStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.analyzeAnalyticsSubstream = initializedAnalyzeAnalyticsSubstream;
    const initializedBuildSubstreamAnalyticsResult = initBuildSubstreamAnalyticsResultStream(
      config, environment, functions,
      this.analyzeAnalyticsSubstream,
      undefined,
      [],
    );
    this.buildSubstreamAnalyticsResult = initializedBuildSubstreamAnalyticsResult;
    const initializedSubstreamAnalyticsInput = initSubstreamAnalyticsInputStream(
      config, environment, functions,
      undefined,
      undefined,
      [],
    );
    this.substreamAnalyticsInput = initializedSubstreamAnalyticsInput;
    const initializedInvokeAnalyticsSubstream = initInvokeAnalyticsSubstreamStream(
      config, environment, functions,
      this.substreamAnalyticsInput,
      undefined,
      [],
    );
    this.invokeAnalyticsSubstream = initializedInvokeAnalyticsSubstream;
    const initializedWriteSubstreamAnalytics = initWriteSubstreamAnalyticsStream(
      config, environment, functions,
      this.invokeAnalyticsSubstream,
      undefined,
      [],
    );
    this.writeSubstreamAnalytics = initializedWriteSubstreamAnalytics;
  }

  public build(): void {
    this.consumeOrderProcessed.setSource(this.countOrderProcessed);
    this.cycleAnalyticsLink.setSource(this.continueCycleAnalytics);
    this.analyzeAnalyticsSubstream.setSource(this.buildSubstreamAnalyticsResult);
  }
}

export function initStreams(config: ConfigSnapshot, environment: RuntimeEnvironment, functions: ServiceFunctions): ServiceStreams {
  const streams = new ServiceStreams();
  streams.initStreams(config, environment, functions);
  streams.build();
  return streams;
}
export function initCycleAnalyticsLinkStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeLinkStream<AnalyticsEvent>(config.named.streams.cycleAnalyticsLink, environment);
  return stream;
}
export function initAnalyticsScheduleStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<string, unknown, Error>(config.named.streams.analyticsSchedule, environment);
  return stream;
}
export function initConsumeOrderProcessedStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<OrderProcessed, OrderProcessed, Error>(config.named.streams.consumeOrderProcessed, environment);
  return stream;
}
export function initCountOrderProcessedStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeProcessStream<OrderProcessed, OrderProcessed, Error>(config.named.streams.countOrderProcessed, source as never, functions.countOrderProcessed);
  return stream;
}
export function initAnalyticsOrdersStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<AnalyticsEvent, unknown, Error>(config.named.streams.analyticsOrders, environment);
  return stream;
}
export function initAnalyticsPaymentsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<AnalyticsEvent, unknown, Error>(config.named.streams.analyticsPayments, environment);
  return stream;
}
export function initAnalyticsShipmentsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<AnalyticsEvent, unknown, Error>(config.named.streams.analyticsShipments, environment);
  return stream;
}
export function initSplitAnalyticsOrdersStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSplitStream<AnalyticsEvent>(config.named.streams.splitAnalyticsOrders, source as never);
  return stream;
}
export function initSplitAnalyticsPaymentsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSplitStream<AnalyticsEvent>(config.named.streams.splitAnalyticsPayments, source as never);
  return stream;
}
export function initCycleAnalyticsInputStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<AnalyticsEvent, unknown, Error>(config.named.streams.cycleAnalyticsInput, environment);
  return stream;
}
export function initMergeCycleAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMergeStream<AnalyticsEvent>(config.named.streams.mergeCycleAnalytics, sources[0] as never, sources[1] as never);
  return stream;
}
export function initAdvanceCycleAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<AnalyticsEvent, AnalyticsEvent>(config.named.streams.advanceCycleAnalytics, source as never, functions.advanceCycleAnalytics);
  return stream;
}
export function initSplitCycleAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSplitStream<AnalyticsEvent>(config.named.streams.splitCycleAnalytics, source as never);
  return stream;
}
export function initCompleteCycleAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeFilterStream<AnalyticsEvent>(config.named.streams.completeCycleAnalytics, source as never, functions.completeCycleAnalytics);
  return stream;
}
export function initContinueCycleAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeFilterStream<AnalyticsEvent>(config.named.streams.continueCycleAnalytics, source as never, functions.continueCycleAnalytics);
  return stream;
}
export function initWriteCycleAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStream<AnalyticsEvent, Error>(config.named.streams.writeCycleAnalytics, source as never);
  return stream;
}
export function initKeyOrdersForJoinStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeKeyByStream<AnalyticsEvent, string, AnalyticsEvent>(config.named.streams.keyOrdersForJoin, source as never, functions.keyOrdersForJoin);
  return stream;
}
export function initKeyPaymentsForJoinStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeKeyByStream<AnalyticsEvent, string, AnalyticsEvent>(config.named.streams.keyPaymentsForJoin, source as never, functions.keyPaymentsForJoin);
  return stream;
}
export function initJoinOrderPaymentAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeJoinStream<string, AnalyticsEvent, AnalyticsEvent, AnalyticsResult>(config.named.streams.joinOrderPaymentAnalytics, source as never, right as never, functions.joinOrderPaymentAnalytics);
  return stream;
}
export function initWriteJoinedAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStream<AnalyticsResult, Error>(config.named.streams.writeJoinedAnalytics, source as never);
  return stream;
}
export function initKeyOrdersForMultiJoinStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeKeyByStream<AnalyticsEvent, string, AnalyticsEvent>(config.named.streams.keyOrdersForMultiJoin, source as never, functions.keyOrdersForMultiJoin);
  return stream;
}
export function initKeyPaymentsForMultiJoinStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeKeyByStream<AnalyticsEvent, string, AnalyticsEvent>(config.named.streams.keyPaymentsForMultiJoin, source as never, functions.keyPaymentsForMultiJoin);
  return stream;
}
export function initKeyShipmentsForMultiJoinStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeKeyByStream<AnalyticsEvent, string, AnalyticsEvent>(config.named.streams.keyShipmentsForMultiJoin, source as never, functions.keyShipmentsForMultiJoin);
  return stream;
}
export function initMultiJoinAnalyticsEventsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMultiJoinStream<string, AnalyticsEvent, AnalyticsResult>(config.named.streams.multiJoinAnalyticsEvents, source as never, functions.multiJoinAnalyticsEvents);
  makeMultiJoinLink(stream, sources[0] as never);
  makeMultiJoinLink(stream, sources[1] as never);
  return stream;
}
export function initRouteAnalyticsResultStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeCaseStream<AnalyticsResult>(config.named.streams.routeAnalyticsResult, source as never, functions.routeAnalyticsResult);
  return stream;
}
export function initHighValueAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeWhenStream<AnalyticsResult, AnalyticsResult>(config.named.streams.highValueAnalytics, source as never);
  return stream;
}
export function initStandardAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeWhenStream<AnalyticsResult, AnalyticsResult>(config.named.streams.standardAnalytics, source as never);
  return stream;
}
export function initWriteHighValueAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStream<AnalyticsResult, Error>(config.named.streams.writeHighValueAnalytics, source as never);
  return stream;
}
export function initWriteStandardAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStream<AnalyticsResult, Error>(config.named.streams.writeStandardAnalytics, source as never);
  return stream;
}
export function initAnalyzeAnalyticsSubstreamStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSubStream<AnalyticsEvent, AnalyticsResult>(config.named.streams.analyzeAnalyticsSubstream, environment);
  return stream;
}
export function initBuildSubstreamAnalyticsResultStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<AnalyticsEvent, AnalyticsResult>(config.named.streams.buildSubstreamAnalyticsResult, source as never, functions.buildSubstreamAnalyticsResult);
  return stream;
}
export function initSubstreamAnalyticsInputStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<AnalyticsEvent, unknown, Error>(config.named.streams.substreamAnalyticsInput, environment);
  return stream;
}
export function initInvokeAnalyticsSubstreamStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<AnalyticsEvent, AnalyticsResult>(config.named.streams.invokeAnalyticsSubstream, source as never, functions.invokeAnalyticsSubstream);
  return stream;
}
export function initWriteSubstreamAnalyticsStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeSinkStream<AnalyticsResult, Error>(config.named.streams.writeSubstreamAnalytics, source as never);
  return stream;
}
