// Code generated by servicegen. DO NOT EDIT.

import type { MessageContext, SubStream, SubStreamCollector } from "@gorundebug/tsservicelib/runtime/graph";
import type { ServiceStreams } from "./streams.generated.js";
import type { AnalyticsEvent, AnalyticsKey, AnalyticsResult } from "../types/index.generated.js";
import type { AutomationJob, OrderProcessed } from "@gorundebug/model";
import type { KeyValue } from "@gorundebug/tsservicelib/runtime/graph";

class SubStreamHandle<T, R> implements SubStream<T, R> {
  public target: SubStream<T, R> | undefined;

  public consume(context: MessageContext, value: T, collector: SubStreamCollector<R>): Promise<void> {
    if (this.target === undefined) {
      return Promise.reject(new Error("SubStream graph is not initialized"));
    }
    return this.target.consume(context, value, collector);
  }
}

/** Stable typed accessors are available before business-function makers run. */
export class ServiceSubStreams {
  readonly #analyzeAnalyticsSubstream = new SubStreamHandle<AnalyticsEvent, AnalyticsResult>();

  public getAnalyzeAnalyticsSubstreamSubStream(): SubStream<AnalyticsEvent, AnalyticsResult> {
    return this.#analyzeAnalyticsSubstream;
  }

  public bindSubStreams(streams: ServiceStreams): void {
    this.#analyzeAnalyticsSubstream.target = streams.analyzeAnalyticsSubstream;
  }
}
