services:
  automationservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-runtime}
      extra_hosts:
        - "host.docker.internal:host-gateway"
      args:
        DEPENDENCY_DOCKER_REGISTRY: ${DEPENDENCY_DOCKER_REGISTRY:-docker.io}
        NPM_CONFIG_REGISTRY: ${NPM_CONFIG_REGISTRY:-https://registry.npmjs.org/}
        DEPENDENCY_GITHUB_RAW_URL: ${DEPENDENCY_GITHUB_RAW_URL:-https://github.com}
    image: automationservice-typescript:local
    command: ["--config", "config/config.yaml", "--values", "config/overrides.yaml", "--overrides", "config/docker_overrides.yaml"]
    environment:
      - DEBUG=${DEBUG:-0}
      - NODE_DIAGNOSTIC_DIR=/tmp/node-diagnostics
      - AUTOMATION_SERVICE_HTTP_PORT
      - AUTOMATION_SERVICE_GRPC_PORT
    ports:
      - "${AUTOMATION_SERVICE_HOST_HTTP_PORT:-9094}:${AUTOMATION_SERVICE_HTTP_PORT:-9094}"
      - "${AUTOMATION_SERVICE_HOST_GRPC_PORT:-9204}:${AUTOMATION_SERVICE_GRPC_PORT:-9204}"
