services:
  automationservice:
    image: automationservice-typescript-development:latest
    command:
      - /workspace/scripts/run-service.generated.sh
      - /workspace/src/main.generated.ts
      - --config
      - /workspace/config/config.yaml
      - --values
      - /workspace/config/docker_overrides.yaml
    environment:
      NODE_DIAGNOSTIC_DIR: /workspace/.artifacts/node-diagnostics
    volumes:
      - .:/workspace
      - /workspace/node_modules
