services:
  analyticsservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-runtime}
      extra_hosts:
        - "host.docker.internal:host-gateway"
      args:
        DEPENDENCY_DOCKER_REGISTRY: ${DEPENDENCY_DOCKER_REGISTRY:-docker.io}
        NPM_CONFIG_REGISTRY: ${NPM_CONFIG_REGISTRY:-https://registry.npmjs.org/}
        DEPENDENCY_GITHUB_RAW_URL: ${DEPENDENCY_GITHUB_RAW_URL:-https://github.com}
    image: analyticsservice-typescript:latest
    command: ["--config", "config/config.yaml", "--values", "config/docker_overrides.yaml"]
    environment:
      - DEBUG=${DEBUG:-0}
      - NODE_DIAGNOSTIC_DIR=/tmp/node-diagnostics
      - ANALYTICS_SERVICE_HTTP_PORT
      - ANALYTICS_SERVICE_GRPC_PORT
    ports:
      - "${ANALYTICS_SERVICE_HTTP_PORT:-9093}:${ANALYTICS_SERVICE_HTTP_PORT:-9093}"
      - "${ANALYTICS_SERVICE_GRPC_PORT:-9203}:${ANALYTICS_SERVICE_GRPC_PORT:-9203}"
      - "2345:2345"
