// Code generated by servicegen. DO NOT EDIT.
import {
  GrpcJsDataSource,
  makeGrpcNoStreamingEndpointConsumer as makeGrpcNoStreamingSourceEndpointConsumer,
} from "@gorundebug/tsservicelib/datasource/grpc";
import { InventoryServiceApi } from "@gorundebug/inventory-service-api";
import type { ServiceClients } from "./clients.generated.js";
import type { ServiceFunctions } from "./functions.generated.js";
import type { ServiceStreams } from "./streams.generated.js";

function initDataConnectors(
  streams: ServiceStreams,
  functions: ServiceFunctions,
  clients: ServiceClients,
) {
  const processInventoryItem = makeGrpcNoStreamingSourceEndpointConsumer(streams.processInventoryItem, InventoryServiceApi, InventoryServiceApi.method.processOrderItem, functions.processOrderItemSource);
  return {
    dataConnectors: {
      processInventoryItem,
    },
    handlers: {
    },
  };
}

export type ServiceDataConnectors = ReturnType<typeof initDataConnectors>["dataConnectors"];
export type ServiceHandlers = ReturnType<typeof initDataConnectors>["handlers"];


export class ServiceEndpoints {
  public dataConnectors!: ServiceDataConnectors;
  public handlers!: ServiceHandlers;

  public bind(streams: ServiceStreams, functions: ServiceFunctions, clients: ServiceClients) {
    const bindings = initDataConnectors(streams, functions, clients);
    this.dataConnectors = bindings.dataConnectors;
    this.handlers = bindings.handlers;
    return bindings;
  }
}
