// Code generated by servicegen. DO NOT EDIT.

import {
  JsonSerde, MessageContext, SerdeRegistry, SerdeType,
  type RuntimeEnvironment,
  boolSerdeType, bytesSerdeType, errorSerdeType,
  float32SerdeType, float64SerdeType,
  int8SerdeType, int16SerdeType, int32SerdeType, int64SerdeType, intSerdeType,
  makeStreamSerde, runeSerdeType,
  stringSerdeType,
  uint8SerdeType, uint16SerdeType, uint32SerdeType, uint64SerdeType, uintSerdeType,
} from "@gorundebug/tsservicelib/runtime/graph";
import {
  makeCaseStream, makeDelayStream, makeFilterStream, makeFlatMapIterableStream,
  makeFlatMapStream, makeInputStream, makeJoinStream, makeKeyByStream,
  makeLinkStream, makeMapStream, makeMergeStream, makeMultiJoinLink,
  makeMultiJoinStream, makeProcessStream, makeSinkStream,
  makeSinkStreamWithResult, makeSplitStream, makeWhenStream,
} from "@gorundebug/tsservicelib/operators";
import type { OrderItem, OrderItemResult } from "@gorundebug/model";
import {
  StreamIds,
  type ConfigSnapshot,
} from "../config/config-snapshot.generated.js";
import {
  ProcessOrderItemSource, makeProcessOrderItemSource,
  GetInventoryItemData, makeGetInventoryItemData,
} from "../functions/index.generated.js";

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const serdeTypes = {
  orderItem: new SerdeType<OrderItem>("OrderItem", (value): value is OrderItem => isRecord(value)),
  orderItemResult: new SerdeType<OrderItemResult>("OrderItemResult", (value): value is OrderItemResult => isRecord(value)),
} as const;

export function registerGeneratedSerdes(registry: SerdeRegistry): void {
  registry.register(serdeTypes.orderItem, makeStreamSerde(new JsonSerde(serdeTypes.orderItem)));
  registry.register(serdeTypes.orderItemResult, makeStreamSerde(new JsonSerde(serdeTypes.orderItemResult)));
  registry.registerStreamValueType(StreamIds.PROCESS_INVENTORY_ITEM, serdeTypes.orderItem);
  registry.registerStreamErrorType(StreamIds.PROCESS_INVENTORY_ITEM, errorSerdeType);
  registry.registerStreamValueType(StreamIds.GET_INVENTORY_ITEM_DATA, serdeTypes.orderItemResult);
  registry.registerStreamErrorType(StreamIds.GET_INVENTORY_ITEM_DATA, serdeTypes.orderItemResult);
  registry.registerStreamValueType(StreamIds.MERGE_INVENTORY_RESULT, serdeTypes.orderItemResult);
}

export interface ServiceMakers {
  processOrderItemSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").GrpcEndpointConfig,
  ) => ProcessOrderItemSource;
  getInventoryItemData: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").ProcessStreamConfig,
  ) => GetInventoryItemData;
}

export function defaultMakers(): ServiceMakers {
  return {
    processOrderItemSource: makeProcessOrderItemSource,
    getInventoryItemData: makeGetInventoryItemData,
  };
}

export function initFunctions(
  context: MessageContext,
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  makers: ServiceMakers,
) {
  return {
    processOrderItemSource: makers.processOrderItemSource(context, environment, config.named.endpoints.processOrderItem),
    getInventoryItemData: makers.getInventoryItemData(context, environment, config.named.streams.getInventoryItemData),
  };
}

export type ServiceFunctions = ReturnType<typeof initFunctions>;

export function initStreams(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
) {
  const processInventoryItem = makeInputStream<OrderItem, OrderItemResult, Error>(config.named.streams.processInventoryItem, environment);
  const getInventoryItemData = makeProcessStream<OrderItem, OrderItemResult, OrderItemResult>(config.named.streams.getInventoryItemData, processInventoryItem, functions.getInventoryItemData);
  const getInventoryItemError = getInventoryItemData.errorStream();
  const mergeInventoryResult = makeMergeStream<OrderItemResult>(config.named.streams.mergeInventoryResult, getInventoryItemData, getInventoryItemError);
  processInventoryItem.setSource(mergeInventoryResult);
  return {
    processInventoryItem,
    getInventoryItemData,
    getInventoryItemError,
    mergeInventoryResult,
  };
}

export type ServiceStreams = ReturnType<typeof initStreams>;
