// Code generated by servicegen. DO NOT EDIT.

import type { MessageContext, RuntimeEnvironment } from "@gorundebug/tsservicelib/runtime/graph";
import {
  makeCaseStream, makeDelayStream, makeFilterStream, makeFlatMapIterableStream,
  makeFlatMapStream, makeInputStream, makeJoinStream, makeKeyByStream,
  makeLinkStream, makeMapStream, makeMergeStream, makeMultiJoinLink,
  makeMultiJoinStream, makeProcessStream, makeSinkStream,
  makeSinkStreamWithResult, makeSplitStream, makeSubStream, makeWhenStream,
} from "@gorundebug/tsservicelib/operators";
import type { InventoryFailure } from "../types/index.generated.js";
import type { OrderItem, OrderItemResult } from "@gorundebug/model";
import type { ConfigSnapshot } from "../config/config-snapshot.generated.js";
import type { ServiceFunctions, ServiceStreams } from "./graph.generated.js";
import {
  makeProcessOrderItemSource,
  makeGetInventoryItemData,
  makeGetInventoryItemError,
} from "../functions/index.generated.js";
import type {
  ProcessOrderItemSource,
  GetInventoryItemData,
  GetInventoryItemError,
} from "../functions/index.generated.js";

export interface InventoryItemPipelineMakers {
  processOrderItemSource: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").GrpcEndpointConfig,
  ) => Promise<ProcessOrderItemSource>;
  getInventoryItemData: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").ProcessStreamConfig,
  ) => Promise<GetInventoryItemData>;
  getInventoryItemError: (
    context: MessageContext,
    environment: RuntimeEnvironment,
    config: import("@gorundebug/tsservicelib/runtime/graph").MapStreamConfig,
  ) => Promise<GetInventoryItemError>;
}

export function defaultInventoryItemPipelineMakers(): InventoryItemPipelineMakers {
  return {
    processOrderItemSource: makeProcessOrderItemSource,
    getInventoryItemData: makeGetInventoryItemData,
    getInventoryItemError: makeGetInventoryItemError,
  };
}

export interface InventoryItemPipelineFunctions {
  processOrderItemSource: ProcessOrderItemSource;
  getInventoryItemData: GetInventoryItemData;
  getInventoryItemError: GetInventoryItemError;
}

export interface InventoryItemPipelineStreams {
  processInventoryItem: ReturnType<typeof initInventoryItemProcessInventoryItemStream>;
  getInventoryItemData: ReturnType<typeof initInventoryItemGetInventoryItemDataStream>["stream"];
  getInventoryItemError: ReturnType<typeof initInventoryItemGetInventoryItemDataStream>["errorStream"];
  mapInventoryItemError: ReturnType<typeof initInventoryItemMapInventoryItemErrorStream>;
  mergeInventoryResult: ReturnType<typeof initInventoryItemMergeInventoryResultStream>;
}

export function initInventoryItemPipelineStreams(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  streams: ServiceStreams,
): void {
  const initializedProcessInventoryItem = initInventoryItemProcessInventoryItemStream(
    config,
    environment,
    functions,
    undefined,
    undefined,
    [],
  );
  streams.processInventoryItem = initializedProcessInventoryItem;
  const initializedGetInventoryItemData = initInventoryItemGetInventoryItemDataStream(
    config,
    environment,
    functions,
    streams.processInventoryItem,
    undefined,
    [],
  );
  streams.getInventoryItemData = initializedGetInventoryItemData.stream;
  streams.getInventoryItemError = initializedGetInventoryItemData.errorStream;
  const initializedMapInventoryItemError = initInventoryItemMapInventoryItemErrorStream(
    config,
    environment,
    functions,
    streams.getInventoryItemError,
    undefined,
    [],
  );
  streams.mapInventoryItemError = initializedMapInventoryItemError;
  const initializedMergeInventoryResult = initInventoryItemMergeInventoryResultStream(
    config,
    environment,
    functions,
    undefined,
    undefined,
    [streams.getInventoryItemData, streams.mapInventoryItemError],
  );
  streams.mergeInventoryResult = initializedMergeInventoryResult;
}

export function postInitInventoryItemPipelineStreams(streams: ServiceStreams): void {
  bindInventoryItemProcessInventoryItemStream(
    streams.processInventoryItem,
    streams.mergeInventoryResult,
  );
}
export function initInventoryItemProcessInventoryItemStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeInputStream<OrderItem, OrderItemResult, Error>(config.named.streams.processInventoryItem, environment);
  return stream;
}
export function initInventoryItemGetInventoryItemDataStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeProcessStream<OrderItem, OrderItemResult, Error>(config.named.streams.getInventoryItemData, source as never, functions.getInventoryItemData);
  return { stream, errorStream: stream.errorStream() };
}
export function initInventoryItemMapInventoryItemErrorStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMapStream<Error, OrderItemResult>(config.named.streams.mapInventoryItemError, source as never, functions.getInventoryItemError);
  return stream;
}
export function initInventoryItemMergeInventoryResultStream(
  config: ConfigSnapshot,
  environment: RuntimeEnvironment,
  functions: ServiceFunctions,
  source?: unknown,
  right?: unknown,
  sources: readonly unknown[] = [],
) {
  const stream = makeMergeStream<OrderItemResult>(config.named.streams.mergeInventoryResult, sources[0] as never, sources[1] as never);
  return stream;
}
export function bindInventoryItemProcessInventoryItemStream<T>(stream: { setSource(source: T): void }, source: T): void {
  stream.setSource(source);
}
