// Code generated by servicegen. DO NOT EDIT.

import {
  JsonSerde, SerdeRegistry, SerdeType,
  boolSerdeType, bytesSerdeType, errorSerdeType,
  float32SerdeType, float64SerdeType,
  int8SerdeType, int16SerdeType, int32SerdeType, int64SerdeType, intSerdeType,
  makeStreamSerde, runeSerdeType,
  stringSerdeType,
  uint8SerdeType, uint16SerdeType, uint32SerdeType, uint64SerdeType, uintSerdeType,
} from "@gorundebug/tsservicelib/runtime/graph";
import type { InventoryFailure } from "../types/index.generated.js";
import type { OrderItem, OrderItemResult } from "@gorundebug/model";
import { StreamIds } from "../config/config-snapshot.generated.js";

function isRecord(value: unknown): value is Readonly<Record<string, unknown>> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

const serdeTypes = {
  inventoryFailure: new SerdeType<InventoryFailure>("InventoryFailure", (value): value is InventoryFailure => isRecord(value)),
  orderItem: new SerdeType<OrderItem>("OrderItem", (value): value is OrderItem => isRecord(value)),
  orderItemResult: new SerdeType<OrderItemResult>("OrderItemResult", (value): value is OrderItemResult => isRecord(value)),
} as const;

export function registerGeneratedSerdes(registry: SerdeRegistry): void {
  registry.register(serdeTypes.inventoryFailure, makeStreamSerde(new JsonSerde(serdeTypes.inventoryFailure)));
  registry.register(serdeTypes.orderItem, makeStreamSerde(new JsonSerde(serdeTypes.orderItem)));
  registry.register(serdeTypes.orderItemResult, makeStreamSerde(new JsonSerde(serdeTypes.orderItemResult)));
  registry.registerStreamValueType(StreamIds.PROCESS_INVENTORY_ITEM, serdeTypes.orderItem);
  registry.registerStreamErrorType(StreamIds.PROCESS_INVENTORY_ITEM, errorSerdeType);
  registry.registerStreamValueType(StreamIds.GET_INVENTORY_ITEM_DATA, serdeTypes.orderItemResult);
  registry.registerStreamErrorType(StreamIds.GET_INVENTORY_ITEM_DATA, serdeTypes.inventoryFailure);
  registry.registerStreamValueType(StreamIds.MAP_INVENTORY_ITEM_ERROR, serdeTypes.orderItemResult);
  registry.registerStreamValueType(StreamIds.MERGE_INVENTORY_RESULT, serdeTypes.orderItemResult);
}
