// Code generated by servicegen. DO NOT EDIT.

import {
  canonicalConfigSchema,
  loadRuntimeConfig,
  parseConfigArguments,
  type EnvironmentPatch,
  type RuntimeConfig,
  requireGrpcDataConnectorConfig,
  type GrpcDataConnectorConfig,
  type GrpcDataConnectorConfigDocument,
  requireGrpcEndpointConfig,
  type GrpcEndpointConfig,
  type GrpcEndpointConfigDocument,
  requireInputStreamConfig,
  type InputStreamConfig,
  type InputStreamConfigDocument,
  type LinkConfigDocument,
  requireMergeStreamConfig,
  type MergeStreamConfig,
  type MergeStreamConfigDocument,
  type ModuleConfig,
  type ModuleConfigDocument,
  type PoolConfig,
  type PoolConfigDocument,
  requireProcessStreamConfig,
  type ProcessStreamConfig,
  type ProcessStreamConfigDocument,
  type ServiceConfig,
  type ServiceConfigDocument,
  type TypeConfig,
  type TypeConfigDocument,
} from "@gorundebug/tsservicelib/runtime/config";

export const ServiceIds = {
  INVENTORY_SERVICE: 1,
} as const;

export const StreamIds = {
  GET_INVENTORY_ITEM_DATA: 1,
  MERGE_INVENTORY_RESULT: 2,
  PROCESS_INVENTORY_ITEM: 3,
} as const;

export const DataConnectorIds = {
  INVENTORY_SERVICE_API: 1,
} as const;

export const EndpointIds = {
  PROCESS_ORDER_ITEM: 1,
} as const;

export interface NamedConfig {
  readonly services: {
    readonly inventoryService: ServiceConfig;
  };
  readonly streams: {
    readonly getInventoryItemData: ProcessStreamConfig;
    readonly mergeInventoryResult: MergeStreamConfig;
    readonly processInventoryItem: InputStreamConfig;
  };
  readonly dataConnectors: {
    readonly inventoryServiceApi: GrpcDataConnectorConfig;
  };
  readonly endpoints: {
    readonly processOrderItem: GrpcEndpointConfig;
  };
  readonly pools: {
    readonly inventoryPriorityWorkers: PoolConfig;
  };
  readonly modules: {
    readonly inventoryServiceApi: ModuleConfig;
    readonly model: ModuleConfig;
    readonly orderServiceApi: ModuleConfig;
  };
  readonly types: {
    readonly orderItem: TypeConfig;
    readonly orderItemResult: TypeConfig;
  };
}

interface DefaultConfig {
  readonly services: {
    readonly "inventoryService": ServiceConfigDocument;
  };
  readonly streams: {
    readonly "getInventoryItemData": ProcessStreamConfigDocument;
    readonly "mergeInventoryResult": MergeStreamConfigDocument;
    readonly "processInventoryItem": InputStreamConfigDocument;
  };
  readonly dataConnectors: {
    readonly "inventoryServiceApi": GrpcDataConnectorConfigDocument;
  };
  readonly endpoints: {
    readonly "processOrderItem": GrpcEndpointConfigDocument;
  };
  readonly pools: {
    readonly "inventoryPriorityWorkers": PoolConfigDocument;
  };
  readonly links: {
    readonly "getInventoryItemDataToMergeInventoryResult": LinkConfigDocument;
    readonly "processInventoryItemToGetInventoryItemData": LinkConfigDocument;
  };
  readonly modules: {
    readonly "inventoryServiceApi": ModuleConfigDocument;
    readonly "model": ModuleConfigDocument;
    readonly "orderServiceApi": ModuleConfigDocument;
  };
  readonly types: {
    readonly "orderItem": TypeConfigDocument;
    readonly "orderItemResult": TypeConfigDocument;
  };
}

const DEFAULT_CONFIG = {
  "services": {
    "inventoryService": {
      "color": "#6800FF",
      "defaultCallSemantics": 2,
      "defaultGrpcTimeout": 0,
      "environment": "",
      "golangVersion": "1.25.4",
      "grpcHost": "0.0.0.0",
      "grpcPort": 9202,
      "httpHost": "0.0.0.0",
      "httpPort": 9092,
      "id": 1,
      "metricsHandler": "metrics",
      "startupHandler": "health/startup",
      "readinessHandler": "health/ready",
      "livenessHandler": "health/live",
      "kubernetesWorkloadType": "Deployment",
      "modulePath": "github.com/gorundebug/tsexample-inventoryservice",
      "name": "Inventory Service",
      "shutdownTimeout": 30000,
      "statusHandler": "status"
    }
  },
  "streams": {
    "getInventoryItemData": {
      "functionDescription": "Reserve the requested quantity without allowing concurrent orders to overdraw stock.\nOn success, return CONFIRMED with the requested quantity available. Otherwise return OUT_OF_STOCK with the current available quantity.\nPreserve the order and item identity, requested quantity, and unit price.\nThe example starts with SKU-001: 100, SKU-002: 50, and SKU-003: 25.\n",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "GetInventoryItemData",
      "functionPackage": "",
      "id": 1,
      "idService": 1,
      "idSource": 3,
      "name": "Get Inventory Item Data",
      "pipeline": "inventoryItem",
      "type": 6,
      "xPos": 527,
      "yPos": -562
    },
    "mergeInventoryResult": {
      "id": 2,
      "idService": 1,
      "idSource": 0,
      "idSources": [
        1
      ],
      "name": "Merge Inventory Result",
      "pipeline": "inventoryItem",
      "type": 10,
      "xPos": 542,
      "yPos": 33
    },
    "processInventoryItem": {
      "id": 3,
      "idEndpoint": 1,
      "idService": 1,
      "idSource": 2,
      "name": "Process Inventory Item ",
      "pipeline": "inventoryItem",
      "type": 1,
      "valueType": "OrderItem",
      "xPos": 250,
      "yPos": -400
    }
  },
  "dataConnectors": {
    "inventoryServiceApi": {
      "address": "dns:///localhost:9202",
      "connectionsCount": 1,
      "id": 1,
      "implementation": "grpc/grpc-js",
      "module": "inventory_service_api",
      "name": "Inventory Service API",
      "type": 2
    }
  },
  "endpoints": {
    "processOrderItem": {
      "functionDescription": "Reserve inventory for one order item using its order ID, item ID, SKU, and quantity.\nReturn the available quantity, reservation outcome, and status. The caller combines this response with the original identity, requested quantity, and unit price.\nIf the inventory call fails, the caller returns a non-reserved PROCESSING_ERROR result with the failure message.\n",
      "functionInitializerGroup": "",
      "functionName": "ProcessOrderItem",
      "functionPackage": "",
      "grpcMethodType": 1,
      "id": 1,
      "idDataConnector": 1,
      "methodName": "ProcessOrderItem",
      "name": "Process Order Item",
      "publicFunction": false
    }
  },
  "pools": {
    "inventoryPriorityWorkers": {
      "executorsCount": 2,
      "name": "Inventory Priority Workers"
    }
  },
  "links": {
    "getInventoryItemDataToMergeInventoryResult": {
      "callSemantics": 2,
      "from": 1,
      "to": 2
    },
    "processInventoryItemToGetInventoryItemData": {
      "callSemantics": 2,
      "from": 3,
      "to": 1
    }
  },
  "modules": {
    "inventoryServiceApi": {
      "name": "inventory_service_api",
      "path": "github.com/gorundebug/tsexample-inventory-service-api"
    },
    "model": {
      "name": "model",
      "path": "github.com/gorundebug/tsexample-model"
    },
    "orderServiceApi": {
      "name": "order_service_api",
      "path": "github.com/gorundebug/tsexample-order-service-api"
    }
  },
  "types": {
    "orderItem": {
      "name": "OrderItem",
      "type": "struct",
      "typeDefinition": "OrderItem",
      "typeImport": "@gorundebug/model/types/order-item.js",
      "module": "model",
      "definitionFormat": 1
    },
    "orderItemResult": {
      "name": "OrderItemResult",
      "type": "struct",
      "typeDefinition": "OrderItemResult",
      "typeImport": "@gorundebug/model/types/order-item-result.js",
      "module": "model",
      "definitionFormat": 1
    }
  }
} as const satisfies DefaultConfig;

export function parseStringEnvironment(value: string): string { return value; }

export function parseIntegerEnvironment(value: string): number {
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed)) throw new Error(`expected an integer, got ${value}`);
  return parsed;
}

export function parseNumberEnvironment(value: string): number {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) throw new Error(`expected a number, got ${value}`);
  return parsed;
}

export function parseBooleanEnvironment(value: string): boolean {
  switch (value.trim().toLowerCase()) {
    case "1": case "true": case "yes": case "on": return true;
    case "0": case "false": case "no": case "off": return false;
    default: throw new Error(`expected a boolean, got ${value}`);
  }
}

export function parseStringListEnvironment(value: string): readonly string[] {
  return value.split(",").map((item) => item.trim()).filter((item) => item.length > 0);
}

export function parseIntegerListEnvironment(value: string): readonly number[] {
  return parseStringListEnvironment(value).map(parseIntegerEnvironment);
}

const ENVIRONMENT_PATCHES: readonly EnvironmentPatch[] = [
  { environment: "INVENTORY_PRIORITY_WORKERS_EXECUTORS_COUNT", path: ["pools", "inventoryPriorityWorkers", "executorsCount", ], parse: parseIntegerEnvironment },
  { environment: "INVENTORY_SERVICE_API_ADDRESS", path: ["dataConnectors", "inventoryServiceApi", "address", ], parse: parseStringEnvironment },
  { environment: "INVENTORY_SERVICE_API_CONNECTIONS_COUNT", path: ["dataConnectors", "inventoryServiceApi", "connectionsCount", ], parse: parseIntegerEnvironment },
  { environment: "INVENTORY_SERVICE_DEFAULT_GRPC_TIMEOUT", path: ["services", "inventoryService", "defaultGrpcTimeout", ], parse: parseIntegerEnvironment },
  { environment: "INVENTORY_SERVICE_ENVIRONMENT", path: ["services", "inventoryService", "environment", ], parse: parseStringEnvironment },
  { environment: "INVENTORY_SERVICE_GRPC_HOST", path: ["services", "inventoryService", "grpcHost", ], parse: parseStringEnvironment },
  { environment: "INVENTORY_SERVICE_GRPC_PORT", path: ["services", "inventoryService", "grpcPort", ], parse: parseIntegerEnvironment },
  { environment: "INVENTORY_SERVICE_HTTP_HOST", path: ["services", "inventoryService", "httpHost", ], parse: parseStringEnvironment },
  { environment: "INVENTORY_SERVICE_HTTP_PORT", path: ["services", "inventoryService", "httpPort", ], parse: parseIntegerEnvironment },
];

function required<T>(value: T | undefined, description: string): T {
  if (value === undefined) throw new Error(`missing ${description}`);
  return value;
}

function namedConfig(runtime: RuntimeConfig): NamedConfig {
  return {
    services: {
      inventoryService: required(runtime.serviceById(ServiceIds.INVENTORY_SERVICE), "Inventory Service"),
    },
    streams: {
      getInventoryItemData: requireProcessStreamConfig(runtime.streamById(StreamIds.GET_INVENTORY_ITEM_DATA)),
      mergeInventoryResult: requireMergeStreamConfig(runtime.streamById(StreamIds.MERGE_INVENTORY_RESULT)),
      processInventoryItem: requireInputStreamConfig(runtime.streamById(StreamIds.PROCESS_INVENTORY_ITEM)),
    },
    dataConnectors: {
      inventoryServiceApi: requireGrpcDataConnectorConfig(runtime.dataConnectorById(DataConnectorIds.INVENTORY_SERVICE_API)),
    },
    endpoints: {
      processOrderItem: requireGrpcEndpointConfig(runtime.endpointById(EndpointIds.PROCESS_ORDER_ITEM)),
    },
    pools: {
      inventoryPriorityWorkers: required(runtime.poolByName("Inventory Priority Workers"), "Inventory Priority Workers"),
    },
    modules: {
      inventoryServiceApi: required(runtime.moduleByName("inventory_service_api"), "inventory_service_api"),
      model: required(runtime.moduleByName("model"), "model"),
      orderServiceApi: required(runtime.moduleByName("order_service_api"), "order_service_api"),
    },
    types: {
      orderItem: required(runtime.typeByName("OrderItem"), "OrderItem"),
      orderItemResult: required(runtime.typeByName("OrderItemResult"), "OrderItemResult"),
    }
  };
}

export class ConfigGenerated {
  public readonly named: NamedConfig;

  public constructor(public readonly runtime: RuntimeConfig) {
    this.named = namedConfig(runtime);
  }

  public static configPaths(arguments_: readonly string[]) {
    return parseConfigArguments(arguments_);
  }

  protected static async loadRuntime(arguments_: readonly string[]): Promise<RuntimeConfig> {
    const paths = ConfigGenerated.configPaths(arguments_);
    const runtime = await loadRuntimeConfig({
      configPath: paths.configPath,
      valuesPath: paths.valuesPath,
      defaults: DEFAULT_CONFIG,
      patches: ENVIRONMENT_PATCHES,
      schema: canonicalConfigSchema
    });
    return runtime;
  }
}
