services:
  inventoryservice:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DOCKER_TARGET:-runtime}
      extra_hosts:
        - "host.docker.internal:host-gateway"
      args:
        NPM_CONFIG_REGISTRY: ${NPM_CONFIG_REGISTRY:-https://registry.npmjs.org/}
        DEPENDENCY_GITHUB_RAW_URL: ${DEPENDENCY_GITHUB_RAW_URL:-https://github.com}
    image: inventoryservice-typescript:latest
    command: ["--config", "config/config.yaml", "--values", "config/docker_overrides.yaml"]
    environment:
      - DEBUG=${DEBUG:-0}
      - NODE_DIAGNOSTIC_DIR=/tmp/node-diagnostics
    ports:
      - "9092:9092"
      - "9202:9202"
      - "2345:2345"
