#!/bin/sh
# Code generated by servicegen. DO NOT EDIT.
set -eu

project_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

remove_source_cache() {
  source_cache="$project_dir/.cpp-source-cache"
  if [ -d "$source_cache" ]; then
    rm -rf -- "$source_cache"
    echo "[dependency-source-cache] removed $source_cache"
  else
    echo "[dependency-source-cache] no project source cache"
  fi
}

remove_cmake_volumes() {
  if ! command -v docker >/dev/null 2>&1; then
    echo "[dependency-source-cache] Docker is unavailable; no CMake volumes removed"
    return
  fi

  found=0
  for compose_file in docker-compose.cmake.generated.yml docker-compose.yml; do
    if [ ! -f "$project_dir/$compose_file" ]; then
      continue
    fi
    volume_names=$(
      docker compose -f "$project_dir/$compose_file" config --format json 2>/dev/null |
        python3 -c 'import json, sys
try:
    config = json.load(sys.stdin)
except json.JSONDecodeError:
    raise SystemExit(0)
for key, value in config.get("volumes", {}).items():
    name = value.get("name", key) if isinstance(value, dict) else key
    if "cpp-cmake-build" in key or "cpp-cmake-build" in name:
        print(name)'
    )
    for volume_name in $volume_names; do
      found=1
      if docker volume inspect "$volume_name" >/dev/null 2>&1; then
        docker volume rm "$volume_name"
        echo "[dependency-source-cache] removed CMake volume $volume_name"
      fi
    done
  done
  if [ "$found" -eq 0 ]; then
    echo "[dependency-source-cache] no CMake build volumes"
  fi
}

case "${1:-invalidate}" in
  invalidate)
    remove_source_cache
    remove_cmake_volumes
    echo "[dependency-source-cache] ccache and Nexus data preserved"
    ;;
  *)
    echo "usage: $0 invalidate" >&2
    exit 2
    ;;
esac