#!/bin/sh
# Code generated by servicegen. DO NOT EDIT.
set -eu

request_path=${PATH_INFO:-}
if [ "$request_path" = "/__servicegen_health" ]; then
  printf 'Content-Type: text/plain\r\n\r\nok\n'
  exit 0
fi
if [ "$request_path" = "/__servicegen_refresh" ]; then
  if [ "${DEPENDENCY_GIT_MIRROR_OFFLINE:-0}" = "1" ]; then
    printf 'Status: 503 Service Unavailable\r\nContent-Type: text/plain\r\n\r\nGit mirror is offline; refresh is disabled\n'
    exit 0
  fi
  if [ "${REQUEST_METHOD:-GET}" != "POST" ]; then
    printf 'Status: 405 Method Not Allowed\r\nContent-Type: text/plain\r\n\r\nPOST required\n'
    exit 0
  fi
  output="/tmp/servicegen-git-refresh.$$"
  mirrors="/tmp/servicegen-git-mirrors.$$"
  active_lock=
  trap 'rm -f "$output" "$mirrors"; [ -z "$active_lock" ] || rmdir "$active_lock" 2>/dev/null || true' EXIT HUP INT TERM
  status=0
  if [ "${CONTENT_LENGTH:-0}" -gt 0 ]; then
    request="/tmp/servicegen-git-refresh-request.$$"
    trap 'rm -f "$output" "$mirrors" "$request"; [ -z "$active_lock" ] || rmdir "$active_lock" 2>/dev/null || true' EXIT HUP INT TERM
    dd bs=1 count="$CONTENT_LENGTH" of="$request" 2>/dev/null
    : >"$mirrors"
    while IFS= read -r repository || [ -n "$repository" ]; do
      case "$repository" in
        github.com/*|gitlab.com/*) ;;
        *) echo "[dependency-cache] invalid Git repository: $repository" >>"$output"; status=1; break ;;
      esac
      cached_mirror="/mirrors/${repository%.git}.git"
      if [ ! -d "$cached_mirror" ]; then
        echo "[dependency-cache] Git mirror is not cached: $repository" >>"$output"
        status=1
        break
      fi
      printf '%s\n' "$cached_mirror" >>"$mirrors"
    done <"$request"
  else
    find /mirrors -type d -name '*.git' -prune -print >"$mirrors"
  fi
  while [ "$status" -eq 0 ] && IFS= read -r cached_mirror; do
    [ -n "$cached_mirror" ] || continue
    cached_lock="${cached_mirror}.lock"
    active_lock=$cached_lock
    attempt=0
    until mkdir "$cached_lock" 2>/dev/null; do
      attempt=$((attempt + 1))
      if [ "$attempt" -ge 1200 ]; then
        echo "[dependency-cache] lock timeout: $cached_mirror" >>"$output"
        status=1
        break
      fi
      sleep 0.1
    done
    [ "$status" -eq 0 ] || break
    echo "[dependency-cache] refreshing ${cached_mirror#/mirrors/}" >>"$output"
    refresh_attempt=1
    refresh_succeeded=0
    while [ "$refresh_attempt" -le 3 ]; do
      if git -C "$cached_mirror" remote update --prune >>"$output" 2>&1; then
        refresh_succeeded=1
        break
      fi
      if [ "$refresh_attempt" -lt 3 ]; then
        echo "[dependency-cache] refresh failed; retry $((refresh_attempt + 1))/3: ${cached_mirror#/mirrors/}" >>"$output"
        sleep 2
      fi
      refresh_attempt=$((refresh_attempt + 1))
    done
    if [ "$refresh_succeeded" -eq 1 ]; then
      touch "$cached_mirror/servicegen-last-refresh"
      rmdir "$cached_lock"
      active_lock=
    else
      status=1
      rmdir "$cached_lock"
      active_lock=
      break
    fi
  done <"$mirrors"
  if [ "$status" -eq 0 ]; then
    printf 'Content-Type: text/plain\r\n\r\n'
    if [ -s "$output" ]; then cat "$output"; else echo '[dependency-cache] no cached Git mirrors to refresh'; fi
  else
    printf 'Status: 502 Bad Gateway\r\nContent-Type: text/plain\r\n\r\n'
    cat "$output"
  fi
  exit 0
fi
case "$request_path" in
  /github.com/*/info/refs|/gitlab.com/*/info/refs)
    service_path=/info/refs
    repository_path=${request_path%/info/refs}
    ;;
  /github.com/*/git-upload-pack|/gitlab.com/*/git-upload-pack)
    service_path=/git-upload-pack
    repository_path=${request_path%/git-upload-pack}
    ;;
  /github.com/*/git-receive-pack|/gitlab.com/*/git-receive-pack)
    service_path=/git-receive-pack
    repository_path=${request_path%/git-receive-pack}
    ;;
  *)
    printf 'Status: 400 Bad Request\r\nContent-Type: text/plain\r\n\r\ninvalid Git mirror path\n'
    exit 0
    ;;
esac

case "$repository_path" in
  *.git) ;;
  *) repository_path=${repository_path}.git ;;
esac
case "$repository_path" in
  *..*|*//*|*[!A-Za-z0-9._/-]*)
    printf 'Status: 400 Bad Request\r\nContent-Type: text/plain\r\n\r\ninvalid Git repository path\n'
    exit 0
    ;;
esac

mirror="/mirrors${repository_path}"
upstream="https://${repository_path#/}"
lock="${mirror}.lock"
mkdir -p "$(dirname "$mirror")"

attempt=0
until mkdir "$lock" 2>/dev/null; do
  attempt=$((attempt + 1))
  if [ "$attempt" -ge 1200 ]; then
    printf 'Status: 503 Service Unavailable\r\nContent-Type: text/plain\r\n\r\nGit mirror lock timeout\n'
    exit 0
  fi
  sleep 0.1
done
trap 'rmdir "$lock" 2>/dev/null || true' EXIT HUP INT TERM

if [ ! -d "$mirror" ]; then
  if [ "${DEPENDENCY_GIT_MIRROR_OFFLINE:-0}" = "1" ]; then
    printf 'Status: 404 Not Found\r\nContent-Type: text/plain\r\n\r\nrepository is not present in the offline Git mirror\n'
    exit 0
  fi
  temporary="${mirror}.tmp.$$"
  rm -rf "$temporary"
  if ! git clone --mirror "$upstream" "$temporary" >&2; then
    rm -rf "$temporary"
    printf 'Status: 502 Bad Gateway\r\nContent-Type: text/plain\r\n\r\nfailed to mirror upstream repository\n'
    exit 0
  fi
  mv "$temporary" "$mirror"
  touch "$mirror/servicegen-last-refresh"
fi

trap - EXIT HUP INT TERM
rmdir "$lock"
export GIT_PROJECT_ROOT=/mirrors
export GIT_HTTP_EXPORT_ALL=1
export PATH_INFO="${repository_path}${service_path}"
exec git http-backend