apiVersion: v1
kind: Service
metadata:
  name: {{ include "automationservice.fullname" . }}
  labels:
    {{ include "automationservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{ include "automationservice.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: temporal-sdk
      port: {{ .Values.service.temporalSdkMetricsPort }}
      targetPort: temporal-sdk
      protocol: TCP
{{- if eq .Values.workloadType "StatefulSet" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "automationservice.fullname" .) }}
  labels:
    {{ include "automationservice.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{ include "automationservice.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
    - name: temporal-sdk
      port: {{ .Values.service.temporalSdkMetricsPort }}
      targetPort: temporal-sdk
      protocol: TCP
{{- end }}