{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "automationservice.fullname" . }}
  labels:
    {{ include "automationservice.labels" . | nindent 4 }}
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{ include "automationservice.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.serviceMonitor.path }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      honorLabels: true
    {{- if .Values.metrics.temporalSdk.enabled }}
    - port: temporal-sdk-metrics
      path: {{ .Values.metrics.temporalSdk.path }}
      interval: {{ .Values.metrics.temporalSdk.interval }}
      honorLabels: true
      relabelings:
        - targetLabel: telemetry_source
          replacement: temporal-sdk
        - targetLabel: service
          replacement: "automationservice"
    {{- end }}
{{- end }}