dataConnectors:
  inventoryServiceApi:
    address: dns:///localhost:9202
    connectionsCount: 1
  orderEvents:
    brokers: redpanda:9092
    password: ""
    saslMechanism: SCRAM-SHA-512
    securityProtocol: PLAINTEXT
    username: ""
endpoints:
  orderProcessed:
    enabled: true
pools:
  defaultPool:
    executorsCount: 2
services:
  orderService:
    defaultGrpcTimeout: 0
    environment: ""
    grpcHost: 0.0.0.0
    grpcPort: 9201
    httpHost: 0.0.0.0
    httpPort: 9091
streams:
  softDeadline:
    duration: 1000
