// Code generated by servicegen. DO NOT EDIT.

import {
  canonicalConfigSchema,
  loadRuntimeConfig,
  parseConfigArguments,
  type EnvironmentPatch,
  type RuntimeConfig,
  requireCronDataConnectorConfig,
  type CronDataConnectorConfig,
  type CronDataConnectorConfigDocument,
  requireCronEndpointConfig,
  type CronEndpointConfig,
  type CronEndpointConfigDocument,
  requireInputStreamConfig,
  type InputStreamConfig,
  type InputStreamConfigDocument,
  type LinkConfigDocument,
  requireMapStreamConfig,
  type MapStreamConfig,
  type MapStreamConfigDocument,
  requireMergeStreamConfig,
  type MergeStreamConfig,
  type MergeStreamConfigDocument,
  type ModuleConfig,
  type ModuleConfigDocument,
  type ServiceConfig,
  type ServiceConfigDocument,
  requireSinkStreamConfig,
  type SinkStreamConfig,
  type SinkStreamConfigDocument,
  requireTemporalDataConnectorConfig,
  type TemporalDataConnectorConfig,
  type TemporalDataConnectorConfigDocument,
  requireTemporalEndpointConfig,
  type TemporalEndpointConfig,
  type TemporalEndpointConfigDocument,
  type TypeConfig,
  type TypeConfigDocument,
} from "@gorundebug/tsservicelib/runtime/config";

export const ServiceIds = {
  AUTOMATION_SERVICE: 1,
} as const;

export const StreamIds = {
  CONSUME_DURABLE_JOB: 1,
  LOCAL_SCHEDULE: 2,
  MAKE_LOCAL_JOB: 3,
  MAKE_TEMPORAL_JOB: 4,
  MERGE_JOB_SUBMISSIONS: 5,
  PROCESS_DURABLE_JOB: 6,
  SUBMIT_DURABLE_JOB: 7,
  TEMPORAL_SCHEDULE: 8,
} as const;

export const DataConnectorIds = {
  LOCAL_CRON: 1,
  TEMPORAL: 2,
} as const;

export const EndpointIds = {
  DURABLE_JOB: 2,
  LOCAL_SCHEDULE: 1,
  TEMPORAL_SCHEDULE: 3,
} as const;

export interface NamedConfig {
  readonly services: {
    readonly automationService: ServiceConfig;
  };
  readonly streams: {
    readonly consumeDurableJob: InputStreamConfig;
    readonly localSchedule: InputStreamConfig;
    readonly makeLocalJob: MapStreamConfig;
    readonly makeTemporalJob: MapStreamConfig;
    readonly mergeJobSubmissions: MergeStreamConfig;
    readonly processDurableJob: MapStreamConfig;
    readonly submitDurableJob: SinkStreamConfig;
    readonly temporalSchedule: InputStreamConfig;
  };
  readonly dataConnectors: {
    readonly localCron: CronDataConnectorConfig;
    readonly temporal: TemporalDataConnectorConfig;
  };
  readonly endpoints: {
    readonly durableJob: TemporalEndpointConfig;
    readonly localSchedule: CronEndpointConfig;
    readonly temporalSchedule: TemporalEndpointConfig;
  };
  readonly pools: {
  };
  readonly modules: {
    readonly inventoryServiceApi: ModuleConfig;
    readonly model: ModuleConfig;
    readonly orderServiceApi: ModuleConfig;
  };
  readonly types: {
    readonly scheduleTrigger: TypeConfig;
    readonly string_: TypeConfig;
  };
}

interface DefaultConfig {
  readonly services: {
    readonly "automationService": ServiceConfigDocument;
  };
  readonly streams: {
    readonly "consumeDurableJob": InputStreamConfigDocument;
    readonly "localSchedule": InputStreamConfigDocument;
    readonly "makeLocalJob": MapStreamConfigDocument;
    readonly "makeTemporalJob": MapStreamConfigDocument;
    readonly "mergeJobSubmissions": MergeStreamConfigDocument;
    readonly "processDurableJob": MapStreamConfigDocument;
    readonly "submitDurableJob": SinkStreamConfigDocument;
    readonly "temporalSchedule": InputStreamConfigDocument;
  };
  readonly dataConnectors: {
    readonly "localCron": CronDataConnectorConfigDocument;
    readonly "temporal": TemporalDataConnectorConfigDocument;
  };
  readonly endpoints: {
    readonly "durableJob": TemporalEndpointConfigDocument;
    readonly "localSchedule": CronEndpointConfigDocument;
    readonly "temporalSchedule": TemporalEndpointConfigDocument;
  };
  readonly pools: {
  };
  readonly links: {
    readonly "consumeDurableJobToProcessDurableJob": LinkConfigDocument;
  };
  readonly modules: {
    readonly "inventoryServiceApi": ModuleConfigDocument;
    readonly "model": ModuleConfigDocument;
    readonly "orderServiceApi": ModuleConfigDocument;
  };
  readonly types: {
    readonly "scheduleTrigger": TypeConfigDocument;
    readonly "string": TypeConfigDocument;
  };
}

const DEFAULT_CONFIG = {
  "services": {
    "automationService": {
      "color": "#00A86B",
      "defaultCallSemantics": 2,
      "defaultGrpcTimeout": 0,
      "environment": "",
      "golangVersion": "1.25.4",
      "grpcHost": "0.0.0.0",
      "grpcPort": 9204,
      "httpHost": "0.0.0.0",
      "httpPort": 9094,
      "id": 1,
      "metricsHandler": "metrics",
      "startupHandler": "health/startup",
      "readinessHandler": "health/ready",
      "livenessHandler": "health/live",
      "kubernetesWorkloadType": "Deployment",
      "modulePath": "github.com/gorundebug/tsexample-automationservice",
      "name": "Automation Service",
      "shutdownTimeout": 30000,
      "statusHandler": "status"
    }
  },
  "streams": {
    "consumeDurableJob": {
      "id": 1,
      "idEndpoint": 2,
      "idService": 1,
      "idSource": 6,
      "name": "Consume Durable Job",
      "pipeline": "automation",
      "type": 1,
      "valueType": "string",
      "xPos": -130,
      "yPos": -330
    },
    "localSchedule": {
      "id": 2,
      "idEndpoint": 1,
      "idService": 1,
      "idSource": 0,
      "name": "Local Schedule",
      "pipeline": "automation",
      "type": 1,
      "valueType": "ScheduleTrigger",
      "xPos": -1050,
      "yPos": -480
    },
    "makeLocalJob": {
      "functionDescription": "Create a job message identifying the local scheduled firing.\n",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "LocalJob",
      "functionPackage": "",
      "id": 3,
      "idService": 1,
      "idSource": 2,
      "name": "Make Local Job",
      "pipeline": "automation",
      "type": 2,
      "valueType": "string",
      "xPos": -820,
      "yPos": -480
    },
    "makeTemporalJob": {
      "functionDescription": "Create a job message identifying the durable scheduled firing.\n",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "TemporalJob",
      "functionPackage": "",
      "id": 4,
      "idService": 1,
      "idSource": 8,
      "name": "Make Temporal Job",
      "pipeline": "automation",
      "type": 2,
      "valueType": "string",
      "xPos": -820,
      "yPos": -180
    },
    "mergeJobSubmissions": {
      "id": 5,
      "idService": 1,
      "idSource": 0,
      "idSources": [
        3,
        4
      ],
      "name": "Merge Job Submissions",
      "pipeline": "automation",
      "type": 10,
      "xPos": -570,
      "yPos": -330
    },
    "processDurableJob": {
      "functionDescription": "Process one accepted automation job and return its result.\n",
      "functionInitializerGroup": "",
      "functionModule": "",
      "functionName": "ProcessDurableJob",
      "functionPackage": "",
      "id": 6,
      "idService": 1,
      "idSource": 1,
      "name": "Process Durable Job",
      "pipeline": "automation",
      "type": 2,
      "valueType": "string",
      "xPos": 140,
      "yPos": -330
    },
    "submitDurableJob": {
      "id": 7,
      "idEndpoint": 2,
      "idService": 1,
      "idSource": 5,
      "name": "Submit Durable Job",
      "pipeline": "automation",
      "type": 13,
      "valueType": "string",
      "xPos": -360,
      "yPos": -330
    },
    "temporalSchedule": {
      "id": 8,
      "idEndpoint": 3,
      "idService": 1,
      "idSource": 0,
      "name": "Temporal Schedule",
      "pipeline": "automation",
      "type": 1,
      "valueType": "ScheduleTrigger",
      "xPos": -1050,
      "yPos": -180
    }
  },
  "dataConnectors": {
    "localCron": {
      "id": 1,
      "implementation": "node/croner",
      "name": "Local Cron",
      "type": 5
    },
    "temporal": {
      "address": "temporal:7233",
      "id": 2,
      "identity": "example-automation",
      "implementation": "temporal/typescript",
      "maxConcurrentActivities": 2,
      "maxConcurrentWorkflows": 4,
      "name": "Temporal",
      "namespace": "default",
      "type": 6
    }
  },
  "endpoints": {
    "durableJob": {
      "activityHeartbeatTimeout": 5000,
      "activityStartToCloseTimeout": 30000,
      "enabled": true,
      "id": 2,
      "idDataConnector": 2,
      "maximumAttempts": 3,
      "name": "Durable Job",
      "taskQueue": "automation-jobs",
      "workflowExecutionTimeout": 60000
    },
    "localSchedule": {
      "enabled": true,
      "id": 1,
      "idDataConnector": 1,
      "missedRunPolicy": "FireOnce",
      "name": "Local Schedule",
      "overlapPolicy": "Skip",
      "schedule": "*/5 * * * *",
      "timezone": "UTC"
    },
    "temporalSchedule": {
      "activityHeartbeatTimeout": 5000,
      "activityStartToCloseTimeout": 30000,
      "enabled": true,
      "id": 3,
      "idDataConnector": 2,
      "maximumAttempts": 3,
      "missedRunPolicy": "FireOnce",
      "name": "Temporal Schedule",
      "overlapPolicy": "Skip",
      "schedule": "*/10 * * * *",
      "scheduleId": "example-automation-schedule",
      "taskQueue": "automation-schedules",
      "timezone": "UTC",
      "workflowExecutionTimeout": 60000
    }
  },
  "pools": {},
  "links": {
    "consumeDurableJobToProcessDurableJob": {
      "activityHeartbeatTimeout": 5000,
      "activityStartToCloseTimeout": 30000,
      "callSemantics": 6,
      "from": 1,
      "idDataConnector": 2,
      "maximumAttempts": 3,
      "taskQueue": "automation-durable-calls",
      "to": 6,
      "workflowExecutionTimeout": 60000
    }
  },
  "modules": {
    "inventoryServiceApi": {
      "name": "inventory_service_api",
      "path": "github.com/gorundebug/tsexample-inventory-service-api"
    },
    "model": {
      "name": "model",
      "path": "github.com/gorundebug/tsexample-model"
    },
    "orderServiceApi": {
      "name": "order_service_api",
      "path": "github.com/gorundebug/tsexample-order-service-api"
    }
  },
  "types": {
    "scheduleTrigger": {
      "name": "ScheduleTrigger",
      "type": "schedule trigger",
      "typeDefinition": "ScheduleTrigger",
      "typeImport": "@gorundebug/tsservicelib/runtime"
    },
    "string": {
      "name": "string",
      "type": "string",
      "typeDefinition": "string",
      "typeImport": "./internal/types/string.js"
    }
  }
} as const satisfies DefaultConfig;

export function parseStringEnvironment(value: string): string { return value; }

export function parseIntegerEnvironment(value: string): number {
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed)) throw new Error(`expected an integer, got ${value}`);
  return parsed;
}

export function parseNumberEnvironment(value: string): number {
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) throw new Error(`expected a number, got ${value}`);
  return parsed;
}

export function parseBooleanEnvironment(value: string): boolean {
  switch (value.trim().toLowerCase()) {
    case "1": case "true": case "yes": case "on": return true;
    case "0": case "false": case "no": case "off": return false;
    default: throw new Error(`expected a boolean, got ${value}`);
  }
}

export function parseStringListEnvironment(value: string): readonly string[] {
  return value.split(",").map((item) => item.trim()).filter((item) => item.length > 0);
}

export function parseIntegerListEnvironment(value: string): readonly number[] {
  return parseStringListEnvironment(value).map(parseIntegerEnvironment);
}

const ENVIRONMENT_PATCHES: readonly EnvironmentPatch[] = [
  { environment: "AUTOMATION_SERVICE_DEFAULT_GRPC_TIMEOUT", path: ["services", "automationService", "defaultGrpcTimeout", ], parse: parseIntegerEnvironment },
  { environment: "AUTOMATION_SERVICE_ENVIRONMENT", path: ["services", "automationService", "environment", ], parse: parseStringEnvironment },
  { environment: "AUTOMATION_SERVICE_GRPC_HOST", path: ["services", "automationService", "grpcHost", ], parse: parseStringEnvironment },
  { environment: "AUTOMATION_SERVICE_GRPC_PORT", path: ["services", "automationService", "grpcPort", ], parse: parseIntegerEnvironment },
  { environment: "AUTOMATION_SERVICE_HTTP_HOST", path: ["services", "automationService", "httpHost", ], parse: parseStringEnvironment },
  { environment: "AUTOMATION_SERVICE_HTTP_PORT", path: ["services", "automationService", "httpPort", ], parse: parseIntegerEnvironment },
  { environment: "DURABLE_JOB_ENABLED", path: ["endpoints", "durableJob", "enabled", ], parse: parseBooleanEnvironment },
  { environment: "LOCAL_SCHEDULE_ENABLED", path: ["endpoints", "localSchedule", "enabled", ], parse: parseBooleanEnvironment },
  { environment: "TEMPORAL_ADDRESS", path: ["dataConnectors", "temporal", "address", ], parse: parseStringEnvironment },
  { environment: "TEMPORAL_SCHEDULE_ENABLED", path: ["endpoints", "temporalSchedule", "enabled", ], parse: parseBooleanEnvironment },
];

function required<T>(value: T | undefined, description: string): T {
  if (value === undefined) throw new Error(`missing ${description}`);
  return value;
}

function namedConfig(runtime: RuntimeConfig): NamedConfig {
  return {
    services: {
      automationService: required(runtime.serviceById(ServiceIds.AUTOMATION_SERVICE), "Automation Service"),
    },
    streams: {
      consumeDurableJob: requireInputStreamConfig(runtime.streamById(StreamIds.CONSUME_DURABLE_JOB)),
      localSchedule: requireInputStreamConfig(runtime.streamById(StreamIds.LOCAL_SCHEDULE)),
      makeLocalJob: requireMapStreamConfig(runtime.streamById(StreamIds.MAKE_LOCAL_JOB)),
      makeTemporalJob: requireMapStreamConfig(runtime.streamById(StreamIds.MAKE_TEMPORAL_JOB)),
      mergeJobSubmissions: requireMergeStreamConfig(runtime.streamById(StreamIds.MERGE_JOB_SUBMISSIONS)),
      processDurableJob: requireMapStreamConfig(runtime.streamById(StreamIds.PROCESS_DURABLE_JOB)),
      submitDurableJob: requireSinkStreamConfig(runtime.streamById(StreamIds.SUBMIT_DURABLE_JOB)),
      temporalSchedule: requireInputStreamConfig(runtime.streamById(StreamIds.TEMPORAL_SCHEDULE)),
    },
    dataConnectors: {
      localCron: requireCronDataConnectorConfig(runtime.dataConnectorById(DataConnectorIds.LOCAL_CRON)),
      temporal: requireTemporalDataConnectorConfig(runtime.dataConnectorById(DataConnectorIds.TEMPORAL)),
    },
    endpoints: {
      durableJob: requireTemporalEndpointConfig(runtime.endpointById(EndpointIds.DURABLE_JOB)),
      localSchedule: requireCronEndpointConfig(runtime.endpointById(EndpointIds.LOCAL_SCHEDULE)),
      temporalSchedule: requireTemporalEndpointConfig(runtime.endpointById(EndpointIds.TEMPORAL_SCHEDULE)),
    },
    pools: {
    },
    modules: {
      inventoryServiceApi: required(runtime.moduleByName("inventory_service_api"), "inventory_service_api"),
      model: required(runtime.moduleByName("model"), "model"),
      orderServiceApi: required(runtime.moduleByName("order_service_api"), "order_service_api"),
    },
    types: {
      scheduleTrigger: required(runtime.typeByName("ScheduleTrigger"), "ScheduleTrigger"),
      string_: required(runtime.typeByName("string"), "string"),
    }
  };
}

export class ConfigGenerated {
  public readonly named: NamedConfig;

  public constructor(public readonly runtime: RuntimeConfig) {
    this.named = namedConfig(runtime);
  }

  public static configPaths(arguments_: readonly string[]) {
    return parseConfigArguments(arguments_);
  }

  protected static async loadRuntime(arguments_: readonly string[]): Promise<RuntimeConfig> {
    const paths = ConfigGenerated.configPaths(arguments_);
    const runtime = await loadRuntimeConfig({
      configPath: paths.configPath,
      valuesPath: paths.valuesPath,
      defaults: DEFAULT_CONFIG,
      patches: ENVIRONMENT_PATCHES,
      schema: canonicalConfigSchema
    });
    return runtime;
  }
}
