# Code generated by servicegen. DO NOT EDIT.
MODULE_DIR := $(abspath .)
TOOLS_DIR ?= $(MODULE_DIR)/tools
PNPM ?= env CI=true corepack pnpm
PROGRESS := ./scripts/run-with-progress.generated.sh
SERVICEGEN_GITHUB_RAW_URL ?= https://github.com
ifneq ($(strip $(SERVICEGEN_DEPENDENCY_PROXY_DIR)),)
SERVICEGEN_DEPENDENCY_PROXY_HOST ?= localhost
SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST ?= host.docker.internal
SERVICEGEN_DEPENDENCY_PROXY_PORT ?= 18081
SERVICEGEN_DEPENDENCY_PROXY_DOCKER_ARGS := --add-host host.docker.internal:host-gateway
export NPM_CONFIG_REGISTRY := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/npm-proxy/
export SERVICEGEN_GITHUB_RAW_URL := http://$(SERVICEGEN_DEPENDENCY_PROXY_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/github-raw
docker-build: export NPM_CONFIG_REGISTRY := http://$(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_HOST):$(SERVICEGEN_DEPENDENCY_PROXY_PORT)/repository/npm-proxy/
endif
BUF_VERSION := v1.47.2
BUF ?= $(TOOLS_DIR)/buf
OS := $(shell uname -s)
ARCH := $(shell uname -m)

.PHONY: install generate build test docker-build clean

install:
	@if [ -f pnpm-lock.yaml ] || [ -f ../pnpm-lock.yaml ]; then \
		$(PROGRESS) "TypeScript dependency install" $(PNPM) install --frozen-lockfile; \
	else \
		$(PROGRESS) "TypeScript dependency install" $(PNPM) install; \
	fi

generate: $(BUF)
	@if [ "$(SKIP_INSTALL)" != "1" ]; then $(MAKE) install; fi
	@set -eu; for script in $$(find . -name 'generate-*.generated.sh' -type f | sort); do \
		$(PROGRESS) "Generate TypeScript artifacts with $$script" \
			env BUF="$(BUF)" "$$script"; \
	done

build: generate
	@$(PROGRESS) "TypeScript package build" $(PNPM) build

test: build
	@$(PROGRESS) "TypeScript package tests" $(PNPM) test

docker-build: ## Verify this independent contract/model package in Docker
	@$(PROGRESS) "TypeScript package Docker build and export" \
		docker build $(SERVICEGEN_DEPENDENCY_PROXY_DOCKER_ARGS) --build-arg NPM_CONFIG_REGISTRY="$${NPM_CONFIG_REGISTRY:-https://registry.npmjs.org/}" \
		--build-arg CONFLUENT_KAFKA_JAVASCRIPT_BINARY_HOST_MIRROR="$${SERVICEGEN_GITHUB_RAW_URL:-https://github.com}/confluentinc/confluent-kafka-javascript/releases/download/" \
		-f Dockerfile.generated -t "inventory_service_api-typescript-package:latest" .

clean:
	@rm -rf dist tsconfig.tsbuildinfo
$(BUF):
	@mkdir -p "$(TOOLS_DIR)"
	@$(PROGRESS) "Download buf $(BUF_VERSION)" \
		curl --fail --location --silent --show-error \
		"$(SERVICEGEN_GITHUB_RAW_URL)/bufbuild/buf/releases/download/$(BUF_VERSION)/buf-$(OS)-$(ARCH)" \
		-o "$(BUF)"
	@chmod +x "$(BUF)"
