# Code generated by servicegen. DO NOT EDIT.
# Make prerequisites need backslash escaping; shell arguments need quotes instead.
make_empty :=
make_space := $(make_empty) $(make_empty)
make_escape_path = $(subst $(make_space),\$(make_space),$(1))
MODULE_DIR := $(abspath .)
TOOLS_DIR ?= $(MODULE_DIR)/tools
PROGRESS := ./scripts/run-with-progress.generated.sh
DEPENDENCY_PNPM_REGISTRY_ARG = $(if $(strip $(NPM_CONFIG_REGISTRY)),--config.registry=$(NPM_CONFIG_REGISTRY),)
# Keep SHELL relative: GNU Make parses an absolute shell path containing spaces as words.
DEPENDENCY_DOWNLOAD_ENV := $(if $(wildcard dependency-download-env.generated.sh),./dependency-download-env.generated.sh,$(if $(wildcard ../dependency-download-env.generated.sh),../dependency-download-env.generated.sh,/bin/sh))
SHELL := $(DEPENDENCY_DOWNLOAD_ENV)
.SHELLFLAGS := -c
export
DEPENDENCY_DOCKER_TARGETS := docker-build
include dependency-proxy.generated.mk
PNPM ?= env CI=true \
	corepack pnpm $(DEPENDENCY_PNPM_REGISTRY_ARG)
BUF_VERSION := v1.47.2
BUF ?= $(TOOLS_DIR)/buf
OS := $(shell uname -s)
ARCH := $(shell uname -m)

.PHONY: install generate build test docker-build clean

install:
	@if [ -f pnpm-lock.yaml ] || [ -f ../pnpm-lock.yaml ]; then \
		$(PROGRESS) "TypeScript dependency install" $(PNPM) install --frozen-lockfile; \
	else \
		$(PROGRESS) "TypeScript dependency install" $(PNPM) install; \
	fi

generate: $(call make_escape_path,$(BUF))
	@if [ "$(SKIP_INSTALL)" != "1" ]; then $(MAKE) install; fi
	@set -eu; find . -name 'generate-*.generated.sh' -type f | sort | while IFS= read -r script; do \
		$(PROGRESS) "Generate TypeScript artifacts with $$script" \
			env BUF="$(BUF)" "$$script"; \
	done

build: generate ## [host] Compile this standalone package
	@$(PROGRESS) "TypeScript package build" $(PNPM) build

test: build ## [host] Run this standalone package's tests
	@$(PROGRESS) "TypeScript package tests" $(PNPM) test

docker-build: ## [Docker] Verify this independent contract/model package
	@$(PROGRESS) "TypeScript package Docker build and export" \
		docker build $(DEPENDENCY_PROXY_DOCKER_ARGS) \
		--build-arg DEPENDENCY_DOCKER_REGISTRY="$${DEPENDENCY_DOCKER_REGISTRY:-docker.io}" \
		--build-arg NPM_CONFIG_REGISTRY="$${NPM_CONFIG_REGISTRY:-https://registry.npmjs.org/}" \
		--build-arg DEPENDENCY_GITHUB_RAW_URL="$${DEPENDENCY_GITHUB_RAW_URL:-https://github.com}" \
		--build-arg DEPENDENCY_APT_DEBIAN_URL="$${DEPENDENCY_APT_DEBIAN_URL:-}" \
		--build-arg DEPENDENCY_APT_DEBIAN_SECURITY_URL="$${DEPENDENCY_APT_DEBIAN_SECURITY_URL:-}" \
		-f Dockerfile.generated -t "inventory_service_api-typescript-package:local" .

clean:
	@rm -rf dist tsconfig.tsbuildinfo
$(call make_escape_path,$(BUF)):
	@mkdir -p "$(TOOLS_DIR)"
	@$(PROGRESS) "Download buf $(BUF_VERSION)" \
		curl --fail --location --silent --show-error --connect-timeout 15 --speed-limit 1024 --speed-time 30 --retry 2 --retry-delay 2 --retry-max-time 30 --retry-all-errors \
		"$(DEPENDENCY_GITHUB_RAW_URL)/bufbuild/buf/releases/download/$(BUF_VERSION)/buf-$(OS)-$(ARCH)" \
		-o "$(BUF)"
	@chmod +x "$(BUF)"
